### ISSUE TITLE
Runtime error on iOS 11

### ISSUE THREAD

**Issue by ercote** [DataDog/dd-sdk-reactnative#105]
Hi DataDog team!

Here's an issue we encountered on our side related to using this SDK and running on iOS 11...

**Describe what happened**
With the package `@datadog/mobile-react-native` (version `1.0.0-rc2`) installed in our React Native app, we get a runtime error with this error message: `dyld: Symbol not found: _OBJC_CLASS_$_OS_dispatch_queue_serial`.
The app then crashes.

**Steps to reproduce the issue:**

- Install `@datadog/mobile-react-native` in a React Native (0.63.2) project.
- Install pods: `pod install --project-directory=ios`
- Run the app from Xcode on a simulator with iOS 11.4 installed.

**Describe what you expected:**

The application should be running without any issue.

**Additional context**
    - Xcode 12.5
    - Simulator 11.4
    - React Native 0.63.2

This issue arises specifically from that line:
https://github.com/DataDog/dd-sdk-reactnative/blame/main/packages/core/ios/Sources/QueueHolder.swift

This file uses `dispatch_queue_serial_t` which is available only from iOS 12+.
Apple documentation: https://developer.apple.com/documentation/dispatch/dispatch_queue_serial_t

Commit that introduced the bug: https://github.com/DataDog/dd-sdk-reactnative/commit/c568d7f1f39e5a639937d5ff0c6884c65896845d

Specific line: https://github.com/DataDog/dd-sdk-reactnative/commit/c568d7f1f39e5a639937d5ff0c6884c65896845d#diff-0288ae99caf2c07d91fce825c748ddaa7b97c2514b32317bf3eb048257804436R9

**Comment by 0xnm** [comment]
Hello @ercote! Thanks for raising the issue. It was fixed and fix will be available in the next SDK release.

**Comment by ercote** [comment]
Thank you @0xnm for the quick fix! Greatly appreciated.
