### ISSUE TITLE
[Feature Request] add traced hosts API

### ISSUE THREAD

**Issue by Jekiwijaya** [DataDog/dd-sdk-reactnative#107]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Currently in Android SDK and iOS SDK can connect RUM to traces using tracedHosts config
https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=androidrum

It would be nice if in react native sdk it also opened the config to set the traced hosts.

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xnm** [comment]
Hello @Jekiwijaya. Currently our React Native SDK injects the necessary headers and it is possible to connect frontend and backend traces, there is just no possibility to filter out certain hosts. Can you please help us better understand your request: you don't see backend traces at all or you just want to explicitly specify traced hosts?

**Comment by louiszawadzki** [comment]
Hi,

We've released version 1.0.0-rc8 this week with traced hosts (officially designated as "first party hosts").

To use distributed tracing, you now need to specify your hosts as first-party hosts in your SDK config after upgrading to this version:

```
config.firstPartyHosts = ['example.com'];
```

I'm closing this issue, feel free to reopen it if you have any further problems :)
