### ISSUE TITLE
Source Discrepancy

### ISSUE THREAD

**Issue by bgneu** [DataDog/dd-sdk-reactnative#123]
**Describe what happened**
Update the SDK to the latest RC (1.0.0-rc3) and noticed the source that shows in Datadog for iOS logs is `react-native` while for Android, the source is `Android`. 

iOS
![Screen Shot 2021-11-02 at 11 20 52 AM](https://user-images.githubusercontent.com/29488885/139876450-a550f975-7b86-4571-ab78-d4576315a34c.png)

Android
![Screen Shot 2021-11-02 at 11 20 19 AM](https://user-images.githubusercontent.com/29488885/139876367-c5ffe921-67d7-4fe5-9caa-1fd0fdc79dfb.png)

**Steps to reproduce the issue:**
1. Follow the setup steps outlined in the README
2. Send any log from your React Native iOS and Android apps
3. Noticed the difference.

**Describe what you expected:**
All my logs are coming from React Native so I would expect the source to be `react-native` for both platforms. This didn't use to be a problem on the previous version of the SDK we were using (1.0.0-beta3)

**Additional context**
    - Version of the SDK: 1.0.0-rc3

**Comment by 0xnm** [comment]
Hello @bgneu. Thanks for noticing that! Indeed, it should be `react-native` for both. We will fix that bug.

**Comment by 0xnm** [comment]
Hello @bgneu. We just published version `1.0.0-rc4` which fixes the issue you've faced.
