### ISSUE TITLE
Apply iOS 15 crash fix to react native package?

### ISSUE THREAD

**Issue by computerjazz** [DataDog/dd-sdk-reactnative#124]
**Is your feature request related to a problem? Please describe.**
I am in the process of integrating the DataDog react native package, which includes DataDogSDKBridge 0.5.0 as a dependency (https://github.com/DataDog/dd-sdk-reactnative/blob/main/packages/core/DatadogSDKReactNative.podspec#L20), which in turn relies on DataDog iOS SDK `1.8.0-beta.1` (https://github.com/DataDog/dd-bridge-ios/blob/main/DatadogSDKBridge.podspec#L20).

DataDog iOS SDK 1.7.2 included a fix for an iOS 15 crash (https://github.com/DataDog/dd-sdk-ios/commit/5db35abd541709baed38c798819e2c51d3eb7066). We are hesitant about shipping code that could potentially crash. Any chance of getting the fix into the 1.8.x branch that ships with the react native package? Thanks!

**Describe the solution you'd like**
Update the react native package with the iOS 15 crash fix.

**Describe alternatives you've considered**
Forking all packages and applying the fix myself

**Comment by 0xnm** [comment]
Hello @computerjazz. Yes, once we see that this fix works for the broader audience, we will move it to the `1.8.0` branch as well and it will be shipped with the next release of React Native SDK.
