### ISSUE TITLE
Getting `helperSkipTransparentExpressionWrappers.skipTransparentExprWrapperNodes is not a function`

### ISSUE THREAD

**Issue by ziwon-kim-mox** [DataDog/dd-sdk-reactnative#134]
Thanks for taking the time for reporting an issue!

**Describe what happened**
I'm upgrading from 1.0.0-rc2 to 1.0.0-rc4. I tried 1.0.0-rc3, but facing the same errors.

DD Package versions:
```
    "@datadog/mobile-react-native": "1.0.0-rc3",
    "@datadog/mobile-react-navigation": "1.0.0-rc3",
```

I tried installing `@babel/helper-skip-transparent-expression-wrappers` as a dev dependency to try solve it, but didn't work.

Reverting back to 1.0.0-rc2 works well.

**Steps to reproduce the issue:**
Podfile has below part:
```
dynamic_frameworks = [['DatadogSDK','DatadogSDKObjc','Kronos'], ...].flatten

target 'app' do
  ...
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if !dynamic_frameworks.include?(pod.name)
        def pod.static_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
  ...
```

1. Upgrade to `1.0.0-rc3 or 4` for both `mobile-react-native` and `mobile-react-navigation`. (I'm using `react-navigation`).
2. Pod install
3. Run app

**Describe what you expected:**
No errors.

**Additional context**
    - Version of the SDK - 1.0.0-rc3 and 1.0.0-rc4
    - A copy of your `package.json` file - N/A

**Comment by 0xnm** [comment]
Hello @ziwon-kim-mox. Thanks for reporting this issue. To help us investigate it further, can you please share your `package.json` (we need the dependencies list you are using).

Also does this happen only on iOS? Or if you build for Android it happens as well?

**Comment by ziwon-kim-mox** [comment]
Hi 0xnm, Thanks for the prompt response. I did a full clean yarn install & pod update & pod install & restarted Metro and the error went away. Android also had issues but okay now. Sorry for the confusion. Thanks!
