### ISSUE TITLE
[Question][RUM Performance overview] PC75:LOADING TIME column of "Most viewed pages" table is "N/A"

### ISSUE THREAD

**Issue by tranducduong1994** [DataDog/dd-sdk-reactnative#139]
Hello,

Hello, I m so confuse about Most viewed pages in RUM - Performance overview. My application use React Native platform. PC75:LOADING TIME column of "Most viewed pages" table is always "N/A". Can datadog measure loading time ? Thank you

![image](https://user-images.githubusercontent.com/89118981/148515835-651423cd-945f-4f2b-b04c-126da0bb7877.png)

**Comment by tranducduong1994** [comment]
@0xnm Could you please help?

**Comment by 0xnm** [comment]
Hello @tranducduong1994. Our React Native SDK doesn't support measuring view loading time so far, but it might be the feature we can look at in the future.

**Comment by tranducduong1994** [comment]
@0xnm thank you. also, I have another question in this screen. I m confused about **VIEW PATH GROUP** column. My application use React Native platform. There are many “App” screens with unique suffixes. What are those? are they some popup and side menu?
![148515835-651423cd-945f-4f2b-b04c-126da0bb7877](https://user-images.githubusercontent.com/89118981/148553045-a9de8738-d8cb-49c5-a1ed-fe75f7396e20.png)

**Comment by 0xnm** [comment]
@tranducduong1994 I suppose you are using [@datadog/mobile-react-navigation](https://www.npmjs.com/package/@datadog/mobile-react-navigation) package? If yes, then in case of React Navigation it is just a unique identifier of the screen backed by [route.key](https://reactnavigation.org/docs/route-prop), you can see `route.name` by clicking Settings icon of this table and adding `@view.name` column.

**Comment by tranducduong1994** [comment]
@0xnm  I only see "Create Monitor" after click on setting button
![image](https://user-images.githubusercontent.com/89118981/148636032-65aab62c-8e3b-4721-a1d9-1d96b0150791.png)
Where can I customize this table's columns? thank you.

**Comment by 0xnm** [comment]
@tranducduong1994 Thanks for reporting that, indeed there is no option in that view. Anyway, we are currently migrating Application Overview page widgets so that they use `@view.name` facet instead, you should get it in soon (few weeks, probably).

Sorry for the temporary inconvenience.

**Comment by tranducduong1994** [comment]
thank you for your time @0xnm
