### ISSUE TITLE
RUM Actions are not logged shortly after SDK initialization

### ISSUE THREAD

**Issue by mjama-daily-harvest** [DataDog/dd-sdk-reactnative#141]
**Describe what happened**
For a short period after the SDK is initialized, RUM Actions logged with DdRum.addAction() do not appear in the Datadog RUM session

**Steps to reproduce the issue:**
```
await DdSdkReactNative.initialize(new DdSdkReactNativeConfiguration(...))
DdSdkReactNative.setUser(...)
DdRum.addAction(...)
```

**Describe what you expected:**
1. The SDK is fully initialized and ready to log RUM Actions directly after the Promise returned by DdSdkReactNative.initialize() fulfills, or
2. RUM Actions logged while the SDK has not finished initializing are not silently dropped

**Additional context**
```
    "@datadog/mobile-react-native": "1.0.0-rc4",
    "@datadog/mobile-react-navigation": "1.0.0-rc4",
    "@react-navigation/native": "5.9.8",
```
* DdRumReactNavigationTracking.startTrackingViews() is used [per docs](https://www.npmjs.com/package/@datadog/mobile-react-navigation#user-content-track-view-navigation)

**Comment by 0xnm** [comment]
Hello @mjama-daily-harvest! RUM Actions exist in the context of the views, so actions which are logged when there is no view active are dropped.

In your case I would suggest to move `addAction` call to the point when there is already a view started.

**Comment by mjama-daily-harvest** [comment]
@0xnm by starting a view with DdRum.startView() before making a call to DdRum.addAction(), action logging works as expected. Thanks!
