### ISSUE TITLE
RUM Events not showing in Play Store build

### ISSUE THREAD

**Issue by nimaprodigy** [DataDog/dd-sdk-reactnative#144]
I am having a strange issue where RUM seems to work brilliantly in all environments except production.

My app is android only at the moment.

Building my code locally (debug build) and running on emulator works perfectly for both RUM & Logs. 
Next I tried creating a release build and shipping it to Firebase App Distribution and installing in on a physical phone; both RUM and Logs also work great.
Then I create a release and send it to Google Play, and in that build RUM does not work. Logs do work still.
I have tried both manual view creation and tracking the NavigationContainer, but I can't get the build that goes to Google Play to work.

I have set the sample rate to 100 so as to not miss anything as well.

Would anyone have any idea what could be causing this?

Here is my package.json

```
"dependencies": {
    "@apollo/client": "^3.3.16",
    "@datadog/mobile-react-native": "^1.0.0-rc4",
    "@datadog/mobile-react-navigation": "^1.0.0-rc4",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-regular-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/pro-regular-svg-icons": "^5.15.3",
    "@fortawesome/pro-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-native-fontawesome": "^0.2.6",
    "@react-native-async-storage/async-storage": "^1.15.9",
    "@react-native-community/datetimepicker": "^3.4.7",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-firebase/app": "^14.2.2",
    "@react-native-firebase/crashlytics": "^14.2.2",
    "@react-native-firebase/messaging": "^14.2.2",
    "@react-native-firebase/perf": "^14.2.2",
    "@react-native-firebase/remote-config": "^14.2.2",
    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^5.14.5",
    "@reduxjs/toolkit": "^1.6.0",
    "@segment/analytics-react-native": "^1.4.8",
    "@types/ms": "^0.7.31",
    "@types/react-native-snap-carousel": "^3.8.3",
    "@types/styled-components": "^5.1.14",
    "@types/styled-components-react-native": "^5.1.1",
    "compare-versions": "3.6.0",
    "cross-fetch": "^3.1.4",
    "date-fns": "2.21.3",
    "expo-secure-store": "^10.1.0",
    "graphql": "^15.5.0",
    "graphql-request": "^3.4.0",
    "lodash": "^4.17.21",
    "ms": "^2.1.3",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-animated-pagination-dot": "^0.1.8",
    "react-native-app-auth": "6.4.0",
    "react-native-appstate-hook": "^1.0.5",
    "react-native-config": "^1.4.2",
    "react-native-device-info": "8.1.3",
    "react-native-dropdown-picker": "^5.1.28",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-push-notification": "^7.4.0",
    "react-native-reanimated": "^2.3.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.2.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.1",
    "react-native-svg-charts": "^5.4.0",
    "react-native-unimodules": "^0.14.10",
    "react-native-uuid": "^2.0.1",
    "react-redux": "^7.2.4",
    "styled-components": "^5.3.1"
```

**Comment by nimaprodigy** [comment]
So sorry! I found a mistake in my own config file that was not setting rum application id properly
Which is very confusing in itself, maybe I am not configuring things correctly but after hours spent debugging this issue I would like to understand

DdSdkReactNative.initialize(datadogConfig)
          .then(() => {
            DdLogs.info(
              `Firebase fetch completed with status ${firebaseRemoteConfig.lastFetchStatus} in ${firebaseFetchDuration}ms`,
              {
                firebase_status: firebaseRemoteConfig.lastFetchStatus,
                firebase_duration: firebaseFetchDuration,
              }
            );
          })
          .catch(() => {
            DdLogs.error('DataDog failed to initialize');
          })

I have this logic in my code and even when the Application_ID was incorrectly set, it would execute and say success in logs. Should this not fail out if the ApplicationID is not defined (as was my case)?

**Comment by 0xnm** [comment]
Hello @nimaprodigy! Our SDK embeds support of several DataDog products and `applicationId` is used only for RUM. Other products like Logs and Traces don't need that to work.

If you enabled RUM in SDK configuration and `applicationId` is not set (or empty), you should see an error in your local native logs.

**Comment by nimaprodigy** [comment]
ahh okay thank you for that detail! i will close this ticket
