### ISSUE TITLE
Remove user that was previously set

### ISSUE THREAD

**Issue by jzhan10** [DataDog/dd-sdk-reactnative#146]
**Describe what happened**
Looking to remove a user, similar to `datadogRum.removeUser()` in [@datadog/browser-rum](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm). Couldn't find a way at the moment unless using `setUser` to set to another user.

**Steps to reproduce the issue:**
1. Set user
```typescript
DdSdkReactNative.setUser({
    id,
    email,
    name,
});
```
2. Trying to remove user on logout

**Describe what you expected:**
A `removeUser` API function or way to remove a user. What is the recommended approach?

**Additional context**
    - `"@datadog/mobile-react-native": "^1.0.0-rc4"`

EDIT:
Apologies if this shouldn't be labeled as a bug

**Comment by mariusc83** [comment]
Hi @jzhan10 thank you for taking the time to open the issue. As this is actually an enhancement we will be discussing this proposal internally and we will keep you updated if we decide to add it as a feature in a future release.

**Comment by mariusc83** [comment]
Hi @jzhan10, we discussed your request internally and we considered that it will be too much to add `DdSdkReactNative#removeUser` function as long as you can use `DdSdkReactNative.setUser({})` which in the end will do the same thing. Have you tried this approach on your end ?

**Comment by jzhan10** [comment]
Thanks for the response @mariusc83. Yes ended up doing something like that, all good now.
