### ISSUE TITLE
Runtime error when using console.error with boolean or number values

### ISSUE THREAD

**Issue by 3dos** [DataDog/dd-sdk-reactnative#148]
Describe what happened:
When console.error is called in a react-native view, it causes a runtime error. This error is raised with specific types.

```ts
console.error(undefined) // Ok
console.error(null) // Ok
console.error(true) // Runtime error (right operand of 'in' is not an object)
console.error(1) // Runtime error (right operand of 'in' is not an object)
console.error('string') // Ok
console.error(() => undefined) // Ok
console.error({property1: undefined, property2: null, property3: true, property4: 1, property5: 'string', property6: () => undefined}) // Ok
```

It seems that the 'in' operator is called on primitive values causing the runtime error:
- https://github.com/DataDog/dd-sdk-reactnative/blob/main/packages/core/src/rum/instrumentation/DdRumErrorTracking.tsx#L109
- https://github.com/DataDog/dd-sdk-reactnative/blob/main/packages/core/src/rum/instrumentation/DdRumErrorTracking.tsx#L125

Steps to reproduce:
Calling the console.error function in a react-native view (with the native sdk @datadog/mobile-react-native).

Describe what you expected:
The sdk doesn't crash regardless of the type of data passed in the console.error function.

Additional context:
Version of the SDK - "@datadog/mobile-react-native": "1.0.0-rc4",

**Comment by mariusc83** [comment]
Hi @3dos thank you for taking the time to report the issue. We will investigate this on our end and we will come back with a fix in a future release.
