### ISSUE TITLE
CocoaPods could not find compatible version for pod 'dd-sdk-reactnative' in in podfile: dd-sdk-reactnaitve

### ISSUE THREAD

**Issue by jainmca21** [DataDog/dd-sdk-reactnative#151]
Thanks for taking the time for reporting an issue!

**Describe what happened**
getting error on terminal
[!] CocoaPods could not find compatible versions for pod "dd-sdk-reactnative":
  In Podfile:
    dd-sdk-reactnative (from `../node_modules/dd-sdk-reactnative`)

Specs satisfying the `dd-sdk-reactnative (from `../node_modules/dd-sdk-reactnative`)` dependency were found, but they required a higher minimum deployment target.

**Steps to reproduce the issue:**
 Run command: npm i @datadog/mobile-react-native in terminal
run pod install on ios folder
error will shown on terminal
**Describe what you expected:**
Error should not come
**Additional context**
    - Version of the SDK: 1.0.0-rc4
    - A copy of your `package.json` file
[package.json.zip](https://github.com/DataDog/dd-sdk-reactnative/files/8170406/package.json.zip)

**Comment by 0xnm** [comment]
Hello @jainmca21! Thanks for opening the issue. Can you please tell what is the minimum iOS version your app supports? Our SDK supports iOS versions 11 and above.

**Comment by jainmca21** [comment]
Hi Nikita, Our app support minimum iOS version 10. However I had tried to set the version to 11.0 but now getting error:

[!] CocoaPods could not find compatible versions for pod "DatadogSDKBridge":
  In Podfile:
    DatadogSDKBridge

    DatadogSDKReactNative (from `../node_modules/@datadog/mobile-react-native`) was resolved to 1.0.0-rc4, which depends on
      DatadogSDKBridge (= 0.5.1)

    dd-sdk-reactnative (from `../node_modules/dd-sdk-reactnative`) was resolved to 1.0.0-beta3, which depends on
      DatadogSDKBridge (~> 0.4.4)

**Comment by 0xnm** [comment]
Hello @jainmca21. It seems you still have old [dd-sdk-reactnative](https://www.npmjs.com/package/dd-sdk-reactnative) package which is deprecated in `node_modules` folder, can you remove it and try to install `pod install` again?

**Comment by jainmca21** [comment]
Hi @0xnm, After uninstalling error is gone but when tried to run app on iPad then getting bellow error in xCode:

Undefined symbols for architecture arm64:

  "static Foundation.JSONEncoder.OutputFormatting.withoutEscapingSlashes.getter : Foundation.JSONEncoder.OutputFormatting", referenced from:

      static (extension in Datadog):Foundation.JSONEncoder.default() -> Foundation.JSONEncoder in libDatadogSDK.a(JSONEncoder.o)

  "Network.NWPath.isConstrained.getter : Swift.Bool", referenced from:

      closure #2 () -> Swift.Bool? in closure #1 (Network.NWPath) -> () in Datadog.NWPathNetworkConnectionInfoProvider.init(monitor: Network.NWPathMonitor) -> Datadog.NWPathNetworkConnectionInfoProvider in libDatadogSDK.a(NetworkConnectionInfoProvider.o)

  "(extension in Foundation):__C.NSFileHandle.readToEnd() throws -> Foundation.Data?", referenced from:

      Datadog.File.read() throws -> Foundation.Data in libDatadogSDK.a(File.o)

  "(extension in Foundation):__C.NSFileHandle.seekToEnd() throws -> Swift.UInt64", referenced from:

      Datadog.File.append(data: Foundation.Data) throws -> () in libDatadogSDK.a(File.o)

  "(extension in Foundation):__C.NSFileHandle.write<A where A: Foundation.DataProtocol>(contentsOf: A) throws -> ()", referenced from:

      Datadog.File.append(data: Foundation.Data) throws -> () in libDatadogSDK.a(File.o)

ld: symbol(s) not found for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 0xnm** [comment]
@jainmca21 I guess it is the same issue as described in #41. Can you please try solution from there and let us know if it works for you?

**Comment by 0xnm** [comment]
Hello @jainmca21. I'm closing this ticket due to inactivity, feel free to re-open it if you still experience the issue.
