### ISSUE TITLE
[Question] Can I manipulate the default attributes recorded in DataDog?

### ISSUE THREAD

**Issue by michaelgmcd** [DataDog/dd-sdk-reactnative#155]
I'm trying to implement DataDog RUM Monitoring for my company's React Native app, but I won't be able to use the default configuration for PII reasons. Session IP addresses and latitude/longitude are recorded. Is there a way to remove or mask these values? I've checked out [the docs on standard attributes](https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/#standard-attributes), but didn't see anything.

I thought additionalConfiguration might be able to support this, but it only seems to be used in two places in the iOS SDK:
https://github.com/DataDog/dd-sdk-ios/blob/3ae90a54513dd05fc053ceb7ad84859489cae604/Sources/Datadog/Core/FeaturesConfiguration.swift#L153

**Comment by 0xnm** [comment]
Hello @michaelgmcd! Thanks for opening the issue. This information (IP addresses and location) is not collected by our mobile SDK, but by the backend itself. So to configure that in our data ingestion pipeline please open a ticket [in our support system](https://help.datadoghq.com/hc/en-us). Don't hesitate to re-open this issue if you have more questions.
