### ISSUE TITLE
Attributes GEO  showing incorrect location

### ISSUE THREAD

**Issue by slatqh** [DataDog/dd-sdk-reactnative#160]
Thanks for taking the time for reporting an issue!

**Describe what happened**

GEO showing Tampa Florida, while I'm actually in Miami Florida. 
Is it some specific configuration I have to add to show precise location? 

For some users it showing correct location.

**Comment by 0xnm** [comment]
Hello @slatqh! Our SDK doesn't record location by itself (via GPS or network), geolocation is computed on the backend side based on the IP address of the incoming request from SDK side.

If you want to have more precise location you can attach your custom attributes for the current user which can be set via `DdSdk.setUser` call.

If you have more questions on the geolocation computation done by our backend, please open support ticket [here](https://www.datadoghq.com/support/).

Don't hesitate to re-open this issue if you have more questions.

**Comment by slatqh** [comment]
@0xnm  thanks for clarifying!
