### ISSUE TITLE
User interactions not reported on basic setup

### ISSUE THREAD

**Issue by PDabek-StreamitApp** [DataDog/dd-sdk-reactnative#163]
According to Readme, user interactions should be reported as soon as enabled in DdSdkReactNativeConfiguration.

I am able to setup project, start up a session and send events described in Manual Instrumentation, but automatic User Interaction tracking does not work.

**Steps to reproduce the issue:**
1) Setup basic RN project and install Datadog dependencies. You can verify on this basic setup:  [github](https://github.com/PDabek-StreamitApp/DatadogTest)

**Describe what you expected:**
Automatic Tap events visible in Datadog session (the same way as it works using app from examples)

**Additional context**
package.json: 

```
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.67.4",
    "@datadog/mobile-react-native": "^1.0.0-rc5"
  },
```

Logs from basic app (taps are invoked manually with  **DdRum.addAction('TAP', 'button name', {}, Date.now());** ):
<img width="602" alt="Zrzut ekranu 2022-03-23 o 13 15 31" src="https://user-images.githubusercontent.com/95762866/159697048-559154af-cc95-456b-b154-0f094c52fb59.png">

Logs from example app:
<img width="697" alt="Zrzut ekranu 2022-03-23 o 13 15 55" src="https://user-images.githubusercontent.com/95762866/159697082-4281632e-c324-40b4-b129-9b26a3e1d5d4.png">

**Comment by 0xnm** [comment]
Hello @PDabek-StreamitApp. User actions are linked to the views, so you need to track views as well: you can read more about that [here](https://github.com/DataDog/dd-sdk-reactnative#track-view-navigation).

**Comment by 0xnm** [comment]
Hello @PDabek-StreamitApp. I hope that the question is solved for you, so I'm closing this ticket due to inactivity. Please feel free to re-open it if you still experience any problems.
