### ISSUE TITLE
Support TV 

### ISSUE THREAD

**Issue by NikitaGura** [DataDog/dd-sdk-reactnative#169]
Hi, is it possible integrate SDK for ATV and TVOS? 
I faced with problem for both OS. 

**For TVOS I have issue:** 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/39771918/162948943-81c57b65-20f0-4945-9d9f-7dc62d3daade.png">

**For ATV don't have issue but could not see logs in analytics board. 
Also SDK informed:** 
 INFO  DATADOG: Datadog SDK was initialized
 INFO  DATADOG: Datadog SDK is tracking interactions
 INFO  DATADOG: Datadog SDK is tracking XHR resources
 INFO  DATADOG: Datadog SDK is tracking errors

**Comment by 0xnm** [comment]
Hello @NikitaGura! We didn't look yet into the Android TV/tvOS support for our React Native SDK. Can you please describe your setup to help us better understand the issue:

* What SDK version are you using
* Do you test your app on emulator or on the real device
* What is the React Native version used
* Do you see any errors/warnings in the Logcat/XCode console
* etc.

**Comment by NikitaGura** [comment]
Hello @0xnm, thank you for answer. 
 SDK version 1.0.0-rc5
 Test on emulator 
 React native version: react-native-tvos@0.66.3-1
 Logs: [javascript] TypeError: null is not an object (evaluating 'this.nativeRum.addAction')
 
 Seems like only support ios build target 
 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/39771918/163137665-d29c5d94-6c33-4247-8822-c986ebc4f1ca.png">

**Comment by NikitaGura** [comment]
Also for android TV SDK not register session for analytics.

**Comment by 0xnm** [comment]
@NikitaGura thanks for the info! We will look into TV support for our React Native SDK.

**Comment by gianfranco03** [comment]
Hi @0xnm any update on this?

**Comment by louiszawadzki** [comment]
Hi @NikitaGura @gianfranco03,

We've added support for tvOS in release `1.8.0-rc0`. 

On iOS, you will need to add support for Swift in your build configurations in your `project.pbxproj` file like so: https://github.com/DataDog/dd-sdk-reactnative-examples/commit/be448c15d50334e007867f2847236de5a41c29cc.

You can also do it through XCode by selecting your tvOS target, then adding `SWIFT_VERSION` and `SWIFT_OPTIMIZATION_LEVEL` user-defined build settings: 
![image](https://github.com/DataDog/dd-sdk-reactnative/assets/8973379/1c341f5b-7e90-4725-982e-bf5e98d1d93a)


I'm closing this issue, feel free to open a new one if you encounter any issue :)
