### ISSUE TITLE
Challenges faced after installing the package - @datadog/mobile-react-native

### ISSUE THREAD

**Issue by NigamCharu** [DataDog/dd-sdk-reactnative#170]
Hi,
I have taken a fresh clone of my working repo and installed the package using -
npm install @datadog/mobile-react-native

OS - MacOS Big Sur (11.6.5 )
React Native vserion - 0.64.2
iOS - 11
Android - buildToolsVersion = "29.0.3"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 30
ndkVersion = "20.1.5948944"
kotlinVersion = "1.3.72"

Datadog Configuration is not initialised yet.

Expected behavior - After installation, app should run normally

Actual behavior - After installation, when I am running the app, I am getting errors on both the platforms

iOS - On Network tab in XCode:
dyld`__abort_with_payload:
0x11217de00 <+0>: movl $0x2000209, %eax ; imm = 0x2000209
0x11217de05 <+5>: movq %rcx, %r10
0x11217de08 <+8>: syscall
-> 0x11217de0a <+10>: jae 0x11217de14 ; <+20>
0x11217de0c <+12>: movq %rax, %rdi
0x11217de0f <+15>: jmp 0x11217c010 ; cerror_nocancel
0x11217de14 <+20>: retq
0x11217de15 <+21>: nop
0x11217de16 <+22>: nop
0x11217de17 <+23>: nop

Android -

:datadog_mobile-react-native:compileDebugKotlin
Task :datadog_mobile-react-native:compileDebugKotlin FAILED
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/charu/.gradle/caches/transforms-2/files-2.1/777d641bce5bcf7814de2fbd24ecdf72/jetified-kotlin-stdlib-common-1.5.31.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
e: /Users/charu/.gradle/caches/transforms-2/files-2.1/8ff75b43d44e2ff8f5256dbd41d561a0/jetified-kotlin-stdlib-1.5.31.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
e: /Users/charu/.gradle/caches/transforms-2/files-2.1/caea75bd52edfc1987579922c371635e/jetified-dd-bridge-android-0.5.3-api.jar!/META-INF/dd-bridge-android_release.kotlin_module: Module was compiled with an incompatible version of Kotlin.

Please suggest here.
Thanks.

**Comment by 0xnm** [comment]
Hello @NigamCharu! On Android starting from version `1.0.0-rc5` of our SDK it is necessary to use Kotlin 1.5+ and also comply with `compileSdkVersion = 31` requirement (which is described [here](https://github.com/DataDog/dd-sdk-reactnative#setup)). You can check the example of the app setup in our [sample app](https://github.com/DataDog/dd-sdk-reactnative/tree/develop/example).

Regarding iOS: it is not clear from the error if it is related to our SDK or not. Can you please try to do the clean build? Any other information regarding this issue will be helpful.

**Comment by NigamCharu** [comment]
Hi @0xnm 
Thanks for the quick reply!
Can you please share the sample link of version 1.0.0-rc4 as well? I am planning to go for lower version.

**Comment by 0xnm** [comment]
@NigamCharu You can [check our repo](https://github.com/DataDog/dd-sdk-reactnative/tree/1.0.0-rc4/example) at the `1.0.0-rc4` tag revision.

**Comment by NigamCharu** [comment]
Thanks @0xnm 
Both my builds are working fine now with version 1.0.0-rc4

**Comment by NigamCharu** [comment]
Hi @0xnm 

We are facing an issue in CI/ CD pipeline for ios build.

Issue - fatal error: module map file '/Users/runner/Library/Developer/Xcode/DerivedData/neighbourly-cuxbeddkxwloitbesuaxjrmkwfrc/Build/Products/Release-iphonesimulator/DatadogSDK/Datadog.modulemap' not found

Our configurations on CI/ CD pipeline:
MacOS- 11
XCode - 13.2

The local build is running fine.

Can you please help here?

Thanks.

**Comment by maxep** [comment]
Hi @NigamCharu 

This looks like an issue in your CI configuration for iOS, please check the following:
1. Make sure that the iOS version in your Podfile match the iOS version of your Xcode project.
2. run `pod install` prior to running the build
3. run the build on your `.xcworkspace` (not the `.xcodeproj`)

Hope this helps!

**Comment by 0xnm** [comment]
Hello @NigamCharu! I hope your issue is resolved now, so I am closing this ticket. Don't hesitate to re-open it if you still experience build issues.
