### ISSUE TITLE
Support older versions of Android

### ISSUE THREAD

**Issue by pas256** [DataDog/dd-sdk-reactnative#172]
**Is your feature request related to a problem? Please describe.**

I added the RUM SDK to our React Native app, and tested with iOS. Everything was great. Then I tried to test it on Android and it wouldn't compile. The reason is this SDK requires API version 31, which is the Android ecosystem is super recent. I did some exploring and 25% of our users are on SDK version 30, so we won't be able to use the SDK given the version dependency on 31+. 

Further exploration, if you open the Android Studio and create a new project, today's (April 20, 2022) distribution is this:
<img width="1109" alt="Screen Shot 2022-04-20 at 1 05 52 PM" src="https://user-images.githubusercontent.com/92010/164314433-7a8fda0d-52db-412d-ac16-44a8193bdc8b.png">

This leads me to believe the current 31+ requirement will capture less than a quarter of the Android market.

**Describe the solution you'd like**

For us, supporting Android SDK 30 would be sufficient, but looking at the stats above, others might need even older than that depending on their user base.

**Describe alternatives you've considered**

I considered changing our app to require SDK 31, but that would knock out 25% of our user base.

**Additional context**

The official docs https://developer.android.com/about/dashboards is what led me to use the Create New Project wizard and then click on the "Help me choose" stats.
 
Other resources here: https://gs.statcounter.com/os-version-market-share/android

**Comment by 0xnm** [comment]
Hello @pas256. Requirement for using SDK 31 is regarding `compileSdkVersion`, not `minSdkVersion` (it is mandatory to have `compileSdkVersion = 31` to have `WorkManager` library working on Android 12+ devices).

So you can safely bump `compileSdkVersion` to 31, while keeping `minSdkVersion` the same as you have right now and not loosing the user base.

**Comment by 0xnm** [comment]
Hello @pas256! I believe your question was answered, so I am closing this ticket. Don't hesitate to re-open it if you still have questions regarding the versions used.

**Comment by pas256** [comment]
Yes, thank you!
