### ISSUE TITLE
Cannot track new navigation container while another one is still tracked

### ISSUE THREAD

**Issue by govarthananve** [DataDog/dd-sdk-reactnative#174]
![image](https://user-images.githubusercontent.com/17062177/166638686-8f0dc017-d4ed-4c8a-bde9-71362c177ff8.png)

**Steps to reproduce the issue:**
After integrated dataDog SDK, I am getting this Crash in "Crash free sessions by version" in UX Monitoring => [RUM Applications] and Application dashboard. But App is not crashing 
**Describe what you expected:**
Without this error 
**Additional context**
    "@datadog/mobile-react-native": "^1.0.0-rc5",
    "@datadog/mobile-react-navigation": "^1.0.0-rc5"

**Comment by 0xnm** [comment]
Hello @govarthananve! This error doesn't lead to the crash. Can you please share the code showing how our `@datadog/mobile-react-navigation` package is integrated? Do you have calls to `DdRumReactNavigationTracking.startTrackingViews` for different navigation containers?

**Comment by govarthananve** [comment]
only one using this in App.js file

import {DdRumReactNavigationTracking} from '@datadog/mobile-react-navigation';

<NavigationContainer
      ref={navigationRef}
      onReady={() => {
        DdRumReactNavigationTracking.startTrackingViews(navigationRef.current);
        }}
      >
      ...
</NavigationContainer>

**Comment by louiszawadzki** [comment]
Hi @govarthananve!

We figured this error was triggered when Android users closed their app using the phone's hardware back button. We released a fix in version 1.0.0-rc7, so you should not see this error pop up anymore if you update.

I'm closing the issue for now, feel free to reopen it if you still encounter the issue with version 1.0.0-rc7 :)

**Comment by blwinters** [comment]
I also get this when I set `ddConfig.verbosity = SdkVerbosity.WARN` and refresh the app during development. I removed that and the local error went away (i.e. was hidden), though it would be nice to have the logs on without getting this bogus one. (My NavigationContainer props are the same as above.)

**Comment by louiszawadzki** [comment]
Hi @blwinters, 
Thanks for reporting it! We'll look into it and see if we can remove this warning in development mode while keeping the warning in relevant times.

I'll keep you updated once we make progress on this.
