### ISSUE TITLE
Dashboard : P75 Loading Time is always N/A for all screen views

### ISSUE THREAD

**Issue by NigamCharu** [DataDog/dd-sdk-reactnative#200]
Hi,

I am experiencing issue in Datadog dashboard after implementing SDK [dd-sdk-reactnative]. The P75 Loading time is always N/A for all screen views. We have used startView and stopView combination for each view as well.

The configs are :
trackUserInteractions= true;
trackXHR= true;
trackError= true;
nativeCrashReportEnabled= true;
site= 'US';
sampleRate= 80;

Please help here.

Thanks!

**Comment by 0xnm** [comment]
Hello @NigamCharu! We currently don't support screen loading time in our React Native SDK, but this is something that we are going to add in the future.

**Comment by NigamCharu** [comment]
Thanks!
