### ISSUE TITLE
Nothing is being reported

### ISSUE THREAD

**Issue by vhurryharry** [DataDog/dd-sdk-reactnative#220]
I'm working on a react-native project where I need to integrate the datadog monitoring.
Followed the steps mentioned in the [guide](https://docs.datadoghq.com/real_user_monitoring/reactnative/) and set onReady callback for NavigationContainer.

Configuration:
```
const config = new DdSdkReactNativeConfiguration(
  '...',
  env,
  '...',
  true, // track User interactions (e.g.: Tap on buttons. You can use 'accessibilityLabel' element property to give tap action the name, otherwise element type will be reported)
  true, // track XHR Resources
  true, // track Errors
);

// Optional: Select your Datadog website (one of "US", "EU" or "GOV")
config.site = 'US';
// Optional: enable or disable native crash reports
config.nativeCrashReportEnabled = true;
// Optional: sample RUM sessions (here, 80% of session will be sent to Datadog. Default = 100%)
config.sampleRate = 80;

await DdSdkReactNative.initialize(config);
```

Package.json
```
...
"@datadog/mobile-react-native": "^1.0.0-rc5",
"@datadog/mobile-react-navigation": "^1.0.0-rc5",
"@react-navigation/drawer": "^6.4.1",
"@react-navigation/native": "^6.0.10",
"@react-navigation/stack": "^6.2.1",
"react": "18.1.0",
"react-native": "0.68.2",
...
```

Navigator
```
...
<NavigationContainer
  ref={navigationRef}
  onReady={() => {
    DdRumReactNavigationTracking.startTrackingViews(
      navigationRef.current,
    );
  }}>
...
```

The installation runs fine and there's no error. But if I run the app, nothing happens on the datadog side. No report, no log, no error.

I've tried manual logging with `DdLogs.info('Lorem ipsum dolor sit amet…', {});`, but it also didn't work.

**Comment by louiszawadzki** [comment]
Hi @vhurryharry,

Thanks for reporting this issue!
Here are a few steps to help us understand a bit more what is going on:

- Set `config.sampleRate` to `100` to make sure all your sessions are tracked
- Set `config.verbosity = SdkVerbosity.DEBUG` (where `SdkVerbosity` is an import from `@datadog/mobile-react-native`) to make internal logs appear in the packager

Could you also share where you are calling your configuration code?
i.e. is it written in the main App component? is it in a separate file that you import in your `index.js`?

Thanks a lot :)

**Comment by vhurryharry** [comment]
Thanks, @louiszawadzki for your quick reply!
I've updated the config and tried again, but still no logs.

And it was written in a separate file and being imported into my 'navigator.js` file where the `NavigationContainer` is being rendered. I've confirmed that the init function is being called properly tho.

**Comment by vhurryharry** [comment]
I've moved the initialization stuff before `AppRegistry.registerComponent` and it works fine now. Thanks!

**Comment by louiszawadzki** [comment]
Great news!
Thanks for your input, I'll add a task in our backlog to improve this setup documentation and make this more explicit :)

**Comment by realjoebrown-verkada** [comment]
@louiszawadzki thoughts on throwing an error, or logging a warning on each subsequent call? Our JS logs look like this:
```
 LOG  analytics: initializeDataDog
 LOG  analytics: initializeDataDog complete
```

while our native logs look like this

```
2022-08-31 15:16:45.348786-0700 MyApp[18499:1207383] [javascript] analytics: initializeDataDog
🔥 Datadog SDK usage error: `Datadog.initialize()` must be called prior to `Logger.builder.build()`.
2022-08-31 15:16:45.381697-0700 MyApp[18499:1207383] [javascript] analytics: initializeDataDog complete
```

technically xcode allows filtering logs based on emoji, however that is not a development flow i regularly use 😄 

our calling code looks like:

```js
try {
    await DdSdkReactNative.initialize(config);
  } catch (error) {
    console.error('Error initializing DdSdkReactNative / DdRum', error);
    trackError(error as Error, { from: 'initializeDataDog' }); // different analytics provider
    return;
  }
```
