### ISSUE TITLE
Cannot "disable" Datadog native modules

### ISSUE THREAD

**Issue by holyris** [DataDog/dd-sdk-reactnative#223]
Hello, i'm using expo SDK 44 so I followed this documentation https://docs.datadoghq.com/fr/real_user_monitoring/reactnative/expo/ to disable datadog in dev mode.

The error i get: 
Exception in HostObject::set for prop 'DdSdk'

Any clue ?

**Comment by louiszawadzki** [comment]
Hi @holyris,

Thank you for reporting this! It looks like this "hack" has not been tested enough, sorry for that.

Here's a version of the `mockDatadog.ts` file that I've tested more thoroughly, tell me if it works for you. If so I'll update our documentation shortly.

```typescript
// mockDatadog.ts
import {
  DdLogs,
  DdTrace,
  DdRum,
  DdSdkReactNative,
} from "@datadog/mobile-react-native";

if (__DEV__) {
  const emptyAsyncFunction = () => new Promise<void>((resolve) => resolve());

  DdLogs.debug = emptyAsyncFunction;
  DdLogs.info = emptyAsyncFunction;
  DdLogs.warn = emptyAsyncFunction;
  DdLogs.error = emptyAsyncFunction;

  DdTrace.startSpan = () =>
    new Promise<string>((resolve) => resolve("fakeSpanId"));
  DdTrace.finishSpan = emptyAsyncFunction;
  DdRum.startView = emptyAsyncFunction;
  DdRum.stopView = emptyAsyncFunction;
  DdRum.startAction = emptyAsyncFunction;
  DdRum.stopAction = emptyAsyncFunction;
  DdRum.addAction = emptyAsyncFunction;
  DdRum.startResource = emptyAsyncFunction;
  DdRum.stopResource = emptyAsyncFunction;
  DdRum.addError = emptyAsyncFunction;
  DdRum.addTiming = emptyAsyncFunction;

  DdSdkReactNative.initialize = emptyAsyncFunction;
  DdSdkReactNative.setUser = emptyAsyncFunction;
  DdSdkReactNative.setAttributes = emptyAsyncFunction;
  DdSdkReactNative.setTrackingConsent = emptyAsyncFunction;
}
```

We also recommend switching to Expo development builds as they enable you to:
- check your integration with Datadog before shipping your app
- make update to Datadog's SDK more easily by testing it locally
- have insights on your debug application as well 

If you decide to go this way instead, tell me if you encounter any issue :) 

Sorry again for the inconvenience.
