### ISSUE TITLE
Configuring @datadog/mobile-react-native alongside native DataDog libraries

### ISSUE THREAD

**Issue by akinzalowevidation** [DataDog/dd-sdk-reactnative#227]
**Is your feature request related to a problem? Please describe.**
The `@datadog/mobile-react-native` package does not specify an option to configure DataDog in native code instead of in the react-native portion or detail if react-native & native iOS/Android DataDog support can coexists.

**Additional context**
We are in the process of adding `dd-sdk-reactnative` to our React Native project. We already have the `DatadogSDK` iOS SDK installed and configured for logging some iOS native code we have for our React-Native project. Is setting up DataDog for react-native + native iOS/Android supported? If we find that it _does_ work, should we rely on it? There is not documentation (that I know of) that has DataDog implemented in RN & native code.

**Describe the solution you'd like**
A documented option for configuring DataDog natively in iOS and Android instead of within react-native for `@datadog/mobile-react-native`.

**Describe alternatives you've considered**
I have considered continuing to configure `DatadogSDK` in native iOS, configure it in Android, and then not configure it in react-native code. I believe this would work as-is since `dd-sdk-reactnative` uses the `DataDog` iOS package. However, it would be nice to see documentation in react-native setup that specifies this is an option if you need both react-native and native iOS/Android DataDog support.

**Comment by louiszawadzki** [comment]
Hi @akinzalowevidation, thank you for reaching out!

As of now, it should be possible to use Datadog both in the React Native and native sides :) 
It's not officially documented as it's not a highly requested feature, but if this issue gets a lot of attention we'll look into it. In the meantime, here are some indications on how to achieve it.

## Constraints

Before getting started, I need to mention a few constraints to keep in mind. 
1. We currently cannot initialize more than 1 instance of  the native `DatadogSDK`, we use a singleton pattern. That means that as we can initialize the native SDK in the native side or on the RN side (by calling `DdSdkReactNative.initialize`) and then it will be configured for both.
2. If we try to call any Datadog method before the initialization, we might end up with things not working.
3. For **errors, resources and interactions tracking**,  SDKs can work in 2 ways: through auto-instrumentation (we modify some framework classes and methods to automate this) or through manual instrumentation - for instance if you want to report something you consider an error but that is not going to crash the app. Auto-instrumentation for JS errors, resources and interactions can only be started from javascript code.
 
## Solutions

We have 3 solutions, depending on your needs

### Recommended: initialize the SDK on the React Native side only

The idea is to initialize the RN SDK, by calling `DdSdkReactNative.initialize` at the start of your RN application. This will also initialize the native SDK.

If you are sure that you don't call the native SDK before the RN SDK (e.g. if you only use logging in some native code that is not called during the initialization), you're fine with this solution.

#### Potential issues
**You cannot call the native SDK before the RN SDK has been initialized.** You can mitigate it by creating a queue on the native side to check if the SDK has been initialized before calling it, but events' timestamps might be wrong then. 


### Initialize the SDK on the native side

If you have to call the native SDK before the RN SDK and don't need the auto instrumentation for JS errors, resources or interactions, (i.e. passing `false` as 4th, 5th and 6th arguments to `DdSdkReactNative.initialize`) you can initialized the SDK in the native code.

#### Potential issues
**You won't have auto instrumentation for JS errors, resources or interactions.** You can mitigate this triggering this auto instrumentation yourself. All you have to do is to do [what the `enableFeatures` function does](https://github.com/DataDog/dd-sdk-reactnative/blob/develop/packages/core/src/DdSdkReactNative.tsx#L184). Note that you will have to use imports to the path to the file (e.g. `import {DdRumErrorTracking} from '@datadog/mobile-react-native/src/rum/instrumentation/DdRumErrorTracking';`) and that the path to these files might change across SDK versions.

### Initialize the SDK on both sides

You can still initialize the SDK on both sides, but this can lead to unexpected results, so be sure to test it well. With this solution you will have to maintain 2 configurations. This can cause issues if the first SDK to initialize is not consistently the same and your configurations are not the same.


I hope this makes sense to you and that can help you make the SDK work on both native and JS sides. 
I'd also be interested to know what you're use case is and which solution you think fits you best :) 

Feel free to reply if you have any question, or close the issue if this resolved it.

**Comment by akinzalowevidation** [comment]
@louiszawadzki Thank you for the detailed and very useful response!

I ended up going with option 2. Everything seems to work well except for two things:
- I am not seeing any logs appear for my service when logging from react-native after initializing in iOS native.
- I do not see errors under the Error Tracking feature of UX Monitoring, but I _do_ see them under the dashboards for the RUM Application. I can see the errors there and click on them to go to the Error Tracking feature, and when I get there it is empty for that application.

Regarding logging, this is how I am using it:
```
Datadog.initialize(
      appContext: .init(),
      trackingConsent: .granted,
      configuration: Datadog.Configuration
        .builderUsing(
            rumApplicationID: rumApplicationID,
            clientToken: clientToken,
            environment: environment
        )
        .set(serviceName: "...")
        .set(tracingSamplingRate: 100.0)
        .set(rumSessionsSamplingRate: 100.0)
        .set(endpoint: .us1)
        .trackUIKitRUMActions()
        .trackURLSession(firstPartyHosts: Set(["..."]))
        .enableCrashReporting(using: DDCrashReportingPlugin())
        .build()

Datadog.verbosityLevel = .debug
Global.rum = RUMMonitor.initialize()
```

```
import { DdLogs } from "@datadog/mobile-react-native";

...

DdLogs.info(...);
```

I notice the `dd-bridge-ios` sets up its own [logger](https://github.com/DataDog/dd-bridge-ios/blob/main/DatadogSDKBridge/Classes/Implementation/DdLogsImplementation.swift). By initializing in native, is this step being skipped?

Everything else appears to be working correctly :+1:

**Comment by akinzalowevidation** [comment]
Regarding the error feature, I [discovered](https://github.com/DataDog/dd-sdk-reactnative/issues/81#issuecomment-1146074106) that RUM javascript errors do not appear there. No worries though as I can just see them under the RUM application dashboard.

The tracing is working well after that addition :+1:. I am still not seeing logs though.
It says that they are uploading:
```
[DATADOG SDK] 🐶 → 15:01:18.530 [DEBUG] ⏳ (logging) Uploading batch...
[DATADOG SDK] 🐶 → 15:01:18.914 [DEBUG]    → (logging) accepted, won't be retransmitted: [response code: 202 (accepted), request ID:XXX]
```
But I do not see any logs for our `serviceName`. I did `.set(serviceName: "...")` on both `Logger.builder` and `Datadog.initialize`.
I also have set `Datadog.verbosityLevel = .debug`.

Are there any other requirements for logs to be sent from the RN package or iOS SDK?

**Comment by louiszawadzki** [comment]
Hi @akinzalowevidation, I've not managed to recreate the issue on my side, even when setting the service name.

Could you try to share a small repo on which you can reproduce the issue to help us troubleshooting?

**Comment by akinzalowevidation** [comment]
> Hi @akinzalowevidation, unfortunately I've not managed to recreate the issue on my side, even when setting the service name 😞
> 
> Could you try to share a small repo on which you can reproduce the issue to help us troubleshooting?

After much investigation I found out that the missing logs were a permission issue in my organization. The team that manages our DataDog services fixed and and I see all of them now :+1: Thank you for the assistance!
