### ISSUE TITLE
How to set the application version of the app

### ISSUE THREAD

**Issue by vitorcremonez** [DataDog/dd-sdk-reactnative#246]
Maybe include that information under config.version

**Comment by louiszawadzki** [comment]
Hi @vitorcremonez ,

For now the application version is automatically set to be the version of your app, specified in:
- `versionName` in `build.gradle` for Android
- "Version" field in Xcode for iOS

To help us improve the SDK, could you share what your use case is?

**Comment by louiszawadzki** [comment]
Hi @vitorcremonez 

You can now specify a version in the configuration:

By default, the SDK will report the version as the commercial version of your app (for example, "1.2.44").

If you use an Over The Air (OTA) updates provider like Microsoft's Codepush, you can override this version to indicate which version of your JavaScript code is running.

The recommended way is to do so by specifying a versionSuffix to the DdSdkReactNativeConfiguration object:

```js
const config = new DdSdkReactNativeConfiguration(
    '<CLIENT_TOKEN>',
    '<ENVIRONMENT_NAME>',
    '<RUM_APPLICATION_ID>',
    true,
    true,
    true
);

config.versionSuffix = 'codepush.3';
```

If the commercial version of your app is "1.2.44", it will then be reported as "1.2.44-codepush.3" in Datadog - a dash (`-`) is automatically added between the version and the suffix.

You can also completely override the version by specifying the version field. However, make sure you set it correctly, as it will have to match the one specified during the upload of your source maps and other mapping files.

For more information about limitations on the version field, see the [Tags documentation](https://docs.datadoghq.com/getting_started/tagging/#define-tags).


I am closing this issue, feel free to reopen it for further questions.
