### ISSUE TITLE
DdRum.addError() does not do anything with 2nd argument (source)

### ISSUE THREAD

**Issue by dcenatiempo** [DataDog/dd-sdk-reactnative#247]
No matter what is put in for the second argument, the source in datadog is always set to "custom"

```
const e = new Error('some new error');
DdRum.addError(e.message, 'logger', e.stack, {}, Date.now());
```
I've tried a variety of random strings, including the "reserved" strings:  `source`, `logger`, `network`

I would expect one of 2 possible behaviors:
a) the error source in Datadog is set to whatever the 2nd arg is
b) the error source in Datadog is set to whatever the 2nd arg is IF it is one of the predefined sources (`source`, `logger`, `network`, etc) ELSE the source is set to `custom`

**Comment by louiszawadzki** [comment]
Hi @dcenatiempo, thanks for reaching out!

I agree that the `source` attribute usage is not very clear, I've planned to include a more details in our docs on this. Let me clarify how it is supposed to behave

In the "Sessions and Replays" page in Real User Monitoring (see screenshot below, I put the same value for error source and error name), you should see that:
- `source` (i.e. source code error), `network`, `console` and `webview` are reported as such for the source attribute
- `agent` (i.e. SDK error) and `logger` are reported as such for Android, and `custom` for iOS (we're planning to change this to have identical behavior on both OS)
- any other value is reported as `custom` for both OS
<img width="294" alt="image" src="https://user-images.githubusercontent.com/8973379/186892853-337adb4e-a3e4-4d1c-99d9-220027af9013.png">


In the Error Tracking page, you will only see errors that have a source of `source` or `custom`.

To help us troubleshoot your case, could you specify the following:
- which values you tried on which OS
- the version of `react-native` you are using
- the version of `@datadog/mobile-react-native` you are using

Thanks a lot!
