### ISSUE TITLE
Some sessions are not recorded, actions not being recorded at all

### ISSUE THREAD

**Issue by andrestone** [DataDog/dd-sdk-reactnative#249]
**Describe what happened**
Only 50% of the sessions are being recorded and displayed at the RUM dashboard.

**Steps to reproduce the issue:**
Follow the README / getting started guides.

**Describe what you expected:**
All sessions and actions should be recorded.

**Additional context**
1.0.0-rc9

**Comment by louiszawadzki** [comment]
Hi @andrestone, thanks for reaching out!

Could you share the following information to help us troubleshoot:
- the SDK configuration you used
- react-native version
- does the problem happen both on iOS and Android

Thanks a lot!

**Comment by andrestone** [comment]
Sure.
```typescript
  const config = new DdSdkReactNativeConfiguration(
    // 'redacted',
    // 'redacted',
    // 'redacted',
    true, // track User interactions (e.g.: Tap on buttons. You can use 'accessibilityLabel' element property to give tap action the name, otherwise element type will be reported)
    true, // track XHR Resources
    true // track Errors
  );
  // Optional: Select your Datadog website (one of "US", "EU" or "GOV")
  config.site = 'EU1';
  // Optional: enable or disable native crash reports
  config.nativeCrashReportEnabled = true;
```
react-native 0.69.4

Can only test on iOS.

**Comment by louiszawadzki** [comment]
Hi @andrestone, thanks for your quick reply!

By default only 80% of the sessions are recorded. If you want 100% you can specify it by adding `config. sessionSamplingRate = 100`.
You can look at [our documentation](https://docs.datadoghq.com/real_user_monitoring/reactnative/#initialize-the-library-with-application-context) for more options.

Tell me if this fixes your case :)
As always we're happy to improve our documentation, please tell us if it is missing or unclear somewhere :)

**Comment by andrestone** [comment]
Hey @louiszawadzki,

If that's the case, the documentation is wrong, as it says that the default is 100%.

```typescript
// ...
// Optional: sample RUM sessions (here, 80% of session will be sent to Datadog. Default = 100%)
config.sessionSamplingRate = 80;
// ...
```

Besides, none of the actions are being recorded.

Here's how I'm adding actions:

```typescript
DdRum.addAction('ready', 'playback', {}, Date.now());
```

**Comment by louiszawadzki** [comment]
Hi @andrestone , 

Sorry you're totally right, thanks for correcting me, it looks like I needed more coffee this morning 😅
Everything looks fine on your configuration :) 

Are you making sure to initialize the SDK (waiting for `DdSdkReactNative.initialize` to resolve) before making any `DdRum` call?
As of today, sending any event or log before initializing the SDK disables parts of it, so it could be the reason behind it.

Could you share the following to help us troubleshoot:
- XCode logs when starting the app from XCode
- The code where you initialize the SDK

You can also reach out to Datadog's support mentioning this issue to share logs and code more easily :)

**Comment by louiszawadzki** [comment]
Hi @andrestone, 

I'm closing this issue as it's been stale for over a month.

If you didn't manage to solve your issue, don't hesitate to reopen it or reach out again through [our support team](https://www.datadoghq.com/support/), it makes it easier to share logs and code if there is data you want to keep private :) 

Thanks a lot!
