### ISSUE TITLE
[1.1.0] - Missing ErrorSource export form index.d.ts

### ISSUE THREAD

**Issue by sync** [DataDog/dd-sdk-reactnative#266]
**Describe what happened**
When using version 1.1.0 with typescript, it's impossible to use the new enum `ErrorSource` from the main export.

```
import { DdRum, ErrorSource } from '@datadog/mobile-react-native';
```
<img width="555" alt="Screen Shot 2022-09-12 at 3 53 59 pm" src="https://user-images.githubusercontent.com/21725/189582816-ff06dfe4-76c0-43ed-9330-008365c8bb8f.png">

This is required for example when wanting to use:

```
      DdRum.addError(
        message,
        ErrorSource.NETWORK,
```

**Steps to reproduce the issue:**
Install latest version (1.1.0) and have it configured in a react-native typescript project.

try to use `DdRum.addError(...`

**Describe what you expected:**
Being able to import `ErrorSource` from the main export.

**Additional context**
    - version 1.1.0
    - It looks like ErrorSource needs to be exported, looking at index.d.ts, it is not there

**Comment by louiszawadzki** [comment]
Hi @sync, 

Thank you for reporting this. Sorry about that, it will be fixed very soon in a patch release.
