### ISSUE TITLE
"TypeError: Cannot read property 'initialize' of null" trying to initialize sdk

### ISSUE THREAD

**Issue by mfelix5** [DataDog/dd-sdk-reactnative#280]
Hello, I must be missing something here. After installing the package (v. 1.1.1) via yarn in my app (react-native v .70) I am unable to successfully initialize the sdk. 

```
import {
  DdSdkReactNative,
  DdSdkReactNativeConfiguration,
  SdkVerbosity,
} from "@datadog/mobile-react-native";

export async function initializeDatadog() {
    const config = new DdSdkReactNativeConfiguration(
      "pub123",
      Config.STAGE,
      "asfdasfd",
      true,
      true,
      true
    );
    config.site = "US1";
    config.nativeCrashReportEnabled = true;
    config.sessionSamplingRate = 80;
    config.resourceTracingSamplingRate = 80;
    config.verbosity = SdkVerbosity.WARN;

    try {
      await DdSdkReactNative.initialize(config);
    } catch (err) {
      console.error("DD initialization error:", err);
    }
  }

```

No matter where I try to run this (in index.js or in a useEffect hook in App.tsx), the sdk is not initialized. What I see in the logs is: `DD initialization error: [TypeError: Cannot read property 'initialize' of null]`.

Any help is appreciated!

**Comment by louiszawadzki** [comment]
Hi @mfelix5, thanks for reaching out!

Could you detail if the error happen on iOS, Android or both?
Also have you run `npx pod-install ios` before building your iOS app?

Thanks :)

**Comment by mfelix5** [comment]
Yes, that was the issue on iOS. Thank you. It might be helpful to add `pod install` to the docs!

**Comment by morgan-doctolib** [comment]
Hello @louiszawadzki.
I am actually having the same issue on both iOS & Android, and installing the pods and cleaning gradle does not do the trick 😕

The problem happens when I try to initialize the SDK.

`DdSdkReactNative.initialize(config)
      .then(() => {
        console.log('################## DdSdkReactNative::INITIALIZED')
      })
      .catch((error) => {
        console.log('################## DdSdkReactNative::ERROR:', error)
      })`


`################## DdSdkReactNative::ERROR: [TypeError: Cannot read property 'initialize' of null]`

Any idea?
Thank you.

**Comment by louiszawadzki** [comment]
Hi @morgan-doctolib, thanks for reaching out!

Have you tried rebuilding your app after the `pod install`?
Could you share your `Podfile.lock` to help us troubleshoot?

On Android, it can be linked to this issue: https://github.com/DataDog/dd-sdk-reactnative/issues/137
Currently the best solution seems to turn on the Debug mode for your app (which should open a Google Chrome tab).

Could you tell me if that works for you?

**Comment by morgan-doctolib** [comment]
> Hi @morgan-doctolib, thanks for reaching out!
> 
> Have you tried rebuilding your app after the `pod install`? Could you share your `Podfile.lock` to help us troubleshoot?
> 
> On Android, it can be linked to this issue: #137 Currently the best solution seems to turn on the Debug mode for your app (which should open a Google Chrome tab).
> 
> Could you tell me if that works for you?

Thank you very much for your quick reply, @louiszawadzki!
Yes, I have rebuilt the app after the `pod install`.
Here's our Podfile:
```
require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', deterministic_uuids: false

target 'MyTarget' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: true,
    fabric_enabled: flags[:fabric_enabled],
    # An absolute path to your application root.
    app_path: "#{Pod::Config.instance.installation_root}/..",
  )

  pod 'Permission-BluetoothPeripheral', path: '../../node_modules/react-native-permissions/ios/BluetoothPeripheral'
  pod 'Permission-Calendars', path: '../../node_modules/react-native-permissions/ios/Calendars'
  pod 'Permission-Camera', path: '../../node_modules/react-native-permissions/ios/Camera'
  pod 'Permission-LocationAlways', path: '../../node_modules/react-native-permissions/ios/LocationAlways'
  pod 'Permission-LocationWhenInUse', path: '../../node_modules/react-native-permissions/ios/LocationWhenInUse'
  pod 'Permission-Microphone', path: '../../node_modules/react-native-permissions/ios/Microphone'
  pod 'Permission-SpeechRecognition', path: '../../node_modules/react-native-permissions/ios/SpeechRecognition'

  pod 'RNSentry', path: '../../node_modules/@sentry/react-native'

  target 'MyTargetTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  use_flipper!({ 'Flipper-DoubleConversion' => '1.1.7' })
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

I'm going to play a little with [the example project](https://github.com/DataDog/dd-sdk-reactnative/tree/main/example), to see if I'm missing something, unless you see anything obvious in the meantime 🙂

**Comment by louiszawadzki** [comment]
It looks like you need to manually link your dependencies.

Tell us if running `yarn react-native link @datadog/mobile-react-native` (or manually adding the pod in the `Podfile` and `settings.gradle`) before `pod install` again fixes the issue.

**Comment by morgan-doctolib** [comment]
Thank you @louiszawadzki, it is working after manually linking my dependencies!

If anyone encounters the same problem, here's what I did.

## iOS
`Podfile`:
` pod 'DatadogSDKReactNative', path: '../../node_modules/@datadog/mobile-react-native'`

## Android
`settings.gradle`:
```
include ':@datadog'
project(':@datadog').projectDir = new File(rootProject.projectDir, '../../node_modules/@datadog/mobile-react-native/android')
```

`app/build.gradle`:
`implementation project(':@datadog')`

`MainApplication.java`:
Add a `new DdSdkReactNativePackage()` in the packages list returned by `getPackages()`.

Have a great week-end 🙂
