### ISSUE TITLE
Is there any configuration needed to work with Exception and Error Boundary Handlers?

### ISSUE THREAD

**Issue by andyasberry** [DataDog/dd-sdk-reactnative#284]
First of all, thank you for this SDK and also for investing the time to make it work with Expo!

This is more of a question (I assume I'm doing something wrong). We have added the following packages to our app to provide graceful exception/crash handling for our users:

* [react-native-exception-handler](https://github.com/a7ul/react-native-exception-handler)
* [react-native-error-boundary](https://github.com/carloscuesta/react-native-error-boundary)
* [react-native-restart](https://github.com/avishayil/react-native-restart)

Both are working as expected, with the exception (pun intended 😄) that we aren't seeing any crash logs in Datadog (RUM or otherwise), unless it is a Native Exception (which we have not set up a handler for yet). We have configured both to use DdLogs to send an error in their respective exception handlers, but it seems not to be working.

A total guess that I have is that when the exception happens and the user restarts the app, the storage for the logs is getting wiped before the batch is sent to Datadog.

Do you have any thoughts or suggestions? Should I look at `DdRum.addError`? Happy to provide any additional details that would be helpful.

**Comment by louiszawadzki** [comment]
Hi @andyasberry, thanks for reaching out!

If you use `DdLogs` to send the errors, they should appear in the Logs menu entry: 
<img width="162" alt="image" src="https://user-images.githubusercontent.com/8973379/192223891-707e87c1-d37f-42c1-b409-c74138f1eb05.png">
Do you see the error logs in here?

However, if you want the error to be linked to its session, its view and show up in "UX Monitoring" > "Error Tracking" you need to use `DdRum.addError`.
<img width="369" alt="image" src="https://user-images.githubusercontent.com/8973379/192225372-5b75aaf9-b068-44dd-8e22-890497d277b9.png">
You should also specify `"SOURCE"` (or `ErrorSource.SOURCE` from version 1.1.1) as the source for the error, meaning it comes from the source code of your app.

Tell me if that works for you.


Also if you try to use the automated error reporting like below, it is possible that one of the libraries you added might interfer with it and prevent it from getting the errors:
```
const config = new DdSdkReactNativeConfiguration(
    '<CLIENT_TOKEN>',
    '<ENVIRONMENT_NAME>',
    '<RUM_APPLICATION_ID>',
    true, 
    true,
    true // track Errors
);
```

**Comment by andyasberry** [comment]
We had added MS AppCenter Analytics at the early stages of our project, and later our organization adopted Datadog as our official monitoring and logging solution. After we removed the AppCenter dependency, we've seen a great improvement in the crash logs coming through. 

We're thinking there may have been some sort of conflict with Datadog and AppCenter analytics, but not 100% sure 🤷‍♂️
