### ISSUE TITLE
Is there a way to log Unhandled Promise Rejections?

### ISSUE THREAD

**Issue by PawelLampliapps** [DataDog/dd-sdk-reactnative#298]
I want to log Unhandled Promise Rejections which are logged to the console in dev mode like this:
![image](https://user-images.githubusercontent.com/73839878/194028185-2a234fbf-5190-4972-85f6-e50e22b1301b.png)

I thought setting `config.verbosity` to `SdkVerbosity.WARN` allows this, but it is not. 
Is it even possible or have done something wrong during initialization DataDog instance?

https://github.com/PawelLampliapps/DataDogAsyncExceptionTestApp - example app I was testing on.

**Comment by louiszawadzki** [comment]
Hi @PawelLampliapps, thanks for reaching out!

I'd like to make sure I understand your request correctly, do you mean that you would like to see the Unhandled Promise Rejections reported in Datadog, for instance in Error Tracking or RUM Errors?

If that is the case, it is something that is not currently supported by the React Native SDK, and I'll add it in our backlog. 
In the meantime, you can also support it in your app by calling `DdRum.addError` whenever there's an unhandled promise rejection.

**Comment by PawelLampliapps** [comment]
Thank you for your answer @louiszawadzki! Yep, I meant such reporting feature. I will close the issue.
