### ISSUE TITLE
iOS build failure in 1.1.3?

### ISSUE THREAD

**Issue by sushilr** [DataDog/dd-sdk-reactnative#299]
Thanks for taking the time for reporting an issue!

**Describe what happened**
I'm seeing a bunch of undefined symbols when I try to build on iOS. I saw this with 1.1.2 and 1.1.3. Am I doing anything wrong? 
![image (6)](https://user-images.githubusercontent.com/1179259/194177873-f57caaae-5411-46ce-b008-c51d25278c48.png)

**Steps to reproduce the issue:**
Integrate the SDK, install pods and attempt to build. 

**Describe what you expected:**
The build to succeed

**Additional context**
- 1.1.2 and 1.1.3
- React native 0.67.4, building on iPhone 14

**Comment by sushilr** [comment]
Hey @louiszawadzki thanks for getting back to me! Here are the Datadog deps in Podfile.lock

```
...
  - DatadogSDK (1.12.0)
  - DatadogSDKCrashReporting (1.12.0):
    - DatadogSDK (= 1.12.0)
    - PLCrashReporter (~> 1.10.1)
  - DatadogSDKReactNative (1.1.3):
    - DatadogSDK (~> 1.12.0)
    - DatadogSDKCrashReporting (~> 1.12.0)
    - React-Core
....

- PLCrashReporter (1.10.2)
...
```

Anything specific you are looking for in the Podfile? Thank you!

**Comment by sushilr** [comment]
Also, does the library support simulator? Was curious if this was an architecture (x86_64) problem

**Comment by louiszawadzki** [comment]
Hi @sushilr, this could be an issue with the configuration of your pods project.
If there are some dependencies you don't want to share feel free to redact them, but the more content you share the more useful it is for us to help you.

Could you also specify which version of XCode you are using?

The library does indeed support simulator.

Thank you.

**Comment by sushilr** [comment]
Hey @louiszawadzki, I fixed it, thanks! We use use_frameworks and the issue was in my Podfile. I had to add it as a static lib. All good now.

**Comment by lukeharvey** [comment]
@sushilr I'm facing the same issue you were facing last week, we are also using `use_frameworks` in our Podfile and encountering the missing symbols issue you mention above. Could you specify here the change you made to your Podfile? Which library did you have to make static? Thanks

**Comment by lukeharvey** [comment]
Actually don't worry, I think I've got it working now, the bit I wasn't sure about was which Pod to make static but turns out to be `DatadogSDKReactNative`, so this is basically what I have now

```
static_libraries = ['DatadogSDKReactNative', ...]
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if static_libraries.include?(pod.name)
        puts "Overriding static framework for #{pod.name}"
        def pod.static_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
```
