### ISSUE TITLE
EAS Build fails with Expo SDK 46

### ISSUE THREAD

**Issue by erisvaldojunior** [DataDog/dd-sdk-reactnative#304]
**Describe what happened**

After installing it, following the Expo instructions and running eas build, I get:

✖ Config sync failed
SyntaxError: [ios.entitlements]: withIosEntitlementsBaseMod: Expected "/*" or ";" but "e" found.

**Steps to reproduce the issue:**

eas build -p ios --profile development

**Describe what you expected:**

EAS Build should complete properly.

**Additional context**
    - Version of the SDK: 1.1.3 , expo-datadog: 45.0.1

**Comment by louiszawadzki** [comment]
Hi @erisvaldojunior, thanks for reaching out!

As per [our documentation](https://docs.datadoghq.com/real_user_monitoring/reactnative/expo/) you should use expo-datadog version 46.0.0 if you use expo version 46.

Some native changes happened between expo 45 and 46 and so `expo-datadog` 45 is not working with `expo` 46.

**Comment by louiszawadzki** [comment]
Hi @erisvaldojunior,

You should be using `US5` if your dashboard is on US5.

You can have a look at the native iOS log to see if any error shows up at this level. To do so:
- Open your project in xcode by running `xed ios`
- Build your project for a simulator or a device
- Native logs will appear on the bottom right corner of XCode

You can filter logs by “DATADOG” and look for any error.
If you are indeed sending events, you should see the following logs:

```
[DATADOG SDK] 🐶 → 10:02:47.398 [DEBUG] ⏳ (rum) Uploading batch...
[DATADOG SDK] 🐶 → 10:02:47.538 [DEBUG]    → (rum) accepted, won't be retransmitted: [response code: 202 (accepted), request ID: 2848FE2E-345D-4D8B-82D2-E325CC29B634]
```
The first one indicates that some data is being sent, the second one that the data has been received

If you see the log below, it means that you have called a RUM method before initialising the SDK, which result in further rum events not being sent. 

```
[DATADOG SDK] 🐶 → 10:09:13.621 [WARN] The `Global.rum` was called but no `RUMMonitor` is registered. Configure and register the RUM Monitor globally before invoking the feature:
```


Once you have this information, can you reach out to [our support team](https://www.datadoghq.com/support/), mentioning this issue?
It will make it easier to exchange information and get help from other teams at Datadog.

Thanks a lot!

**Comment by louiszawadzki** [comment]
Hi,

Since there was no update to this issue for a while I'm considering it resolved and will close it.
Feel free to reopen it if it wasn't resolved :)
