### ISSUE TITLE
RUM and Tracing

### ISSUE THREAD

**Issue by andyasberry** [DataDog/dd-sdk-reactnative#314]
We use this package, and our app talks to a Node.js backend that has Datadog APM installed and configured.

We have a couple of questions (forgive me if this is not the correct forum):

1. How do we "connect" the logs between the client (mobile app) and the server? I've read [the docs around RUM and Tracing](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum), but it seems to be a little different than this SDK for React Native. We have configured our `firstPartyHosts` in the React Native RUM initialization.
2. Related to (1) above, how do we get the session id from the Datadog React Native RUM SDK? We would like to pass a custom header to our server that follows a convention at our organization.

Sorry if I've overlooked the relevant docs - I did read through but may have missed something.

Thanks again for this package!!

**Comment by louiszawadzki** [comment]
Hi @andyasberry, thanks for reaching out!

For connecting client and server traces, make sure of the following:
- both your RUM app and your backend service are on the same Datadog organization'
- the host of your backend is in the `firstPartyHosts`
- `resourceTracingSamplingRate` is set to `100` to send all traces for debugging purposes (default is 20%)

If that does not work, please reach out to [our support team](https://www.datadoghq.com/support/) that will be better suited to tackle this issue with you.

As per the session id, we don't expose it in our React Native and native SDKs. Could you explain a bit more what your use case is about this, so we can maybe help you find a way to achieve what you are looking for without exposing this session id?

Thanks a lot.

**Comment by andyasberry** [comment]
Thanks, sorry for not closing this sooner!
