### ISSUE TITLE
EAS Build fails with Expo SDK 46 - bis

### ISSUE THREAD

**Issue by kevinL5** [DataDog/dd-sdk-reactnative#316]
Hello

**Describe what happened**

I started a fresh new project with Expo and try to install Datadog. I followed this instructions from the documentation :  

`yarn add expo-datadog @datadog/mobile-react-native`

`yarn add -D @datadog/datadog-ci`

Then, I haded "expo-datadog" plugin in app.json

` "plugins": ["expo-datadog"]`

Then, I pushed `DATADOG_API_KEY` and `DATADOG_SITE` secrets 

Finally, I initialized config with token and id provided on Datadog website :

```
async function init() {
  const config = new DdSdkReactNativeConfiguration(
     '<MY_CLIENT_TOKEN>',
    '<MY_ENVIRONMENT_NAME>',
    '<MY_RUM_APPLICATION_ID>',
    true, // track User interactions (e.g.: Tap on buttons. You can use 'accessibilityLabel' element property to give tap action the name, otherwise element type will be reported)
    true, // track XHR Resources
    true // track Errors
  );
  // Optional: Select your Datadog website (one of "US", "EU" or "GOV")
  config.site = "EU";
  // Optional: enable or disable native crash reports
  config.nativeCrashReportEnabled = true;
  // Optional: sample RUM sessions (here, 80% of session will be sent to Datadog. Default = 100%)
  config.sessionSamplingRate = 80;

  await DdSdkReactNative.initialize(config);

  return true;
}
```

**EAS Build failled at "Run fastlane" step with the following error :**

```
    Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the testdatadog editor. (in target 'testdatadog' from project 'testdatadog')
2967
▸ ** BUILD FAILED **
2968
▸ The following build commands failed:
2969
▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/testdatadog.build/Debug-iphonesimulator/testdatadog.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'testdatadog' from project 'testdatadog')
2970
▸ (1 failure)
2971
2022-10-16 16:22:55.492 xcodebuild[5124:13446] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2972
2022-10-16 16:22:55.492 xcodebuild[5124:13446] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2973
2022-10-16 16:22:55.549 xcodebuild[5124:13446] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
2974
2022-10-16 16:22:55.549 xcodebuild[5124:13446] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
2975
2022-10-16 16:22:55.549 xcodebuild[5124:13446] XType: unable to make a connection to the font daemon!
2976
2022-10-16 16:22:55.549 xcodebuild[5124:13446] XType: XTFontStaticRegistry is enabled as fontd is not available.
2977
** BUILD FAILED **
2978

2979

2980
The following build commands failed:
2981
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/testdatadog.build/Debug-iphonesimulator/testdatadog.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'testdatadog' from project 'testdatadog')
2982
(1 failure)
```

**Steps to reproduce the issue:**

`eas build -p ios --profile development`

**Describe what you expected:**

EAS Build should complete properly.

**Additional context**

 Here is my package.json :
 

```
  "dependencies": {
    "@datadog/mobile-react-native": "^1.1.3",
    "expo": "^46.0.0",
    "expo-datadog": "^46.0.0",
    "expo-dev-client": "~1.3.1",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.4",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@datadog/datadog-ci": "^1.16.0",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "typescript": "^4.6.3"
  },
```
  

Did I miss anything during the installation? 

Thank you in advance for your help

**Comment by louiszawadzki** [comment]
Hi @kevinL5, thanks for reaching out!

The explicit reason for the build failure does not appear in the fastlane log, could you share the XCode logs from that build as well (you can download them at the bottom of the build)?
If you prefer not to post it publicly here, you can also share them through our support team by mentioning this issue and I will get back to you through support.

Thanks a lot!

**Comment by kevinL5** [comment]
Hi @louiszawadzki !
Thanks for your quick reply. 

I might have a problem with `MARKETING_VERSION` variable. However, I thought that `MARKETING_VERSION` === `CFBundleShortVersionString` === `expo.version` (set in my app.json to ` "version": "1.0.0",`)

```
Environment variable MARKETING_VERSION is missing for Datadog sourcemaps upload.
Check that a Version is set for your target in XCode. It needs to be changed once.
If you are not running this script from XCode, set a MARKETING_VERSION environment variable before running the script.
error Command failed with exit code 1.
```

Here is the full log :
[xcode-build-4690f60f-bf46-4d3c-a131-ba8b86023adb.log](https://github.com/DataDog/dd-sdk-reactnative/files/9803915/xcode-build-4690f60f-bf46-4d3c-a131-ba8b86023adb.log)

**Comment by louiszawadzki** [comment]
Hi @kevinL5 , 

Thanks for this information!
The version field needs to be edited at least once for the `MARKETING_VERSION` variable to be exported by XCode.

Try to change its value, then you can check that it is added in your `project.pbxproj` file before re-running the build.

If reverting it to `1.0.0` removes the variable, you could temporarily add an environment variable to your EAS build.

Tell me if it helps!

**Comment by kevinL5** [comment]
Thank you for the answer @louiszawadzki 

Unfortunately, I don't understand how to do it and why I have to make a modification in XCode.

I'm just trying to install Datadog into a new Expo and build it with EAS.

Do you have any documentation?

**Comment by louiszawadzki** [comment]
Hi @kevinL5,

Thanks for your feedback, we realised that there are [several ways to set your app version](https://docs.expo.dev/build-reference/app-versions) with EAS builds and we might not support all of them yet.

We are working on adding support for these, I'll let you know once support is implemented so you can try it out :)

**Comment by kevinL5** [comment]
Hi @louiszawadzki !

Thank you for the quick reply 😃 

I understood the workaround for EAS build. For anyone interested, you have to manually set the `MARKETING_VERSION` variable with `eas secret:create` or in the Expo interface. 

As you say, the version must be taken into account automatically to avoid doing it manually (and avoid potential errors).
