### ISSUE TITLE
unknown module "undefined" error

### ISSUE THREAD

**Issue by eueddem** [DataDog/dd-sdk-reactnative#318]
**Describe what happened**
Hello, I'm trying to upgrade `@datadog/mobile-react-native` and `@datadog/mobile-react-navigation`, but I'm getting errors on launching the app. Any idea how to resolve?

![Simulator Screen Shot - iPhone 11 - 2022-10-19 at 13 57 21](https://user-images.githubusercontent.com/61439482/196802626-98ed1293-ed4b-4903-bf08-8aca191d8637.png)
![Simulator Screen Shot - iPhone 11 - 2022-10-19 at 13 57 19](https://user-images.githubusercontent.com/61439482/196802635-0fbc5007-ae6a-4d91-9455-9b1eae27588c.png)

**Steps to reproduce the issue:**
Add
"@datadog/mobile-react-native": "^1.1.3",
"@datadog/mobile-react-navigation": "^1.1.3",
to `package.json`, run `yarn install` & `pod install`, and build the app on the iOS simulator.

My `react-native version` is 0.63.4.

**Comment by louiszawadzki** [comment]
Hi @eueddem, thanks for reaching out!

Could you share the version of `react` in your `package.json`? 
If your version is below 16.14.0, this issue will be fixed very soon in version 1.1.4.

**Comment by louiszawadzki** [comment]
Hi, 

Version 1.1.4 of `@datadog/mobile-react-native` has been released and should fix your issue.
Please do tell me if this is not the case and we'll help you troubleshoot further.

**Comment by eueddem** [comment]
Hello @louiszawadzki , it works! Thanks for the quick fix. My project is on `react` 16.13.1

**Comment by louiszawadzki** [comment]
Thanks for your feedback @eueddem!
I'm closing the issue, feel free to open a new one if you encounter any other problem :)
