### ISSUE TITLE
Update expo-datadog to support expo 47

### ISSUE THREAD

**Issue by Nicktho** [DataDog/dd-sdk-reactnative#337]
**Is your feature request related to a problem? Please describe.**
Expo 47 has been released and is not compatible with expo-datadog as it's peer dependency is expo@46.x

**Describe the solution you'd like**
Update expo-datadog so that it supports expo 47

**Describe alternatives you've considered**
Downgrading to expo 46.

**Comment by louiszawadzki** [comment]
Hi @Nicktho, thanks for reaching out!

We've just released version 47.0.0 of `expo-datadog`.
By the way, we're in the process of extracting the expo repo from this one to https://github.com/DataDog/expo-datadog, if you encounter any problem, feel free to open an issue in the expo repo directly :)
