### ISSUE TITLE
RUM sessions are not always stopped when the app goes to background

### ISSUE THREAD

**Issue by simontreny** [DataDog/dd-sdk-reactnative#341]
**Describe what happened**

I'm recording RUM sessions using the SDK and quite often, sessions stay active even though the app is "closed" by the user. When this happens, sessions are reported as still active despite the fact that the app is no longer on foreground. If the app is killed manually and relaunched, it seems to prevent new sessions from being recorded, and views/actions/resources are not recorded to the previous, still "active" session. I sometimes need to wait tens of minutes before the session is marked as stopped in Datadog's "Sessions and replays" dashboard.

**Steps to reproduce the issue:**

Here is how the SDK is initialized:
```ts
const config = new DdSdkReactNativeConfiguration(
    clientToken,
    env,
    applicationId,
    true, // Track User interactions (e.g.: Tap on buttons)
    true, // Track XHR Resources
    true // Track Errors
  );
  config.nativeCrashReportEnabled = false;
  config.site = "EU";
  config.sessionSamplingRate = 100;
  config.resourceTracingSamplingRate = 100;
  config.firstPartyHosts = ["my-domain.com"];
  config.verbosity = SdkVerbosity.DEBUG;
  await DdSdkReactNative.initialize(config);
  DdRumReactNavigationTracking.startTrackingViews(navigatorRef.current)
```

I can reproduce the issue on iOS on a simulator and device. With `verbosity` set to `SdkVerbosity.DEBUG`, I can see that views, resources and actions are tracked properly on the client.

**Describe what you expected:**

I would expect that a session starts when the user launch the app and stops when they close the app. I would be fine if the session resumed when the app is brought to background again, but then, lifecycle events (going to background, going back to foreground) should be tracked as actions and the `session.time_spent` attribute shouldn't take into account  the time spent while the app is in background.

**Additional context**

- `@datadog/mobile-react-native`: 1.1.4
- `DatadogSDK` pod: 1.12.1
- `DatadogSDKReactNative` pod: 1.1.4
- iOS 16.0

**Comment by louiszawadzki** [comment]
Hi @simontreny, 

I hope that you found the solution to your issue! As it's not been active for a while I'm going to close it, feel free to reopen it if this is not the case!
