### ISSUE TITLE
Cannot see RUM traces in Datadog UI

### ISSUE THREAD

**Issue by sushilr** [DataDog/dd-sdk-reactnative#356]
**Describe what happened**
I'm using the DdTrace.startSpan(..) and DdTrace.finishSpan(..) APIs and I can't find the trace in Datadog. 

I'm trying to test this out on a sample trace. 
```
const spanId = await DdTrace.startSpan(
			'mobile_testing_sample_trace',
			undefined,
			Date.now(),
		);
DdTrace.finishSpan(spanId, undefined, Date.now() + 100);
```

Is the API usage correct? Can you point me to examples to set up custom traces? Thank you! 

**Steps to reproduce the issue:**

**Describe what you expected:**
I need the trace to show up in Datadog UI

**Additional context**

-   Version of the SDK - 1.1.3
-  Running on an Android device

**Comment by sushilr** [comment]
@louiszawadzki sorry about the ping here, but was just looking for some help/direction :) We'd really like to use the tracing APIs, but we're not sure if it is working as expected yet. Do you suggest using actions or similar for this?

**Comment by louiszawadzki** [comment]
Hi @sushilr,

Thanks for reaching out and I apologize for the delay.
The way you call the tracing API seems correct to me, I've copied your code over and I'm able to see the traces in [APM](https://docs.datadoghq.com/tracing/).

However these traces won't appear in the "Traces" tab from RUM views, as this tab currently only displays RUM Resources linked to one of your first party host (see [documentation](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=androidrum)).

Could you confirm you were looking at the APM page? If so and you don't see any trace, I would advise you to reach out to [our support team](https://www.datadoghq.com/support/), as they will help identify the issue as it can come from a lot of different places in the product.

I hope this helps :)

**Comment by sushilr** [comment]
Thank you @louiszawadzki! I am actually able to see traces today, not sure why I wasn't able to see it when I reported.

**Comment by sahejeventme** [comment]
@sushilr were you able to see traces in the "Traces" tab under RUM application specific session?
