### ISSUE TITLE
Can't get error tracking working on Android

### ISSUE THREAD

**Issue by onlyanegg** [DataDog/dd-sdk-reactnative#359]
**Describe what happened**

I can't get error tracking working in android. Here's dummy project on expo 47, but I also can't get it working on my real project which is on expo 45.

https://github.com/onlyanegg/datadog-error-tracking

I basically just created a new expo project, installed the datadog dependencies, and wrote some logging and error tracking code.

Some notes:

- I'm running on a Pixel 3A emulator on Android API 33
- I can see the log that I'm sending
- I can't see any errors in Android both when I thrown and when I use `DdRum.addError`
- It works fine for me on an iPhone 14 simulator on iOS 16.2

**Steps to reproduce the issue:**

- Clone the project
- Replace `DdSdkReactNativeConfiguration` values in `App.js`
- `yarn && yarn expo prebuild && yarn android`
- Click "Press me!"

**Describe what you expected:**

- I expect to see errors in the Error Tracker UI

**Comment by louiszawadzki** [comment]
Hi @onlyanegg, thanks for reaching out!

Thanks a lot for providing an example, I think you're only missing a call to `DdRum.startView` for the errors to be reported, like so:
```
DdSdkReactNative.initialize(config).then(() => DdRum.startView("main", "Main"));
```
Once I've added this, I've been able to see the errors in the sessions.
Tell me if that solves the issue on your example, or if you still see the issue.

I've also noticed some delays in the errors that seems to be resolved now, maybe this was the issue for you as well? If that's the case, the errors on your app might have come through now, can you check and tell me if it works?

If you're still experiencing issue on your app, but not on the example app, can you maybe share your implementation of the Datadog SDK as well as the list of dependencies of your project (some might interfere with our SDK)?

Thank you!

**Comment by onlyanegg** [comment]
Thanks, Luis! I appreciate you getting back to me so quickly!

Hmmm, that fixed it, but I didn't expect error tracking to be dependent on view tracking.

**Comment by Szakariia** [comment]
Hello guys, 

I need some help please, am facing this error : 

" WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: null is not an object (evaluating '_foundation.DdSdk.initialize')"

when I try to initialize my dataDog Config in this line :

DdSdkReactNative.initialize(config);


any help please .

**Comment by louiszawadzki** [comment]
Hi @onlyanegg!

As there has not been activity on this issue for a while I'm going to close it.

Feel free to reopen it with more details if you still encounter a problem :)
