### ISSUE TITLE
detekt config looks for a  detekt.yml in root always. 

### ISSUE THREAD

**Issue by zsfVishnu** [DataDog/dd-sdk-reactnative#361]
**Describe what happened**

detekt config looks for a detekt.yml in root always.  While publishing the sdk, do we really need detekt? And if we do need it, can we add an option to specify an alternate path for the config file, if the detekt.yml is not maintained in the root of the consumer project?

**Steps to reproduce the issue:**
Any project using the sdk where the detekt.yml is in any location other than project root will throw an error while running detekt check.

**Describe what you expected:**

An option to provide a custom path to the config file or remove the detekt before publishing.

**Additional context**
This is the code from v1.1.5
```

detekt {
  input = files("$projectDir/src/main/kotlin")
  config = files("${project.rootDir}/detekt.yml")

  reports {
    xml {
      enabled = true
      destination = file("build/reports/detekt.xml")
    }
  }
}
```

**Comment by louiszawadzki** [comment]
Hi @zsfVishnu, thanks for reaching out!

I agree that this could be improved, and even if most RN projects don't use detekt, we could give more flexibility for projects using it.

To help us understand better how to solve this, could you specify your use case?
Why do you have a `detect.yml` in your React Native project and where is it located?

Thanks!

**Comment by zsfVishnu** [comment]
Hey @louiszawadzki , our project has native code across different modules inside the android folder of our react native project. For similar projects, the detekt.yml is usually kept in the root of the android folder which gets picked up when detekt is run. For various purposes including saving time on our build, we run detekt on specifc modules and provide their respective detekt config files within that module and not the root. I do agree that this might not be a regular use case and so i was thinking we could add a capability to optionally run datadog:detekt or provide an alternate path.

**Comment by karankalsi** [comment]
I am also facing the same issue on RN 0.68.2

**Comment by zsfVishnu** [comment]
@karankalsi can you confirm whether your `detekt.yml `is in the project root or not?

**Comment by louiszawadzki** [comment]
@zsfVishnu I implemented a fix using our detekt config if none is detected at the root of the project - ensuring it will always pass (see link just above)
Would this work for you?

**Comment by zsfVishnu** [comment]
@louiszawadzki This looks good .

**Comment by karankalsi** [comment]
> an you confirm whether your `detekt.yml `is in the project root or not?

No `detekt.yml` is not there in the project root.
