### ISSUE TITLE
can't find repo when building for Android

### ISSUE THREAD

**Issue by mutablestudio** [DataDog/dd-sdk-reactnative#37]
Not sure if this is a bug, but for me building on Android failed because it could not find the datadog repo. Maybe we could add something to the readme, to add this to repositories in the root `build.gradle` for Android:

```
allprojects {
    repositories {
        ...
        maven { url "https://dl.bintray.com/datadog/datadog-maven" }
    }
}
```

**Comment by 0xnm** [comment]
Hello @mutablestudio! We are moving away from Bintray to Maven Central and our upcoming releases are already there (ex: https://search.maven.org/artifact/com.datadoghq/dd-sdk-android). So next release of `dd-sdk-reactnative` won't have a dependency on Bintray.
