### ISSUE TITLE
Can install mobile-react-navigation

### ISSUE THREAD

**Issue by elmcapp** [DataDog/dd-sdk-reactnative#375]
Cannot find module '@datadog/mobile-react-navigation' or its corresponding type declarations.ts(2307).

I followed all install instructions

I am on Mac and running react native ^18.0.0

**Comment by louiszawadzki** [comment]
Hi @elmcapp, thanks for reaching out!

Unfortunately we cannot reproduce the issue on our side by following [these instructions](https://www.npmjs.com/package/@datadog/mobile-react-navigation).
Can you make sure that when you run `yarn add @datadog/mobile-react-navigation` or `npm install @datadog/mobile-react-navigation` the command succeeds and that the package is installed at `node_modules/@datadog/mobile-react-navigation`?

If that is already the case, could you share a minimal project reproducing the issue to help us understand the issue?

Thanks a lot!
