### ISSUE TITLE
Provide an example of how to mock DatadogProvider

### ISSUE THREAD

**Issue by curthipster** [DataDog/dd-sdk-reactnative#380]
**Is your feature request related to a problem? Please describe.**
My unit tests are failing now that I have `DatadogProvider` wrapping my application code. This requires me to figure out what and how to mock parts of the module. This is less trivial than it used to be, now that the application code is a child of the provider.

**Describe the solution you'd like**
A working example would be great. Another option would be to export a mock, e.g., like `react-native-safe-area-context` does: https://github.com/th3rdwave/react-native-safe-area-context/blob/main/jest/mock.js

**Describe alternatives you've considered**
I'm trying to figure out how to mock it in a way that the children components are still rendered.

I've searched existing issues and around the Internet, and I haven't seen anyone else posting about this yet. The library is pretty new.

**Additional context**

Tests rendering `App` used to pass, and now they don't. 

Before (passes):
```

// In test setup
jest.mock('@datadog/mobile-react-native');

// App.tsx
const ddConfig = { /* omitted */ };

export default function App() {

  useEffect(() => {
    await DdSdkReactNative.initialize(ddConfig);
  }, []);


  return (
    <View testID="test-view" />
  )
}

// App.spec.tsx
import { render } from '@testing-library/react-native';

it('renders', async () => {
  const { findByTestId } = render(<App />);

  await findByTestId('LoginHeader');
});
```

After (fails):
```

// In test setup
jest.mock('@datadog/mobile-react-native');

// App.tsx
const ddConfig = { /* omitted */ };

export default function App() {

  return (
    <DatadogProvider configuration={ddConfig}>
      <View testID="test-view" />
    </DatadogProvider>
  )
}

// App.spec.tsx
import { render } from '@testing-library/react-native';

it('renders', async () => {
  const { findByTestId } = render(<App />);

  await findByTestId('LoginHeader');
});
```

**Comment by louiszawadzki** [comment]
Hi @curthipster, thanks for reaching out!

This is some very valuable feedback, I've opened a pull request with a complete mock: https://github.com/DataDog/dd-sdk-reactnative/pull/381

If you want to try it before it's included in the next release, you can simply copy the content of the `jest/mock.js` file from that PR in your app, at the following location from the root of your app:  `__mocks__/@datadog/mobile-react-native.js`.

Let me know if you still have some errors in your tests after this!
If that's the case you can include the full stack trace so I can help you solve them :)

**Comment by curthipster** [comment]
@louiszawadzki, thank you for the quick turnaround! It works perfectly for me.

**Comment by blwinters** [comment]
Thanks for the mock. I'll add that for my project configuration, I needed to add the mock to the jest config's `transformIgnorePatterns` so that it would transpile the jsx inside the mock to make it compatible with jest. Here are some more details for context:

```
// Error message when running jest:

Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

[...]

 /[...]/node_modules/@datadog/mobile-react-native/jest/mock.js:19
        return <>{children}</>;
               ^

    SyntaxError: Unexpected token '<'

      70 |
      71 | jest.mock('@datadog/mobile-react-native', () => {
    > 72 |   return require('@datadog/mobile-react-native/jest/mock')
         |          ^
      73 | })
      74 |
```

``` javascript
// jest.config.js
const untranspiledModulePatterns = [
  '(jest-)?react-native',
  '@react-native(-community)?',
  '@?expo',
  'react-navigation',
  '@react-navigation/.*',
  '@datadog/mobile-react-native/jest/mock', // <----
]

const nodeModulesIgnorePattern = `node_modules/(?!(${untranspiledModulePatterns.join('|')}))`

module.exports = {
  // ...
  transform: {
    '^.+\\.jsx$': 'babel-jest',
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.spec.json',
      },
    ],
  },
  transformIgnorePatterns: [nodeModulesIgnorePattern],
  // ...
}


```

**Comment by lucasfronza** [comment]
> I needed to add the mock to the jest config's transformIgnorePatterns so that it would transpile the jsx inside the mock to make it compatible with jest.

Same! Perhaps worth adding this to [advanced_configuration.md](https://github.com/DataDog/dd-sdk-reactnative/blob/develop/docs/advanced_configuration.md#testing-with-jest)? I don't mind doing a PR for it if it makes sense to add it.
