### ISSUE TITLE
Passing traceID into DD logs.

### ISSUE THREAD

**Issue by peteratdivvy** [DataDog/dd-sdk-reactnative#389]
**Is your feature request related to a problem? Please describe.**
It's a feature request, not a problem.

**Describe the solution you'd like**
We use datadog APM logs on our web frontend application and it's awesome that we can track the whole lifecycle of an error from frontend request to backend errors. 

We'd love to be able to do that on our react native side as well. 

**Describe alternatives you've considered**
I've looked through the logs and found nothing that relates to traceId. 

**Additional context**

**Comment by louiszawadzki** [comment]
Hi @peteratdivvy, thanks for reaching out!

You can actually achieve this with automated resource tracking!
You need to specify two fields in your configuration:

```javascript
// Optional: Sample tracing integrations for network calls between your app and your backend (in this example, 80% of calls to your instrumented backend are linked from the RUM view to the APM view. Default is 20%)
// You need to specify the hosts of your backends to enable tracing with these backends
config.resourceTracingSamplingRate = 80;
config.firstPartyHosts = ['example.com']; // matches 'example.com' and subdomains like 'api.example.com'
```

And make sure `trackResources` (5th argument in the `DdSdkReactNativeConfiguration` constructor) is set to `true`.

This will have the same effect as explained for browser here: https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum#setup-rum
Your `firstPartyHosts` for React Native should include the same list as `allowedTracingUrls` does for web, with the addition of the host of your app if you use it for your API as well (we cannot infer it in mobile SDKs). 

Let me know if this helps, or if you are looking for something else :)

**Comment by awaldow** [comment]
Engaging in some necromancy here, what about the case where I want logs emitted from my react native app to get attached to the logs view of the resource request trace? As far as I can tell the logs coming out of using `DdLogs.*` don't get a trace ID (or at least its not the same one as the resource I have) so I can't see logs from the mobile app before and after resource requests are being made within the trace page for that XHR request or whatever. Am I thinking about that wrong?

**Comment by plousada** [comment]
Hi @awaldow, indeed correlation between Traces and Logs is currently not available in the React Native SDK. Thank you for raising awareness. 
You are correct that Logs performed during an active trace should be highlighted in the Trace panel. 

We'll plan to add it in a near future release and get back to you once it's available.
