### ISSUE TITLE
Datadog Could not invoke DdSdk.initialize

### ISSUE THREAD

**Issue by Afdz1020** [DataDog/dd-sdk-reactnative#397]
Thanks for taking the time to report an issue!

If you are having trouble sending data from the SDK but don't see any error, please reach out first [through our support team](https://www.datadoghq.com/support/).

**Describe what happened**
Hi all, I have upgraded to version 1.2.0 and did the respective configuration for this version, but when I run the application in android shows the following error `Could not invoke DdSdk.initialize`

![MicrosoftTeams-image](https://user-images.githubusercontent.com/17262900/216422467-8c31e9cd-d666-47a6-8eed-b53a550e0f71.png)

**Steps to reproduce the issue:**

Building in android in IOS is working fine

**Describe what you expected:**

to be able to run the app in my local environment

**Additional context**

-   Version of the SDK
-   ` "@datadog/mobile-react-native": "1.2.0",
        "@datadog/mobile-react-navigation": "1.2.0",`
-   `android/build.gradle`
    [androis/build.gradle](https://gist.github.com/Afdz1020/1a2d4333bb75e79e4e1858c660d536fd)
- `android/app/build.gradle`
    [android/app/build.gradle](https://gist.github.com/Afdz1020/a0f775a170baf409e05fd1c5626ab3fb)

**Comment by louiszawadzki** [comment]
Hi @Afdz1020, thanks for reaching out!

This looks like your version of React Native is missing some methods on Android.
Could you specify which version of React Native you are using to help us troubleshoot?

Thanks a lot

**Comment by Afdz1020** [comment]
@Hi @louiszawadzki 

In the project are using the version of react native 0.67.2

Thanks

**Comment by sergeyphi** [comment]
@Afdz1020 @louiszawadzki I'm seeing the same issue in my build when upgrading DD. Curious, was there a resolution in your case? Thanks!

**Comment by juliusiqbalfn** [comment]
@Afdz1020 @louiszawadzki I am facing similar issue in my Android build when upgraded Datadog SDK to v2.3.3 and using React Native v0.73.8. What should I try or do to resolve?

![image](https://github.com/DataDog/dd-sdk-reactnative/assets/56021945/e174cf4d-1b66-4733-9c07-6e93b11205d3)

NOTE: iOS build works fine with Datadog SDK v2.3.3 and using React Native v0.73.8.
