### ISSUE TITLE
areObjectShallowEqual does not handle edge case where objectA or objectB are null or undefined.

### ISSUE THREAD

**Issue by jackson-allio** [DataDog/dd-sdk-reactnative#419]
> Thanks for taking the time for reporting an issue!
> 
> If you are having trouble sending data from the SDK but don't see any error, please reach out first [through our support team](https://www.datadoghq.com/support/).
> 
> **Describe what happened**
> Include any error message or stack trace if available.

_**TLDR: We have a proposed fix below, at the end of this issue.**_

The Datadog React Native SDK internally overrides `React.memo`, and the `areObjectShallowEqual` method used to compare props between invocations is not safe against arguments being `undefined` or `null`. Under certain circumstances, _even if it is not supposed to happen_, memoized hooks can uninitialized values, so the memo comparison between a `setState` or similar setter will throw an error: 

```
 DEBUG  DATADOG: Tracking error log “Cannot convert null value to object”
```

<img src="https://user-images.githubusercontent.com/126990718/222936521-4cfb9a21-b3d5-4265-9d87-67c30db5eed0.png" width="320" />

> **Steps to reproduce the issue:**

In our use case, we are using Datadog to instrument our React Native application, with [Recoil](https://recoiljs.org/) for state management, and [LaunchDarkly](https://docs.launchdarkly.com/sdk/client-side/react/react-native) for feature flag management.

Please note, because of the combination of these three libraries, we are probably creating a rare and unexpected edge case.

Internally, Recoil uses React Context to manage state, and `useRecoilState` is essentially a wrapper for `useState`. You can supply a default value. LaunchDarkly needs to be initialized asynchronously, similar to Datadog, and the client must be connected to poll / listen for flag status changes. An example configuration might look like this:

```typescript
import { useEffect } from 'react';
import { atomFamily, useRecoilState } from 'recoil'
import LDClient, { LDConfig } from 'launchdarkly-react-native-client-sdk';

const ldConfig: LDConfig = {};
const ldUser = {};
const launchDarklyClient: LDClient = new LDClient();
let isReady = false;

async function getLaunchDarklyClient() {
  if (!isReady) {
    try {
      await launchDarklyClient.configure(ldConfig, ldUser);
      isReady = true;
    } catch (err) {
      console.error(err, 'Error initializing LaunchDarkly Client');
   }
}

const featureFlagCache = atomFamily({
  key: 'feature-flag-cache',
  // This is to allow for the scenario where the feature flag default could be set to anything, including undefined - no default value is a valid outcome
  default: () => undefined,
});

// For purpose of the bug, we are only dealing with boolean flags, but we could have various flag types
export function useBooleanFeatureFlag(flagName: string, defaultFlagValue: boolean): boolean {
  const [flagValue, setFlagValue] = useRecoilState(flagCache(flagName));

  useEffect(() => {
    const updateFlags = async (flagKey: string) => {
      const client = await getLaunchDarklyClient();
      // This asynchronously resolves to a valid value, or the default if provided
      const newFlagValue = await client.boolVariation(flagKey, !!defaultFlagValue);
      // This is where things get weird; behind the scenes, Recoil might backfill the default: () => undefined as the state while consumers get set to newValue, breaking Datadog's React.memo override
      setFlagValue(newFlagValue);
    };
    void updateFlags(flagName);
  }, [defaultFlagValue, flagName, setFlagValue]);

  return flagValue;
}
```

Then, in our entry, a bare-bones Datadog integration:

```typescript
// App.tsx
import {
  DdSdkReactNative,
  DdSdkReactNativeConfiguration,
  TrackingConsent,
  SdkVerbosity,
} from '@datadog/mobile-react-native';
import React from 'react';
import { RecoilRoot } from 'recoil';
import { BaseApp } from './BaseApp';

const DdConfig = new DdSdkReactNativeConfiguration(
  Config.DATA_DOG_CLIENT_TOKEN,
  Config.ENVIRONMENT,
  Config.DATA_DOG_APPLICATION_ID,
  true, // track user interactions (such as a tap on buttons)
  true, // track XHR resources
  true, // track errors
  TrackingConsent.GRANTED,
);

DdSdkReactNative.initialize(DdConfig);

export function App() {
  return (
    <RecoilRoot>
      <BaseApp />
    </RecoilRoot>
  );
}
```

While this isn't a common setup, it raises the edge case where an internally `React.memo`'d method call (`setRecoilState` -> `setState`) can be called where one of the previous or next memoized parameters might be `undefined`, `null`, or even simply "missing" due to asynchronous behavior.

> **Describe what you expected:**

In normal operation, this works fine. It's simply once integrating Datadog that this breaks down and throws the error.

> **Additional context**

-   Version of the SDK: `1.4.0`
-   `package.json`: 
```json
{
  "dependencies": {
    "@datadog/mobile-react-native": "^1.4.0",
    "@datadog/mobile-react-native-code-push": "^1.4.0"
  },
  "devDependencies": {
    "@datadog/datadog-ci": "^2.5.1"
  }
}
```
-   `Podfile` and `Podfile.lock`:
```
PODS:
  - DatadogSDK (1.15.0)
  - DatadogSDKCrashReporting (1.15.0):
    - DatadogSDK (= 1.15.0)
    - PLCrashReporter (~> 1.11.0)
  - DatadogSDKReactNative (1.4.0):
    - DatadogSDK (~> 1.15.0)
    - DatadogSDKCrashReporting (~> 1.15.0)
    - React-Core
```
-   `android/build.gradle` and `android/app/build.gradle`: N/A

### Proposed Fix

The fix we implemented locally was to use `patch-package` to inject some additional comparisons and checks in `areObjectShallowEqual`. We suggest applying this here, as it should not break any existing functionality, but rather, ensure that _if for any reason `objectA` or `objectB` are `null` or `undefined`, the comparison does not throw an error_.

```diff
--- a/node_modules/@datadog/mobile-react-native/src/rum/instrumentation/interactionTracking/ShallowObjectEqualityChecker.ts
+++ b/node_modules/@datadog/mobile-react-native/src/rum/instrumentation/interactionTracking/ShallowObjectEqualityChecker.ts
@@ -11,6 +11,23 @@ export const areObjectShallowEqual = (
     objectA: Record<string, unknown>,
     objectB: Record<string, unknown>
 ): boolean => {
+
+    if (typeof objectA !== typeof objectB) {
+        return false;
+    }
+
+    if (objectA === undefined) {
+        return objectB === undefined;
+    }
+
+    if (objectA === null) {
+        return objectB === null;
+    }
+    
+    if (objectB === undefined || objectB === null) {
+        return false;
+    }
+
     const keys = Object.keys(objectA);
     if (keys.length !== Object.keys(objectB).length) {
         return false;
```

**Comment by louiszawadzki** [comment]
Hi @jackson-allio, thanks for reaching out and for the comprehensive explanation!

I think your fix could be brought in, but before that I would also like to make sure we cover your case in our unit tests so it's not broken by accident in later releases.

If you don't mind, could you clarify why and how you're using `React.memo` on a method call? I've been looking for such a use case, and I could only find examples of `React.memo` being called to memoized React components, not method calls. 
If you can include a simple example of such a use case that would also be very helpful. 

Thanks a lot!

**Comment by jackson-allio** [comment]
@louiszawadzki We're not using `React.memo` on a method call, only on components - though, it's my understanding that  `useCallback`, `useEffect` internally rely on memoization or an adaptation of it via the dependency array. However, when a `setState` or `setRecoilState` is modifying a prop consumed by a `React.memo`'d component, we're interacting with `React.memo` and potentially creating the scenario were props (or at least, whatever is being passed to the overridden `React.memo`) are `null` or `undefined`.

I'm not entirely sure "why" the props end up `null` or `undefined`, but it's a potential edge case we're encountering one way or another. We aren't using any custom `compare` method instead our memoized components, so the `React.memo` override here is taking precedence.

I suspect Suspense mode may have something to do with it, since our use case does involve some async behavior. If not, I'm unsure.

**Comment by louiszawadzki** [comment]
Hi @jackson-allio, thanks for coming back with more details!

This is indeed a specific edge case, so I'd very much to have a unit test in place before fixing it, to make sure we don't accidentally break it in the future.

To help us properly fix this and test our fix faster, could you maybe share a short reproducible example? Even a failing unit test with a small component using testing-library would be enough :) 
Alternatively you can reach out through our support team (https://www.datadoghq.com/support/), so you can securely share concrete examples from your app.

Thanks a lot!

**Comment by jackson-allio** [comment]
@louiszawadzki Sorry for the delay.

A full reproducible example is available in this repo: https://github.com/jackson-allio/dd-sdk-reactnative-issues-419

To further drill down into the issue, I suspect that the problem is occurring if a props are changing on a component that is suspended. While suspended, memoization appears to break down and props are temporarily `null`. This means that  `objectA` in `areObjectShallowEqual` is `null`, throwing a `[TypeError: Cannot convert undefined or null to object]` when trying to call `Object.keys(objectA)`.

In the repo / reproducible example, I've included the current source code for `areObjectShallowEqual` and a lightweight stub of the Datadog SDK's override of `React.memo` causing the problem. The unit tests and associated mocks should highlight the issue clearly. Hopefully this addresses your concerns?

```typescript
function App() {
  const [prop, setProp] = useState(false);
  
  useEffect(() => {
    setProp(true);
  }, []);
  
  return (
    <Suspense fallback={<ActivityIndicator />}>
      <Component prop={prop} />
    </Suspense>
  )
}
```

**Comment by louiszawadzki** [comment]
Hi @jackson-allio, thank you very much for taking the effort to provide us with an example 🙇  

I will look into it to see if we can produce a good unit test and and keep you updated!

**Comment by jackson-allio** [comment]
Hey @louiszawadzki, just checking if there is any update on this? The unit tests I provided in the sample repo should provide a good baseline for reproducing & testing the issue.

**Comment by jackson-allio** [comment]
@louiszawadzki Any movement on this?

**Comment by louiszawadzki** [comment]
Hi @jackson-allio, 
Sorry we've been pushing this for other topics with higher priority, I will try to fit it in the next minor release.
