### ISSUE TITLE
Cannot read property 'initialize' of null

### ISSUE THREAD

**Issue by aravindhan2612** [DataDog/dd-sdk-reactnative#443]
**Describe what happened**
Hi all , I have setup the react native project with latest version (v0.71.6), also installed DataDog sdk (v1.5.0). Configured the data dog and run the app in IOS simulator , it throws me warning ' Cannot read property 'initialize' of null' . I'm able to run the app in android emulator without any issue and also able to see the events in Data dog dashboard
![image](https://user-images.githubusercontent.com/46160304/230101032-1ecd5d14-1bcf-4987-ad5f-30124c541399.png)

**Steps to reproduce the issue:**
Run the React native app in IOS simulator

**Describe what you expected:**
Able to run the app in IOS simulator and able to see the events in Data dog dashboard
**Additional context**

-   Version of the SDK: 1.5.0
-   Version of React Native: 0.71.6
-   `package.json`
-   `Podfile` and `Podfile.lock`
-   `android/build.gradle` and `android/app/build.gradle`

**Comment by louiszawadzki** [comment]
Hi @aravindhan2612, thanks for reaching out!

This would mean that your app is lacking the native modules from the SDK.
Can you run `pod install`, rebuild your ios app and try again?

Thanks a lot

**Comment by aravindhan2612** [comment]
Thanks @louiszawadzki , it's working now.
