### ISSUE TITLE
Bindings for beta feature flag functionality

### ISSUE THREAD

**Issue by stevoland** [DataDog/dd-sdk-reactnative#463]
Hi, just wondering if this is on the roadmap?

https://docs.datadoghq.com/real_user_monitoring/guide/setup-feature-flag-data-collection/?tab=ios

Thanks!

**Comment by louiszawadzki** [comment]
Hi @stevoland, thanks for reaching out!

It's indeed high in our backlog, I'll let you know once this is released :)

**Comment by stevoland** [comment]
Released in v1.7.0 👍
