### ISSUE TITLE
DdLogs may never be sent if logger is called too soon (<=1.5.2)

### ISSUE THREAD

**Issue by stevoland** [DataDog/dd-sdk-reactnative#468]
**Describe what happened**

<strike>In Debug builds logs appear in [DD logs](https://app.datadoghq.eu/logs) (and in 1.5.2 are linked to the view) but in Release builds with both 1.5.1 and 1.5.2, no logs appear in DD.</strike>

Often no logs ever sent if DdLogs method has been called before initialisation.

**Steps to reproduce the issue:**

Use async initialisation. Calls DdLogs methods before and after initialisation.

`DdLogs.info('message')`

**Describe what you expected:**

Logs sent to DD when logger is called after initialisation.

**Additional context**

-   Version of the SDK: 1.5.2
-   Version of React Native: 0.69.4

**Comment by stevoland** [comment]
Have tried to debug 1.5.2 a bit more on ios simulator. 

In Debug configuration I can see POSTs to both

`https://browser-intake-datadoghq.eu/api/v2/rum` and
`https://browser-intake-datadoghq.eu/api/v2/logs`

But in Release configuration there are no requests to `https://browser-intake-datadoghq.eu/api/v2/logs`

I've placed an `Alert.alert('message')` after the calls to `DdLogs.info('message')` so I know that the log method is being called in the Release build.

**Comment by dann95** [comment]
@stevoland  if you let me enhance your issue post:

I'm facing the same problem, no log in production, but i tried different verions 1.5.0 | 1.4.0 |  1.2.1 and none of them make logs in prod. Also Android works fine both (debug and release)

**Comment by stevoland** [comment]
@dann95 of course. Happy to hear it's not just me! I also tried 1.2.1 release build and got no logs.

I haven't seen any logs from our 1.5.0 Android release build but I need to spend some time verifying that. If there is an issue it's likely a different one as the JS side seemed to be doing what it should when I poked around with 1.5.2 yesterday.

**Comment by dann95** [comment]
> @dann95 of course. Happy to hear it's not just me! I also tried 1.2.1 release build and got no logs.
> 
> I haven't seen any logs from our 1.5.0 Android release build but I need to spend some time verifying that. If there is an issue it's likely a different one as the JS side seemed to be doing what it should when I poked around with 1.5.2 yesterday.

my Android production app (release build) is running 1.5.0, i had no problems with Android, just with IOS, idk how much time they take to answer here, but i think company i work has a special support package, so if no answer until monday i will try that channel.

**Comment by 0xnm** [comment]
Hello @stevoland! I cannot reproduce this problem when running our sample app in `Release` configuration. I can see the logs fine.

Do you see any errors/warnings in the device logs? You can set SDK verbosity to `SdkVerbosity.DEBUG` to see all the details.

**Comment by stevoland** [comment]
Hi @0xnm! I couldn't reproduce either on the sample app on your develop branch and then I realised that you fixed it last week https://github.com/DataDog/dd-sdk-reactnative/pull/464 (I actually thought that change had gone into 1.5.2)

The Debug/Release thing was a red-herring, presumably race conditions on when logs are called relative to initialisation.

Looking forward to the next release 😄 I'll edit this ticket's details and leave it open until then. Cheers

**Comment by 0xnm** [comment]
Indeed, the PR #464 you've mentioned is not released yet. This PR fixes the bug when logs are sent before SDK is initialized, so iOS implementation is stuck with no-op implementation of the underlying logs processor.

If it is critical for you and you don't want to wait for the next release (which should happen soon anyway), you can check your app for the log entries which can be sent before SDK is initialized.

**Comment by stevoland** [comment]
@0xnm Not critical for me but out of interest: is there a built-in way of querying if the SDK has been initialised?

**Comment by stevoland** [comment]
Fixed for me in 1.6.0 so closing, thanks
