### ISSUE TITLE
Support for Expo Managed Workflow

### ISSUE THREAD

**Issue by agjini** [DataDog/dd-sdk-reactnative#47]
Thanks for taking the time for reporting an issue!

**Describe what happened**

The build of my react native expo application which uses dd-sdk-reactnative fails on IOS using eas build.
It looks like arm64 architecture is not supported at JSON encoder level (Mac M1 chip ??).

**Steps to reproduce the issue:**

- Build a new expo managed app.
- Add `dd-sdk-reactnative` dependency (1.0.0-alpha5)
- Call dd-sdk-reactnative init method in App.tsx.
- Launch a build using `eas build` (i've don't tried

**Describe what you expected:**
To be able to build my react native app on `arm64` mac with `dd-sdk-reactnative`.

**Additional context**
    - version : `1.0.0-alpha5`

The xcode build failure (on expo EAS IOS build server) :
```
Undefined symbols for architecture arm64:
  "Network.NWPath.isConstrained.getter : Swift.Bool", referenced from:
      closure #1 (Network.NWPath) -> () in Datadog.NWPathNetworkConnectionInfoProvider.init(monitor: Network.NWPathMonitor) -> Datadog.NWPathNetworkConnectionInfoProvider in libDatadogSDK.a(NetworkConnectionInfoProvider.o)
  "static Foundation.JSONEncoder.OutputFormatting.withoutEscapingSlashes.getter : Foundation.JSONEncoder.OutputFormatting", referenced from:
      function signature specialization <Arg[0] = Dead> of static (extension in Datadog):Foundation.JSONEncoder.default() -> Foundation.JSONEncoder in libDatadogSDK.a(JSONEncoder.o)
  "(extension in Foundation):__C.NSFileHandle.readToEnd() throws -> Foundation.Data?", referenced from:
      Datadog.File.read() throws -> Foundation.Data in libDatadogSDK.a(File.o)
  "(extension in Foundation):__C.NSFileHandle.seekToEnd() throws -> Swift.UInt64", referenced from:
      Datadog.File.append(data: Foundation.Data) throws -> () in libDatadogSDK.a(File.o)
  "(extension in Foundation):__C.NSFileHandle.write<A where A: Foundation.DataProtocol>(contentsOf: A) throws -> ()", referenced from:
      Datadog.File.append(data: Foundation.Data) throws -> () in libDatadogSDK.a(File.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

my package.json
```json
{
  "main": "index.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/inter": "^0.1.0",
    "@react-native-async-storage/async-storage": "^1.13.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "dd-sdk-reactnative": "^1.0.0-alpha5",
    "expo": "~41.0.1",
    "expo-app-loading": "^1.0.3",
    "expo-location": "~12.0.4",
    "expo-notifications": "~0.11.6",
    "expo-sms": "~9.1.2",
    "expo-status-bar": "~1.0.4",
    "expo-task-manager": "~9.1.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-elements": "^3.4.1",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-web": "~0.13.12",
    "tailwind-rn": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "typescript": "~4.0.0"
  },
  "private": true
}
```

**Comment by buranmert** [comment]
hi @agjini 👋 
your error message is very similar to [this issue](https://github.com/DataDog/dd-sdk-reactnative/issues/41)
can you please try to change `Library Search Paths` build setting as described in the original issue?

let me know if that works for you

**Comment by agjini** [comment]
Thank you for your reply.

The problem is that I'm using expo build system : and the xcode environment is configured on their servers.
I think I cannot change the library path in this environment.

I'm totally noob in XCODE development but do you have an explanation why the default library path cannot be used for dd-sdk ?

thanks

**Comment by flexbox** [comment]
Hey @agjini 
Do you have an update with your issue? 

I am trying to add Datadog to our **React Native Managed Workflow** app —and before jumping on `eas-cli` / refactoring our entire build system— I am looking for inputs 🙂

**Comment by agjini** [comment]
Hello @flexbox,
I have no update on this. I've not tried a newer version of the library.
I've asked the expo team (from discord) but they did not get any issue fixed.
Maybe it would be nice to try again now.
For the moment we have completely disabled datadog rum from our expo app.

**Comment by xgouchet** [comment]
Hi @flexbox , @agjini , 
We indeed still need to work out a solution to make our Datadog SDK compatible with Expo's managed framework, but we can't provide any time yet on when this will be available

**Comment by flexbox** [comment]
@xgouchet Thanks for the input
I think I will investigate the sentry x datadog integration as a quick win 
https://docs.datadoghq.com/integrations/sentry/

I have no logging system at the moment so no idea of users crashing rates 🙈

**Comment by zlanich** [comment]
I too desperately want to get DataDog working in Expo Managed Workflow. We're currently using Sentry for everything, but DataDog's offering is SO much richer, and my company is in the process of completely rethinking our web/mobile app infrastructure, including Monitoring/Telemetry. I would love to try out DataDog, but we currently build all of our mobile apps on Expo MW (unless we have to eject).

+1 !

**Comment by brookemitchell** [comment]
As a follow-up, we've had this working well in the Expo Managed workflow, our only challenge was testing locally. 

https://github.com/DataDog/dd-sdk-reactnative/issues/78#issuecomment-1009424507

**Comment by priyanshi-gupta** [comment]
Hey folks, I'm the PM for RUM at Datadog, thank you for the feature request. We're investigating integration with Expo managed workflow and we would love to get insights on your experience. If you're open to a quick chat, please reach out support@datadoghq.com and mention this issue.

**Comment by louiszawadzki** [comment]
Hi all,
We now support Expo managed workflow, you can learn about how to enable our SDK with Expo here: https://github.com/DataDog/dd-sdk-reactnative/blob/develop/docs/expo_development.md
If you are using Expo Go, you'll find instructions on how to move to development builds or to prevent your app from crashing with the SDK while using Expo Go.

I'm closing this issue, feel free to open a new one if the documentation is missing something :)
