### ISSUE TITLE
Question - not initializing or configuring Datadog for a development environment

### ISSUE THREAD

**Issue by mfelix5** [DataDog/dd-sdk-reactnative#475]
Hello, I am in the process of updating dd-sdk-reactnative from version 1.1 to 1.6. Part of that process is moving from the older initializeDatadog() pattern to the new DatadogProvider. I do not want to use Datadog in our 'development' environment and so in the old pattern we just didn't initialize it for that env. However it seems that using the provider, Datadog will always be initialized. Is that correct? 

If so, I assume that our config should look something like this:

```
const isDev = Config.STAGE === "development";

const config = new DatadogProviderConfiguration(
    Config.DATADOG_RUM_CLIENT_TOKEN,
    Config.STAGE,
    Config.DATADOG_RUM_APPLICATION_ID,
    !isDev, // track user actions 
    !isDev, // track XHR Resources
    !isDev, // track Errors
  );

  config.site = "US1";
  config.nativeCrashReportEnabled = !isDev;
  config.sessionSamplingRate = isDev ? 0 : 100;
```

Am I missing anything here?

**Comment by louiszawadzki** [comment]
Hi @mfelix5, 

Indeed this is not yet supported, I'll add it to our backlog.

`config.sessionSamplingRate = isDev ? 0 : 100;` by itself should be enough to make sure no RUM event is sent in dev mode in the meantime.

**Comment by mfelix5** [comment]
Thank you @louiszawadzki!
