### ISSUE TITLE
Crash when logging object with enumerable and non-configurable property

### ISSUE THREAD

**Issue by stevoland** [DataDog/dd-sdk-reactnative#479]
**Describe what happened**

Sent an instance of `GraphQLError` ([graphql@14](https://github.com/graphql/graphql-js/blob/v14.5.8/src/error/GraphQLError.js#L86)) to the logger and experienced a crash.

Reduced the minimal test case to:

```ts
const context = {}

Object.defineProperty(context, 'boom', {
  value: 'boom',
  enumerable: true,
  configurable: false // No crash if true
})

DdLogs.info('Boom', context)
// Same also with DdRum.addError(...)
```

and receive these errors

```
Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.

[[46,49,80,46],[1,0,1,0],[[20],[8,8,{"iterations":1,"toValue":1,"frames":[0,0.008888888888888889,0.035555555555555556,0.08000000000000002,0.14222222222222222,0.2222222222222222,0.32000000000000006,0.4355555555555556,0.5644444444444444,0.6799999999999999,0.7777777777777777,0.8577777777777778,0.92,0.9644444444444444,0.9911111111111112,1],"type":"frames"},637],[21,100,1684328154277,false]],317]
Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.

[[46,49,80,46],[1,0,1,0],[[20],[8,8,{"iterations":1,"toValue":1,"frames":[0,0.008888888888888889,0.035555555555555556,0.08000000000000002,0.14222222222222222,0.2222222222222222,0.32000000000000006,0.4355555555555556,0.5644444444444444,0.6799999999999999,0.7777777777777777,0.8577777777777778,0.92,0.9644444444444444,0.9911111111111112,1],"type":"frames"},637],[21,100,1684328154277,false]],317]
    at nativeFlushQueueImmediate (native)
```

**Steps to reproduce the issue:**

Checkout branch of test app https://github.com/DataDog/dd-sdk-reactnative/compare/develop...stevoland:non-configurable-crash

Run example app in ios simulator

Tap "Crash on log"

**Describe what you expected:**

**Additional context**

-   Version of the SDK: 1.6.0
-   Version of React Native: 0.69.4, 0.71.2

**Comment by louiszawadzki** [comment]
Hi @stevoland, thanks for reaching out!

I'm able to reproduce the issue in debug mode (it does not seem to crash for release versions).
From what I understand, the conversion of the object with such properties by React Native is failing silently, and so we don't attach send any parameter for the `DdLogs.info` native call - see [this SO post for more detailed explanations](https://stackoverflow.com/questions/55084493/malformed-calls-from-js-field-sizes-are-different/67100389#67100389).

Trying to make our SDK work better for all the cases that RN cannot handle is on our backlog, but it won't be tackled soon.
We're also working on a GraphQL integration that is likely to be released earlier :) 

In the meantime I would recommend to try to "manually" rebuild an object from the GraphQL error object with the fields you're interested in, to make sure it doesn't have any non-configurable property.


Let me know if that works for you :)

**Comment by stevoland** [comment]
Hi @louiszawadzki, thanks for the link. We are now sanitising data passed to DdLogs via `lodash.cloneDeep`.

I thought I would raise it but of course not a priority at all. (Don't you have any spoilers for the graphql integration? Very exciting!)

**Comment by stevoland** [comment]
Duplicate of https://github.com/DataDog/dd-sdk-reactnative/issues/357
