### ISSUE TITLE
actionNameAttribute support for tracking user actions

### ISSUE THREAD

**Issue by akinzalowevidation** [DataDog/dd-sdk-reactnative#490]
**Describe the solution you'd like**

Would it be possible to add support for `actionNameAttribute` which can be seen in browser rum documentation [here](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/#declare-a-name-for-click-actions). We would like to tie action names to `testID`'s.

**Describe alternatives you've considered**

We have considered writing a utility function to pass both `testID` and `data-dd-action-name` to a component, but it would be nice to avoid having to do `{...getTestID("blah")}` every time as add an id.

**Comment by louiszawadzki** [comment]
Hi @akinzalowevidation, thanks for reaching out!

This sounds like a good addition, we've added it to our backlog and I'll let you know once it's released :)

**Comment by louiszawadzki** [comment]
Hi @akinzalowevidation,

I'll close this issue since this has been released in SDK version `1.8.0` :)
