### ISSUE TITLE
RN-0.73 change Android configs for RN 0.73 compatibility

### ISSUE THREAD

**Issue by eppisapiafsl** [DataDog/dd-sdk-reactnative#493]
**Is your feature request related to a problem? Please describe.**

React Native 0.73 will depend on Android Gradle Plugin (AGP) 8.x. This will require all the libraries to specify a namespace in their build.gradle file.

App/Library Developers will now have to install and use [Java 17](https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp)
Specify a namespace in [their build.gradle file](https://developer.android.com/build/releases/gradle-plugin#namespace-dsl).
Specifically, the last change is a breaking change and will make libraries that are not specifying a namespace incompatible with React Native 0.73

**Describe the solution you'd like**

Update their android/build.gradle file as follows:

```
android {
   namespace = "com.datadog.reactnative"
    ...
}
```
and remove the package definition from their AndroidManifest.xml:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
</manifest>
```

**Additional context**

Further reading

[Official Google documentation on namespaces is here](https://developer.android.com/build/configure-app-module#set-namespace).

**Comment by louiszawadzki** [comment]
Hi @eppisapiafsl, thanks a lot for reaching out!

We've seen this change coming as well :) But we're still waiting a bit before making it.

Unfortunately this change is going to break compatibility with RN versions below 0.71: https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1597368831
Either a backward compatible solution will exist when 0.73 is out, or we need to release a new major version specifically targeting RN >= 0.71.

We always test React Native release candidates in any case, so rest assured that when 0.73.0 is out this will be supported :)

**Comment by FelipeSSantos1** [comment]
Hi @louiszawadzki  looks like the community found [a solution](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1604910280) to keep the compatibility. Could you let us know whats the DataDog team plan for deal with that, since RN 0.73 is the next major release?

**Comment by louiszawadzki** [comment]
Hi @felipemillhouse!

Our plan is to address it as soon as the first release candidate for RN 0.73 is released. There might be other breaking changes for us in RN 0.73, and we want to avoid releasing a version only partially supporting RN 0.73 for clarity.

I hope this makes sense, in any case let me know if there is a need on your side to get this out sooner.
