### ISSUE TITLE
Feature Request: React 17 Support

### ISSUE THREAD

**Issue by garrettreed** [DataDog/dd-sdk-reactnative#50]
**Describe the solution you'd like**
We would like to use this in our project that has upgraded to React 17. Is this being considered for the public release?

**Additional context**
I was able to upgrade to v17.0.1 with passing tests. However, I had to keep `react-test-renderer` at `^16.13.1` due to this issue: https://github.com/react-navigation/react-navigation/issues/9023

**Comment by 0xnm** [comment]
Hello @garrettreed! Sorry for the late reply. You shouldn't have any issues with React 17 with our latest `1.0.0-beta3` version. Please let us know otherwise.

**Comment by nbielak** [comment]
Hello @0xnm I am still running into this issue with a new app using `npx react-native init`. I have specified versions of the following packages:

React: `17.0.2`, 
 "react-dom": "17.0.2",
`react-native`: `0.66.0`,
'dd-sdk-reactnative`: `1.0.0-beta3`

Error output:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@"*" from @react-navigation/native@5.9.8
npm ERR!   node_modules/@react-navigation/native
npm ERR!     peer @react-navigation/native@"^5.6.0" from dd-sdk-reactnative@1.0.0-beta3
npm ERR!     node_modules/dd-sdk-reactnative
npm ERR!       dd-sdk-reactnative@"^1.0.0-beta3" from the root project
npm ERR!   1 more (react-native)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from dd-sdk-reactnative@1.0.0-beta3
npm ERR! node_modules/dd-sdk-reactnative
npm ERR!   dd-sdk-reactnative@"^1.0.0-beta3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

```

I tried the force command as stated in the error but that did not work either.

**Comment by 0xnm** [comment]
Hello @nbielak. Package `dd-sdk-reactnative` is deprecated, please use [@datadog/mobile-react-native](https://www.npmjs.com/package/@datadog/mobile-react-native) instead - this is a core package, individual integrations can be found [here](https://www.npmjs.com/package/@datadog/mobile-react-native-navigation) and [here](https://www.npmjs.com/package/@datadog/mobile-react-navigation).

If error is still present, please show us the output with `legacy-peer-deps` flag.
