### ISSUE TITLE
no frustration signal reported on any view (iOS/ Android)

### ISSUE THREAD

**Issue by AleCatSS** [DataDog/dd-sdk-reactnative#506]
Hello,
I am are currently trying to measure frustration signals on our application (iOS/Android). Following the docs [here](https://docs.datadoghq.com/real_user_monitoring/reactnative/advanced_configuration/#initialization-paramaters) both 'trackInteractions' and 'trackFrustrations' are enabled, however in the Frustration Signals Dashboard I don't see any data, in particular 'RAGE/DEAD CLICKS PER VIEW' are always 0.

Given the number of sessions we currently have in production we find it very odd to not have any frustration signals and we were wondering if the measurement is currently working properly.

We tried to generate few 'rage clicks' by replacing the onPress listener on a button with an arrow function and spamming clicks over it but nothing shows up in the dashboard (please let me know if there is a correct/better way to test this).

**Steps to reproduce the issue:**

1. Initialize DataDog SDK with trackInteractions: true and trackFrustrations: true;
2. add a button with an empty onPress handler to a view and spam more then 3 taps per seconds on it;
3. observe the Frustration Signals Dashboard: no rage/dead click is reported

**Describe what you expected:**

observe rage/dead click in the Frustration Signals Dashboard

**Additional context**

-   Version of the SDK:

"@datadog/mobile-react-native": "1.5.2",
"@datadog/mobile-react-navigation": "1.5.2"

-   Version of React Native:

react-native": "0.70.10

**Comment by louiszawadzki** [comment]
Hi @AleCatSS, thanks for reaching out!

On mobile SDKs we currently only support error taps: when a user taps on an element right before a JavaScript error occurs.

Rage clicks and dead clicks are not supported yet on mobile, thanks for pointing out that it's not clear in our documentation, I'll edit it to reflect this better!

**Comment by AleCatSS** [comment]
Hello @louiszawadzki,
thank you for the clarification.
