### ISSUE TITLE
CI Visibility integration

### ISSUE THREAD

**Issue by stevoland** [DataDog/dd-sdk-reactnative#507]
Hi, wondering if support for this is on the roadmap?

Or if it might possibly be achievable now by setting `ciTest` on the `context` in event mappers?

Thanks!

**Comment by plousada** [comment]
Hi @stevoland, you should be able to achieve integration with CI visibility provided you use `jest-environment-node`.

Did you encounter any particular issues?

**Comment by stevoland** [comment]
Sorry I should have been clearer. I'm referring to end-to-end tests of an RN app (in our case with wdio/cucumber) and linking the test run in DD with the RUM session (and APM traces) as seems to be supported by the browser SDK https://www.datadoghq.com/blog/ci-test-visibility-with-rum/#get-the-rum-perspective-on-your-ci-test-performance.

I presume this requires linking the test run id with the RUM session somehow. Each of our test runs opens the app via deep link so passing an ID through would be fine if this SDK supported adding that id to the RUM events.

(RUM seems to have 3 possible session types: User, Synthetic and CI Test and I'm referring to supporting CI Test sessions with this SDK)

**Comment by plousada** [comment]
Hi @stevoland, unfortunately we don't have this feature yet widely available on both Android and iOS Mobile SDKs so we can't leverage it for our RN SDK. It's also not in our immediate roadmap.
Changing it on the event mappers wouldn't work as we don't allow the override of session type there. 

Would you mind opening up a Feature Request together with your customer success manager so we can evaluate the priority of the feature?

**Comment by stevoland** [comment]
Thanks for your time, will do
