### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Solid-Metal** [DataDog/dd-sdk-reactnative#51]
hello everyone, sorry for the newb question

i always got crash on startup when tried to import this SDK, its a debug apk, what is the minimum react-native need to use it ?

heres react-native version that we use
react-native-cli: 2.0.1
react-native: 0.60.5

already tried to look at logcat but theres seems no unusual problem popup

thank you in advance

**Comment by 0xnm** [comment]
Hello @Solid-Metal. We recommend using `0.63.4` as it is declared in the `peerDependencies`: https://github.com/DataDog/dd-sdk-reactnative/blob/009f5370097f52b697e909c0ddab7105666259c8/package.json#L68. If you have a crash, please provide stacktrace, this would be very helpful.

**Comment by Solid-Metal** [comment]
thanks for the answer, unfortunately theres no stacktrace, the app just crash, and theres nothing wrong as well on the debug log, so i'm not really sure what happen

i'll try to update to RN 0.63.4

thanks again !

**Comment by xgouchet** [comment]
Hi @Solid-Metal , did upgrading to RN `0.63.4` fix the issue?

**Comment by Solid-Metal** [comment]
> Hi @Solid-Metal , did upgrading to RN `0.63.4` fix the issue?

good evening, sorry for late response, i only tried it for just a moment and it seems fine, and nothing crashed iirc, but not fully tested yet since transition from 0.60 to 0.63.4 min is quite hefty at the moment cause of the amount of unmaintained lib that we used, we're still on progress on updating it

**Comment by xgouchet** [comment]
I'm going to close this issue, but feel free to reopen it if you notice a crash, or open a new issue if something else happens.
