### ISSUE TITLE
Large performance hit if using custom `actionEventMapper`

### ISSUE THREAD

**Issue by justinadkins** [DataDog/dd-sdk-reactnative#514]
**Describe what happened**
We noticed that our applications felt sluggish when using DD RUM with user interaction tracking enabled. We then noticed if we disabled our custom `actionEventMapper` the sluggishness went away. Tracing the code lead me [here](https://github.com/DataDog/dd-sdk-reactnative/blob/develop/packages/core/src/sdk/EventMappers/EventMapper.ts#L76). 

This `deepClone` is adding an additional 50 - 250ms to every action event! 💀 That's a huge penalty for using a custom mapper. 

**Steps to reproduce the issue:**
1. Enable user interaction tracking and add a custom `actionEventMapper`
2. Track time to complete simple `onPress` handler

Compare with implementation where custom `actionEventMapper` configured.

**Describe what you expected:**
I expect no additional performance impact when adding a custom `actionEventMapper` outside of what is added by the mapper itself.

**Comment by louiszawadzki** [comment]
Hi @justinadkins, thanks for reaching out!

We can reproduce some slowness in the `actionEventMapper`, I apologize for this.

I've already identified ways to make the `deepClone` function faster, I'm investigating into how far we can go and will make a pull request soon.

I will let you know once the PR is opened so you can patch the SDK on your end without having to wait for the release.

Thank you again for reporting this.

**Comment by louiszawadzki** [comment]
Hi @justinadkins, 

This has been fixed in release `1.8.3`. 
The release will be promoted to `latest` in a few weeks and is already safe to use as the changes in this one are quite minimal :) 

I'm closing the issue, feel free to reopen if you experience any further performance issue with this version!
