### ISSUE TITLE
TypeError: Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by simistern** [DataDog/dd-sdk-reactnative#52]
**Describe what happened**
When installing `dd-sdk-reactnative` and following the installation instructions, I am seeing an error

```
TypeError: Cannot read property 'initialize' of undefined
    at DdSdkReactNative.tsx:38
    at new Promise (es.promise.js:235)
    at Function.initialize (DdSdkReactNative.tsx:30)
    at initializeDDSdk$ (LoggingProvider.tsx:16)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:189
```

**Steps to reproduce the issue:**
1. `yarn add dd-sdk-reactnative`
2. follow instructions to initialize as here: 

```
import { DdSdkReactNative, DdSdkReactNativeConfiguration } from 'dd-sdk-reactnative';

const config = new DdSdkReactNativeConfiguration(
    "<TOKEN>", 
    "<ENVIRONMENT_NAME>", 
    "<TOKEN>", ,
    true, // track User interactions (e.g.: Tap on buttons)
    true, // track XHR Resources
    true // track Errors
)
DdSdkReactNative.initialize(config)
```
**Describe what you expected:**
Instrumentation to connect to datadog backend

**Additional context**
    - Version of the SDK: `"dd-sdk-reactnative": "^1.0.0-beta1",`
    - A copy of your `package.json` file: 
```
     "react": "16.13.1",
      "react-native": "0.63.4",
```

**Comment by 0xnm** [comment]
Hello @simistern! Thanks for reporting the issue. Is app made with [Expo](https://expo.io/) by any chance? Do you experience that issue on both iOS and Android or only on one of them?

**Comment by kylesurowiec** [comment]
Also experiencing this issue on iOS, using a bare expo app. We only support iOS so I can't speak for Android.

**Comment by 0xnm** [comment]
We don't support Expo flows currently, but we will address this issue soon.

**Comment by simistern** [comment]
> Hello @simistern! Thanks for reporting the issue. Is app made with [Expo](https://expo.io/) by any chance? Do you experience that issue on both iOS and Android or only on one of them?

The app isn't made with expo, and we are experiencing it on android as well unfortunately.

**Comment by 0xnm** [comment]
@simistern I tried to reproduce the problem with a fresh React Native project (doing `npx react-native init`), but it works fine for me. By looking on the stacktrace it seems like native modules cannot be initialized correctly. Can you please check if there are any other related errors/warnings in the logs?

I would also recommend to try `npx react-native unlink dd-sdk-reactnative` and linking it back (normally things should be linked automatically, but maybe something didn't work, more info here https://reactnative.dev/docs/linking-libraries-ios and here https://github.com/react-native-community/cli/blob/master/docs/autolinking.md), and maybe removing `node_modules` and installing packages again.

**Comment by 0xnm** [comment]
Hello @simistern. We didn't hear from you back on this issue, so closing it. In the meantime we've released `beta3` with a couple of fixes, so you may want to try it.

**Comment by danlupascu** [comment]
We're having this issue as well, same exact issue, we just followed the website instructions.

**Comment by 0xnm** [comment]
@danlupascu Please open a new issue if it is the case with the necessary details (SDK version, React Native version, etc.)
