### ISSUE TITLE
Expose a way to get the Session Id

### ISSUE THREAD

**Issue by JIGsaw133** [DataDog/dd-sdk-reactnative#521]
It looks like there'a way to get the session id through the web SDK but I couldn't find a similar way to get it from reactNative. I need it for the same purpose as the web app, to allow the user to contact us when they're encountering a problem.

https://github.com/DataDog/browser-sdk/issues/390

- can you please expedite on this would help us to allow know exact user session where they faced the issue.

**Comment by JIGsaw133** [comment]
or if there is anything workaround to fetch the session id.

**Comment by louiszawadzki** [comment]
Hi @JIGsaw133, thanks for reaching out!

This feature is currently in our backlog. If this is urgent for you, please reach out through [our support team](https://www.datadoghq.com/support/) so we can better assess the priority of this feature.

In any case, I will let you know in this issue when this is available.

**Comment by jheurtin** [comment]
I'm adding a thumbs up here !
It would be really great to access this sessionId.

In the meantime, is their a way to set-up our own ID at the initialisation of the client ?

**Comment by louiszawadzki** [comment]
Hi @jheurtin, 

We don't enable setting up your own ID, and likely won't be supported soon as we would need to support all the possible session creation scenarios for this as well.
Exposing the current session Id is still in our backlog, I'll bump it :) 

If you do have a particular use case for this I'm curious as well, this can help us design the feature better.

Thanks a lot!

**Comment by amol-chaudhari-cerebral** [comment]
We are in need of the same feature as well. Any updates on exposing the session id?

**Comment by HishamOmran** [comment]
Are there any updates on this? 🙏

**Comment by marcosaia** [comment]
@JIGsaw133 @amol-chaudhari-cerebral @HishamOmran @jheurtin 

Hello there! :wave:

We are currently working on exposing the session ID on React Native, and it will soon be released.

You can follow the progress of the PR here: https://github.com/DataDog/dd-sdk-reactnative/pull/662

**Comment by marco-saia-datadog** [comment]
@JIGsaw133 @amol-chaudhari-cerebral @HishamOmran @jheurtin 

Hello there! :wave:

We are currently working on exposing the session ID on React Native, and it will soon be released.

You can follow the progress of the PR here: https://github.com/DataDog/dd-sdk-reactnative/pull/662

**Comment by marco-saia-datadog** [comment]
@JIGsaw133 @amol-chaudhari-cerebral @HishamOmran @jheurtin 

Hello 👋 

We have exposed a method to retrieve the Session ID with [our latest release v2.3.5](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.3.5).

I will close this issue, feel free to re-open it if you encounter any problems!
