### ISSUE TITLE
`datadog-ci` should be dependency?

### ISSUE THREAD

**Issue by bhy** [DataDog/dd-sdk-reactnative#524]
**Describe what happened**
After integrating datadog my expo eas build failed. The Android build has error message:
```
Exception raised during command execution, stderr=error Command "datadog-ci" not found.
```

The iOS build has error message:
```
line 30: ../node_modules/.bin/datadog-ci: No such file or directory
```

**Describe what you expected:**

Builds to success

**Additional context**

-   Version of the SDK: 1.8.3
-   Version of React Native: 0.72.4
-   Version of Expo: 49
-   Build is managed by Expo EAS.

**Comment by louiszawadzki** [comment]
Hi @bhy, thanks for reaching out!

From the error you are reporting, you should indeed be adding `datadog-ci` as a dev dependency. If you want to enable the expo config-plugin you need to have this dependency: https://docs.datadoghq.com/real_user_monitoring/reactnative/expo/#add-the-config-plugin

However, I understand that the "[Usage](https://docs.datadoghq.com/real_user_monitoring/reactnative/expo/#usage)" part of our documentation is misleading as adding the config plugin without `datadog-ci` would indeed make EAS build fail like yours.
I will edit the documentation to make it clearer.

The `datadog-ci` dependency is only needed as a dev dependency to your project if you want to upload your sourcemaps to Datadog. Adding it as a direct dependency would make it a direct dependency of every project using `@datadog/mobile-react-native`, which would also mean that its code would be bundled into the RN application.

Let me know if that answers your questions and solves your issue :)

**Comment by bhy** [comment]
@louiszawadzki thank you so much! This clarified my question and works perfectly for me!
