### ISSUE TITLE
Problem to integrate version 1.8.4

### ISSUE THREAD

**Issue by Francesco-Voto** [DataDog/dd-sdk-reactnative#529]
**Describe what happened**
Hello,

I am currently trying to integrate the latest version of the lib (1.8.4) in my project.

Anyway I am having some issue whit Pod: this is the message

```
The Swift pod `DatadogSDKReactNative` depends upon `React-Fabric`, `React-graphics`, `React-utils`, and `React-debug`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

```

Unfortunalety it looks like I cannot use `use_modular_headers` globally

The problem doesn't occur if I downgrade to the version 1.7.1

We currently have both Fabric and Hermes enabled and we have `ENV['RCT_NEW_ARCH_ENABLED'] = "1"` in our PodFile

Any ideas? thanks

**Steps to reproduce the issue:**
Integrate the lib

**Describe what you expected:**

The build has not problem

**Additional context**

-   Version of the SDK: 1.8.4
-   Version of React Native: 0.72.4

**Comment by louiszawadzki** [comment]
Hi @Francesco-Voto, thanks for reaching out!

There is indeed an issue with building our SDK with the new architecture enabled in RN 0.72.4.

The specificity of our SDK is that it uses Swift files on iOS, which is not automatically tested in RN versions.
We detected the issue in RN 0.72.0, made a fix for this issue that landed in RN 0.72.2, but it created other issues for other users and so it was reverted soon after in 0.72.3 ([that's even the only change in this version](https://github.com/facebook/react-native/releases/tag/v0.72.3)).

We tried to come up with a solution that would work for everyone, but unfortunately it's not straightforward to fix it for everyone without making larger (and riskier) changes. 
Furthermore these problems should be solved with other big changes that should land in RN 0.73, so it's not even sure we could deploy these changes in a patch version of RN 0.72.

My recommandation would be to apply [this commit](https://github.com/facebook/react-native/commit/a4a065549677c61eb91bf587032976ed48c75821) as a patch for React Native in your project.
All this does is specifying that RN pods define modules when this was forgotten. 
You can even skip the change for `glog` in `packages/react-native/scripts/react_native_pods.rb` if you can do without it, as this was the change that generated issues in some cases and `glog` does not appear in the list of problematic pods in your error message. 

Alternatively, you could downgrade to RN 0.72.2, but in that case you would lose the added fixes and features from 0.72.4.


Let me know if either of these two solutions can work for you!

**Comment by Francesco-Voto** [comment]
Thanks for reaching me @louiszawadzki 

At the moment I should have fix adding something similar to the patch to suggest to my pod file

```
  pod 'React-Fabric', :modular_headers => true, :path => '../node_modules/react-native/ReactCommon'
  pod 'React-graphics', :modular_headers => true, :path => '../node_modules/react-native/ReactCommon/react/renderer/graphics'
  pod 'React-utils', :modular_headers => true, :path => '../node_modules/react-native/ReactCommon/react/utils'
  pod 'React-debug', :modular_headers => true, :path => '../node_modules/react-native/ReactCommon/react/debug'
```

thanks again

**Comment by Francesco-Voto** [comment]
I think we can close this: we are currently using 2.0.4 without problems

Thanks again
