### ISSUE TITLE
startTrackingViews function not triggering any RUM sessions from Test Flight build

### ISSUE THREAD

**Issue by millro04** [DataDog/dd-sdk-reactnative#55]
**Describe what happened**
I have everything working locally in the iOS Simulator and can see sessions in the RUM explorer and can also see logs. However, after I deploy the app to Test Flight and download on my phone, it doesn't look like any sessions are being tracked. I have verified that my configuration is correct. Are there any differences that could be causing this? Any settings that could be preventing the network call to Datadog from being sent from my device?

It's odd that everything works perfectly locally, but can't get anything to work from my device with a Test Flight build.

**Steps to reproduce the issue:**
Upload a working example to TestFlight and download on a device.

**Describe what you expected:**
Expected the same behavior as locally on the iOS simulator - calling startTrackingViews should cause a new session to appear in the RUM explorer.

**Additional context**
   package.json file:
```
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.11.4",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "axios": "^0.21.1",
    "color": "^3.1.3",
    "dd-sdk-reactnative": "^1.0.0-beta1",
    "formik": "^2.2.6",
    "immutability-helper": "^3.1.1",
    "lodash.filter": "^4.6.0",
    "react": "16.13.1",
    "react-moment": "^1.1.1",
    "react-native": "0.63.4",
    "react-native-config": "^1.4.1",
    "react-native-elements": "^3.1.0",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loading-spinner-overlay": "^2.0.0",
    "react-native-modal": "^11.6.1",
    "react-native-paper": "^4.8.1",
    "react-native-reanimated": "^1.13.3",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.16.1",
    "react-native-sensitive-info": "^6.0.0-alpha.9",
    "react-native-vector-icons": "^7.1.0",
    "react-redux": "^7.2.2",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "styled-components": "^5.2.3",
    "tailwind-rn": "^3.0.1",
    "yup": "^0.32.8"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "detox": "^18.0.2",
    "eslint": "^7.16.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-detox": "^1.0.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-sort-keys-fix": "^1.1.1",
    "jest": "^26.6.3",
    "jest-circus": "^26.6.3",
    "metro-react-native-babel-preset": "^0.59.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by 0xnm** [comment]
Hello @millro04. It shouldn't be any difference from library perspective when deployed on simulator vs real device. I would suggest checking things like release app configuration, bundle content, ISP connectivity/resolution of Datadog host, etc. Do you experience this only on iOS or Android is affected as well?

**Comment by devproivansurzhenko** [comment]
@0xnm 

I am experiencing similar things at simulator build (did not test it on real device yet).

What I can provide from my end?

**Comment by 0xnm** [comment]
Hello @devproivansurzhenko! Does it happen on iOS only or on Android as well? If you have any console logs, this would be useful. Also does it happen only with RUM sessions or you don't have Logs reported as well?

**Comment by devproivansurzhenko** [comment]
Hey-hey-hey... it is interesting... I just tried to follow your recommendation to check `Logs` (never did that before) and things started to work after my visit to the Page. So, now everything on iOS simulator is working as expected (My code is not runnable on Android yet)

Context for times while i had issues: I attempted to register my first RUM app. So, I even did not finish the flow of registration just because DD did not "saw" the user sessions.

There is no specific console outputs. Everything what i know `DdSdkReactNative.initialize` and `DdSdkReactNative.setUser` promises did finish with success

**Comment by 0xnm** [comment]
@devproivansurzhenko RUM session will start once any view is started and it can be done in the following ways:

* if you are using [React Navigation](https://reactnavigation.org/) package, you can enable automatic view tracking as described here https://github.com/DataDog/dd-sdk-android/pull/504
* otherwise you need to track view manually with `DdRum#startView` and `DdRum#stopView` methods.

**Comment by 0xnm** [comment]
Hello @millro04 Since there is no update from you, I'm closing this issue. Feel free to re-open if needed.
