### ISSUE TITLE
Can't upgrade to version 2.0.0

### ISSUE THREAD

**Issue by ghost** [DataDog/dd-sdk-reactnative#553]
**Describe what happened**

I can't upgrade to version 2.0.0.

Failing with this message

```sh
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @datadog/mobile-react-navigation@2.0.0
npm ERR! Found: @datadog/mobile-react-native@2.0.0
npm ERR! node_modules/@datadog/mobile-react-native
npm ERR!   @datadog/mobile-react-native@"2.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @datadog/mobile-react-native@"^1.0.0-beta4" from @datadog/mobile-react-navigation@2.0.0
npm ERR! node_modules/@datadog/mobile-react-navigation
npm ERR!   @datadog/mobile-react-navigation@"2.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @datadog/mobile-react-native@1.9.0
npm ERR! node_modules/@datadog/mobile-react-native
npm ERR!   peer @datadog/mobile-react-native@"^1.0.0-beta4" from @datadog/mobile-react-navigation@2.0.0
npm ERR!   node_modules/@datadog/mobile-react-navigation
npm ERR!     @datadog/mobile-react-navigation@"2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Maybe the peer dependency needs to be updated too.
https://github.com/DataDog/dd-sdk-reactnative/blob/cbf402ae85f73b4ee9a8091ceb1310b35d7318f9/packages/react-native-navigation/package.json#L47

**Steps to reproduce the issue:**

In the `package.json` update Datadog dependencies

```
    "@datadog/mobile-react-native": "2.0.0",
    "@datadog/mobile-react-navigation": "2.0.0",
```

run `npm install`

**Describe what you expected:**

Datadog packages are upgraded without error.

**Additional context**

-   Version of the SDK: 2.0.0
-   Version of React Native: 0.72.6

**Comment by louiszawadzki** [comment]
Hi @lgassense, thanks for catching this!

Indeed there is an error in the `package.json`. I apologize, we only run our release flow using `yarn` and missed that one.
I'll make a quick release to fix this, and look at how we can automate the peer dependency update for the release after that.

In the meantime, I can suggest a few ways to unblock you.
Perhaps the best is to force the version of `@datadog/mobile-react-native` to the one specified in your `package.json` by adding an `"overrides"` field in your `package.json` ([docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)):

```json
{
  "overrides": {
    "@datadog/mobile-react-native": "$@datadog/mobile-react-native"
  }
}
```

You can also run `npm install --legacy-peer-deps`,  at the risk of potentially missing a real peer dependency issue.

I'll get back to you when `2.0.1` is ready.

**Comment by ghost** [comment]
Thanks @louiszawadzki for the quick response

**Comment by louiszawadzki** [comment]
Hi @lgassense, 

Thanks again for taking the time to report the issue :) 
Version `2.0.1` has been released, containing the fix to the issue. 

I'll close the GitHub issue, feel free to reopen it if needed!
