### ISSUE TITLE
Real user monitoring for a ReactNative app inside a native iOS app

### ISSUE THREAD

**Issue by hamidhadi** [DataDog/dd-sdk-reactnative#556]
We have a native iOS app which has couple of screens in ReactNative.
How can we setup the real user monitoring for this project?

**Comment by louiszawadzki** [comment]
Hi @hamidhadi, thanks for reaching out!

We have a dedicated guide for this use case here: https://github.com/DataDog/dd-sdk-reactnative/blob/develop/docs/hybrid_applications.md.

You can also find a sample iOS application with RN screens instrumented here: https://github.com/DataDog/dd-sdk-reactnative-examples/tree/main/ios-app-with-rn.

I'll close this issue for now, please feel free to reopen it if anything is unclear in the documentation so we help you and improve it :)
