### ISSUE TITLE
Android build error in 2.0.1 - stackoverflowerror

### ISSUE THREAD

**Issue by AZagatti** [DataDog/dd-sdk-reactnative#565]
**Describe what happened**

When migrating to version 2.0.1 and configuring it as per the migration guide, my teammates and I encountered a StackOverflowError while attempting to build the Android app using Java. Any suggestions on how to resolve this issue?

**Steps to reproduce the issue:**

Upgrade the SDK.

**Describe what you expected:**

![image](https://github.com/DataDog/dd-sdk-reactnative/assets/40201172/5921c3e3-b8c3-4c50-95d9-0a589cdf788d)

**Additional context**

-   Version of the SDK: 2.0.1
-   Version of React Native: 0.71.8
-   `package.json`
-   `Podfile` and `Podfile.lock`
-   `android/build.gradle` and `android/app/build.gradle`

**Comment by flochtililoch** [comment]
Could you update your issue description with an actual copy/paste of the text (so it's searchable) that contains the entire error (right now the screenshot cuts out most of the useful information). Thanks!

**Comment by AZagatti** [comment]
Is there a flag to generate the log? It just keeps repeating this and cuts off in the terminal

**Comment by louiszawadzki** [comment]
Hi @AZagatti, thanks for reaching out!

To help us troubleshoot this issue could you share the following files:
- `android/build.gradle`
- `android/app/build.gradle`
- `android/gradle.properties`
- `android/settings.gradle`

Or if you can share a simple project reproducing the error that would work as well :) 

Also can you attach the full log as @flochtililoch mentioned? 
Maybe you can get it by just running the gradle command: `(cd android && ./gradlew assembleRelease)`.


Thanks a lot!

**Comment by louiszawadzki** [comment]
Hi @AZagatti,

There has not been any activity on this issue for a while so I'm going to close it.

Feel free to reopen it with more details if you still encounter the problem :)
