### ISSUE TITLE
[Question] How Datadog process logs in case of no-internet connection?

### ISSUE THREAD

**Issue by whalemare** [DataDog/dd-sdk-reactnative#566]
All logs stored in database and wait for connection appear? Or just ignored it all?

**Comment by xgouchet** [comment]
Hi @whalemare , as mentioned in [our documentation](https://docs.datadoghq.com/logs/log_collection/reactnative/#batch-collection), all our mobile SDKs (including React Native) will store the data in the local storage and try to upload them as soon as the network connection becomes available. Our goal is to avoid losing data as much as possible.
