### ISSUE TITLE
App Tracking Transparency for React Native app

### ISSUE THREAD

**Issue by celestk** [DataDog/dd-sdk-reactnative#577]
Hi Team,

I was wondering if App Tracking Transparency needs to be enabled for IOS devices to track RUM. 

Thank you!

**Comment by plousada** [comment]
Hi @celestk,

No, we don't rely on any user identifier that would require the use of App Tracking Transparency framework at runtime.
We also don't share any data collect with 3rd party entities, unless you choose to do so yourself through export. 

We do provide [public APIs to transmit user tracking consent](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/#set-tracking-consent-gdpr-compliance) to data collection, that you can leverage in your app's flow. Data won't leave the users device unless consent is given to the SDK.

**Comment by louiszawadzki** [comment]
Hi @celestk,

There has not been any activity on this issue for a while so I'm going to close it.

Feel free to reopen it with more details if you still encounter any problem :)
