### ISSUE TITLE
Unable to Send RUM Actions with Datadog in React Native App during Login Process

### ISSUE THREAD

**Issue by belt-basya** [DataDog/dd-sdk-reactnative#591]
## Description

I have a React Native application where I'm using Datadog for monitoring, and I'm trying to send RUM (Real User Monitoring) actions during the login process to track successful and failed login attempts. However, the actions are not being sent successfully, and I'm encountering the following issue.

### Code

**App.js:**

```js
import {
  DdSdkReactNative,
  DdSdkReactNativeConfiguration,
  SdkVerbosity,
} from "@datadog/mobile-react-native";

const config = new DdSdkReactNativeConfiguration(
    clientToken,
    environmentName,
    rumApplicationId,
    true,
    true,
    true
);
config.site = "US5";
config.nativeCrashReportEnabled = true;
config.sessionSamplingRate = 80;
config.resourceTracingSamplingRate = 80;
config.firstPartyHosts = ["us5.datadoghq.com"];
config.serviceName = "mobile";
config.verbosity = SdkVerbosity.DEBUG;

DdSdkReactNative.initialize(config);

const App = () => {

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <FlipperAsyncStorage />
      <PaperProvider>
        <NavigationContainer>
          <AppStack />
        </NavigationContainer>
      </PaperProvider>
    </GestureHandlerRootView>
  );
};

export default App;
```

**Login.js:**

```js
import { DdRum, RumActionType } from "@datadog/mobile-react-native";

const handleLogin = async () => {
  try {
    // code to check valid user
    DdRum.addAction(RumActionType.TAP, 'login', {"app": 'mobile', "email": email.value, "status": "success"}, Date.now());
  } catch (error) {
    DdRum.addAction(RumActionType.TAP, 'login', {"app": 'mobile', "email": email.value, "status": "failure"}, Date.now());
    console.log(error);
  }
};
```

### Issue

The RUM actions are not being sent successfully, and the terminal logs show the following:

```
 DEBUG  DATADOG: Adding RUM Action “RCTView” (TAP)
 DEBUG  DATADOG: Starting RUM Resource #1706102314622/POST POST: http://192.168.1.112:3001/api/auth/login/mobile
 DEBUG  DATADOG: Stopping RUM Resource #1706102314622/POST status:401
 DEBUG  DATADOG: Adding RUM Action “login” (TAP)
```

### Additional Information

- I have already initialized Datadog in the `App.js` file.
- The code for handling login attempts and adding RUM actions is in a separate file (`Login.js`).
- The actions are not being sent, and the status code 401 suggests a failed login attempt.

### Question

What could be causing the failure of RUM actions being sent during the login process, and how can I resolve this issue? Any insights or suggestions would be greatly appreciated.

Screenshot of datadog dashboard

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/esVNg.png

**Comment by louiszawadzki** [comment]
Hi @belt-basya, thanks for reaching out!

Could you explain a bit more how you see that your actions are not being sent?
I can see a "tap on login" action on the screenshot you sent that corresponds to the code snippet you shared, was it from a different place in the code?

I would also recommend you to reach out to [our support team](https://www.datadoghq.com/support/) that will be more able and quicker to help you troubleshoot this issue as it can come from various places in the Datadog platform.

**Comment by belt-basya** [comment]
Hello @louiszawadzki, thank you for your quick response. It was my mistake. I was hurrying to see the result, but it did show the action after 5-6 minutes. So now you can close this issue. Thank you once again.

**Comment by louiszawadzki** [comment]
No worries :)
