### ISSUE TITLE
Apple Privavy file

### ISSUE THREAD

**Issue by eppisapiafsl** [DataDog/dd-sdk-reactnative#615]
Hi there! 👋 

Starting in April 2024, Apple will require a privacy file. [Apple - Privacy manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)

We must declare the Privacy manifest to be able to deploy to the stores, and this file must contain the privacy codes not just from the App but any third-party library we install in our app. 

I saw you are addressing the issues in the `dd-sdk-ios` project, https://github.com/DataDog/dd-sdk-ios/releases/tag/2.7.1 

Do we know when those changes will get in this repo?

It will be beneficial if the teams add the Privacy Manifest file in the repo 🙏

**Comment by louiszawadzki** [comment]
Hi @eppisapiafsl, thanks for reaching out!

We'll be updating the iOS SDK version very soon to benefit from these changes :)

**Comment by louiszawadzki** [comment]
Hi @eppisapiafsl,

We've released version `2.2.0` of the React Native SDK that includes the App Privacy manifest on iOS :) 

I'm going to close this issue, feel free to reopen it if you have any issue with it!
