### ISSUE TITLE
Unclear Datadog SDK Integration in hybrid apps after version 2 update

### ISSUE THREAD

**Issue by fedemartinm** [DataDog/dd-sdk-reactnative#616]
### Question

Hello everyone,

The instructions for using Datadog in hybrid applications were clear for version 1 of the SDK.

However, after updating to version 2, it seems unclear how to import the SDK from the native side if it has already been configured from React Native.

The document [hybrid_applications.md](https://github.com/DataDog/dd-sdk-reactnative/blob/cb2836eb9b3beeb738270f89dcf8aec0de029ff5/docs/hybrid_applications.md) says:

```rb 
# On iOS, add the Datadog iOS SDKs to your dependencies in your ios/Podfile to use in Objective C files.
pod 'DatadogCoreObjc', '~> 2.5.0'
pod 'DatadogLogsObjc', '~> 2.5.0'
pod 'DatadogTraceObjc', '~> 2.5.0'
...
```

However, these packages do not seem to be available. 
It is possible that they are referring to:
```rb
pod 'DatadogCore', '~> 2.5.0'
pod 'DatadogLogs', '~> 2.5.0'
pod 'DatadogTrace', '~> 2.5.0'
...
```

In that case, it would resolve the versions already installed by `@datadog/mobile-react-native`.

Is there any basic example of how to correctly import the SDK from the native side to log an error in RUM? 
Previously, it was possible with this code:
```ObjC
@import DatadogObjc;
...
[DDGlobal.rum addErrorWithMessage:message source:DDRUMErrorSourceCustom  stack:nil attributes:@{}];
```

Thank you in advance

**Comment by louiszawadzki** [comment]
Hi @fedemartinm, thanks for reaching out! 

Indeed there's a mistake in the documentation, you should keep importing the `DatadogSDKObjc` pod

```ruby
pod 'DatadogSDKObjc', '~> 2.5.0'
```

For usage you can look at [our documentation](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios/?tab=objectivec). For the example you gave, you would for instance do:

```objective-c
@import DatadogObjc;

DDRUMMonitor *rum = [DDRUMMonitor shared];
[rum addErrorWithMessage:message stack:nil source:DDRUMErrorSourceCustom  attributes:@{}];
```

Note that installing the `DatadogSDKObjc` pod currently imports all Datadog pods. If you can, we recommend using the SDK in Swift as much as possible to prevent this issue.

I'll fix the documentation, let me know if you need more information!
