### ISSUE TITLE
react-native 0.64 support

### ISSUE THREAD

**Issue by ap4y** [DataDog/dd-sdk-reactnative#62]
Project with react-native 0.64 and dd-sdk-reactnative 1.0.0-beta1 fail to compile on Android with the following error:

```
> Task :dd-sdk-reactnative:processDebugAndroidTestManifest FAILED
[androidx.vectordrawable:vectordrawable-animated:1.0.0] Warning:
	Package name 'androidx.vectordrawable' used in: androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1.
	uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.64.2] as the library might be using APIs not available in 19
```

react-native bumped `minSdkVersion`  to 21: https://reactnative.dev/blog/2021/03/12/version-0.64#major-dependency-version-changes

Bumping `minSdkVersion` here: https://github.com/DataDog/dd-sdk-reactnative/blob/main/android/build.gradle#L32 fixes the issue but I haven't done much testing beyond this.

**Comment by 0xnm** [comment]
Hello @ap4y! Can you please share what is the task/command executed which leads to this error? Normally, in your app, if you have native Android connected tests (under `androidTest`) and you want to run them, considering native code is located in the `app` folder, you need to run `:app:connectedCheck` and not task from the root module.

It seems just that `minSdk` is not defined in the execution.

**Comment by ap4y** [comment]
Hi @0xnm. I saw this error in our CI pipeline that runs `detox` tests (from the `androidTest`). We use fastlane for those builds with this definition:

```
    gradle(
      tasks: %w[assembleRelease assembleAndroidTest],
      project_dir: './android',
      system_properties: {
        'testBuildType' => 'release',
      },
    )
```

Which is roughly the what detox recommends to use: https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#2-apply-detox-configuration

**Comment by 0xnm** [comment]
It seems that this recommended configuration is not good and doesn't work in all the cases. The issue is that native code is distributed with `npm` not as library (binary), but as a source code. So dependencies with native code are included as modules in the project (in gradle terms it is `implementation project(...path...)`), and not as libraries. And proposed configuration above runs tasks for all the modules then.

I would recommend to narrow down the list of the modules which should have this task executed.

This problem wouldn't exist if `npm` would distribute native code parts as libraries/binaries.

If there is no possibility to specify the tasks to run, alternatively you can override `minSdk` property of the `dd-sdk-reactnative` module. Just add the following right at the end of your `app/build.gradle`, after script to import native modules is called:

```
rootProject.project(":dd-sdk-reactnative").afterEvaluate { ddSdkProject ->
    def androidExtension = ddSdkProject.extensions.getByName("android") as com.android.build.gradle.LibraryExtension
    androidExtension.defaultConfig.minSdkVersion = 21
}
```

**Comment by ap4y** [comment]
Thanks for the suggestions. We will try to figure it out in our gradle settings.

**Comment by Rehubbard** [comment]
> @0xnm's suggestion did not work for me. The project wouldn't build.
> 
> I ended up using patch-package to upgrade this library's midSdk to 21 in `android/build.gradle`. Is there any harm in this? Project seemed to build successfully. Maybe this project's minSdk can be upgraded to 21?
> 
> I can make a PR if that's helpful

The patch-package fix in `android/build.gradle` ended up crashing the app on launch in production. The error message was strange and I couldn't figure out the issue.

I ended up using @0xnm's suggestion. You'll need to change the package name in his suggestion to `datadog_mobile-react-native`. So it'll look like:

```
rootProject.project(":datadog_mobile-react-native").afterEvaluate { ddSdkProject ->
    def androidExtension = ddSdkProject.extensions.getByName("android") as com.android.build.gradle.LibraryExtension
    androidExtension.defaultConfig.minSdkVersion = 21
}
```

**Comment by ecexplorer** [comment]
Also ran into this issue compiling for Detox. I'm not sure why `minSdkVersion` isn't set to 21.

**Comment by louiszawadzki** [comment]
Hi @ecexplorer, 

This is indeed a bug on Detox build that's not fixed and documented: https://github.com/wix/Detox/issues/2712

Updating `minSdkVersion` to 21 was a risk earlier as it would mean to drop support for users of the library that wanted to support Android devices with a version below 21.
Now that the share of such devices is lower, we upgraded the `minSdkVersion`, it will be in the next release :) 

If you need to support Android devices below 21, you can still downgrade the `minSdkVersion` with `patch-package`.
