### ISSUE TITLE
Unable to build for iOS

### ISSUE THREAD

**Issue by tbeech** [DataDog/dd-sdk-reactnative#63]
Unable to build iOS app when Data Dog RN SDK is added as a dependency.

React Native Version: 0.64.0

**Describe what happened**
```
Undefined symbols for architecture arm64:
  "Network.NWPath.isConstrained.getter : Swift.Bool", referenced from:
      closure #2 () -> Swift.Bool? in closure #1 (Network.NWPath) -> () in Datadog.NWPathNetworkConnectionInfoProvider.init(monitor: Network.NWPathMonitor) -> Datadog.NWPathNetworkConnectionInfoProvider in libDatadogSDK.a(NetworkConnectionInfoProvider.o)
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libDatadogSDK.a(ActiveSpansPool.o)
  "(extension in Foundation):__C.NSFileHandle.readToEnd() throws -> Foundation.Data?", referenced from:
      Datadog.File.read() throws -> Foundation.Data in libDatadogSDK.a(File.o)
  "static Foundation.JSONEncoder.OutputFormatting.withoutEscapingSlashes.getter : Foundation.JSONEncoder.OutputFormatting", referenced from:
      static (extension in Datadog):Foundation.JSONEncoder.default() -> Foundation.JSONEncoder in libDatadogSDK.a(JSONEncoder.o)
  "(extension in Foundation):__C.NSFileHandle.seekToEnd() throws -> Swift.UInt64", referenced from:
      Datadog.File.append(data: Foundation.Data) throws -> () in libDatadogSDK.a(File.o)
  "(extension in Foundation):__C.NSFileHandle.write<A where A: Foundation.DataProtocol>(contentsOf: A) throws -> ()", referenced from:
      Datadog.File.append(data: Foundation.Data) throws -> () in libDatadogSDK.a(File.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
<img width="1231" alt="Screen Shot 2021-06-10 at 9 21 26 AM" src="https://user-images.githubusercontent.com/796007/121561364-45b68400-c9cd-11eb-8bdc-0366d2747712.png">

**Steps to reproduce the issue:**

1. yarn add dd-sdk-reactnative
2. from project root: cd ios
3. from ios folder: pod install
4. follow instructions here: https://github.com/DataDog/dd-sdk-reactnative#readme
4. open Xcode project and build

**Describe what you expected:**
For the app to build without error

**Additional context**
    - Version of the SDK: 1.0.0-beta1
    - A copy of your `package.json` file
[package.json.txt](https://github.com/DataDog/dd-sdk-reactnative/files/6632940/package.json.txt)

**Comment by xgouchet** [comment]
Hi @tbeech , sorry for the delay replying. Indeed we still need to have a proper troubleshooting documentation. This is something we'll trying to fix in the short term future. Let us know if you have any other issue with this library.
