### ISSUE TITLE
Does DD have a public certificate we can use for certificate pinning? 

### ISSUE THREAD

**Issue by gtokman** [DataDog/dd-sdk-reactnative#645]
### Question

We want to add cert pinning so middlemen cannot see the request bodies of DD endpoints. 

Maybe related: https://docs.datadoghq.com/data_security/guide/tls_cert_chain_of_trust/?tab=g1rootcertificateold

**Comment by plousada** [comment]
Hi @gtokman, 

We don't do certificate pinning by default in our SDKs. Mainly because older versions of the SDK would be blocked from uploading data after the certificate has been rotated. More [here](https://github.com/DataDog/dd-sdk-ios/issues/932#issuecomment-1188723298).

Are you looking to fork and add the support yourself?

**Comment by gtokman** [comment]
> Hi @gtokman,
> 
> We don't do certificate pinning by default in our SDKs. Mainly because older versions of the SDK would be blocked from uploading data after the certificate has been rotated. More [here](https://github.com/DataDog/dd-sdk-ios/issues/932#issuecomment-1188723298).
> 
> Are you looking to fork and add the support yourself?

That's fine. I was planning to get the public certificate myself w/ `openssl`. I was wondering if DD had an explicit certificate that teams could use to add cert pinning to their mobile apps.

I'm worried about it expiring if I fetch it myself using `openssl` and it expires, and our app pauses to record any metrics until it's updated. Does DD notify customers certificates are about to expire?

**Comment by plousada** [comment]
Unfortunately we don't provide any mechanism to notify customers our certificates are about to expire. Currently we renew our certificate at least 1 month in advance to its expire date, but might anticipate this further in the future.

Overall we don't believe certificate pinning is a good option for Mobile Apps unless you're able to control both the app release cycle and the endpoint certificate renewal process (which is not the case here). Even so, some customers on older versions of the app could still be locked out of using the endpoint post renewal.

**Comment by gtokman** [comment]
@plousada, thanks for the extra info.
