### ISSUE TITLE
Task :app:uploadStagingDebugSourcemaps FAILED with ❌ Configuration error: Error: DATADOG_API_KEY does not contain a valid API key for Datadog site datadoghq.com. after running datadog-react-native-wizard

### ISSUE THREAD

**Issue by riad40** [DataDog/dd-sdk-reactnative#647]
### Describe the bug

I'm trying to integrate crash reporting feature in my react native app, and after following the [docs](https://docs.datadoghq.com/real_user_monitoring/error_tracking/mobile/reactnative/#symbolicate-crash-reports), i couldn't run my android project anymore, and i'm getting this task failed with this error Task :app:uploadStagingDebugSourcemaps FAILED with ❌ Configuration error: Error: DATADOG_API_KEY does not contain a valid API key for Datadog site datadoghq.com. after running datadog-react-native-wizard 

### Reproduction steps

N/A

### Affected SDK versions

"@datadog/mobile-react-native": "^2.3.1"

### Latest working SDK version

N/A

### Did you confirm if the latest SDK version fixes the bug?

No

### Integration Methods

Yarn

### React Native Version

0.71.6

**Comment by marco-saia-datadog** [comment]
Hey @riad40, I apologise for the late reply!

We are currently working on some issues that were recently introduced with 2.3.0, including this one.

In the meantime, I suggest you discard the changes made by `datadog-react-native-wizard`, and follow [the alternative approach for uploading the source maps.](https://docs.datadoghq.com/real_user_monitoring/error_tracking/mobile/reactnative/#alternatives-to-datadog-react-native-wizard)

**Comment by marco-saia-datadog** [comment]
Hey @riad40!

Have you solved the issue on your side?

I believe this issue is unrelated to the fixes we have provided with the new updates. It seems like you did not set `DATADOG_API_KEY` variable in your environment.

I will close this issue for now, but feel free to re-open it if necessary!

**Comment by vtrikoupis** [comment]
I've got the same issue here

`DATADOG_API_KEY`
 as well as`DATADOG_SITE=datadoghq.eu` have been set to ensure I'm talking to the correct site

`❌ Configuration error: Error: DATADOG_API_KEY does not contain a valid API key for Datadog site datadoghq.eu.`

scoped, or unscoped
