### ISSUE TITLE
performance monitoring does not look correct

### ISSUE THREAD

**Issue by ChrisWiles** [DataDog/dd-sdk-reactnative#657]
### Question

I have had 2,000 sessions in the last day, but the metrics appear to only show the data for a single session.

For example, the FPS is inconsistent. If it were an average of all users, it should be much smoother. Also, when looking at 'Views with the highest percentage of slow renders,' it only shows data for half a day yesterday and is similarly erratic.

Am I doing something wrong? Why am I not seeing useful metrics?

![Screenshot 2024-04-23 at 8 51 51 AM](https://github.com/DataDog/dd-sdk-reactnative/assets/9455409/57598f35-2054-4913-8b8b-59ccf3dd33b1)
![Screenshot 2024-04-23 at 8 53 24 AM](https://github.com/DataDog/dd-sdk-reactnative/assets/9455409/dd6815e1-d503-41eb-82ad-77af085050a3)

``` js
const config = new DatadogProviderConfiguration(
  clientToken,
  environment,
  applicationId,
  true, // track User interactions (e.g.: Tap on buttons. You can use 'accessibilityLabel' element property to give tap action the name, otherwise element type will be reported)
  true, // track XHR Resources
  true // track Errors
);
// Optional: Select your Datadog website (one of "US1", "EU1", "US3", "US5", "AP1" or "GOV")
config.site = 'US1';
// Optional: Enable JavaScript long task collection
config.longTaskThresholdMs = 100;
// Optional: enable or disable native crash reports
config.nativeCrashReportEnabled = true;
// Optional: sample RUM sessions (here, 100% of session will be sent to Datadog. Default = 100%)
config.sessionSamplingRate = 100;

if (__DEV__) {
  // Optional: Send data more frequently
  config.uploadFrequency = UploadFrequency.FREQUENT;
  // Optional: Send smaller batches of data
  config.batchSize = BatchSize.SMALL;
  // Optional: Enable debug logging
  // config.verbosity = SdkVerbosity.DEBUG;
}
```

**Comment by marco-saia-datadog** [comment]
Hi @ChrisWiles, thank you for reaching out!

We strongly suggest to open a support ticket, and reference this GitHub issue there. This way our team can analyze the data of your organization and help you solve the issue.

In the meantime, we will double check how we calculate the metrics, and get back to you if we notice any problems that need to be fixed.

**Comment by ChrisWiles** [comment]
https://help.datadoghq.com/hc/requests/1666340
 
 
![Screenshot 2024-05-06 at 8 45 11 AM](https://github.com/DataDog/dd-sdk-reactnative/assets/9455409/c94d6608-82ec-4c95-b9c3-23686ceea7ff)


None of this data is useful. An average FPS of 7,000? Also, it still doesn't seem like an average across all devices.

**Comment by marco-saia-datadog** [comment]
Hello @ChrisWiles 👋 

Our latest release [v2.4.2](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.4.2) improves the JS Refresh Rate reliability by ensuring UI Thread safety, and making sure the reported time is always reset when the app is paused, to avoid unexpected peaks when the app is resumed.

I will close this issue for now, feel free to re-open it if you still experience the same problem :)
