### ISSUE TITLE
Unable to send batch because of a network error

### ISSUE THREAD

**Issue by joshuous** [DataDog/dd-sdk-reactnative#67]
**Describe what happened**
Datadog is able to log locally, but can't submit the logs.

![Screen Shot 2021-06-17 at 8 35 31 AM copy](https://user-images.githubusercontent.com/16533168/122319200-e0294100-cf52-11eb-9580-be6ae361fdca.png)

![Screen Shot 2021-06-17 at 9 48 51 AM copy](https://user-images.githubusercontent.com/16533168/122319209-e1f30480-cf52-11eb-89f7-8edd8eab0f38.png)

**Steps to reproduce the issue:**
iOS and Android, React-Native 0.62.2.

**Describe what you expected:**
Datadog logs are uploaded as expected.

**Additional context**
    - Version of the SDK: dd-sdk-reactnative 1.0.0-beta1
    - A copy of your `package.json` file: unable to provide

Is there a recommended way I can inspect what the network error is?

**Comment by 0xnm** [comment]
Hello @joshuous. This error happens at the transport layer: probably system has no Internet (which may happen often) or cannot connect to the Datadog endpoints. You can check if endpoints listed here are reachable from your network: https://github.com/DataDog/dd-sdk-android/blob/1.9.0-alpha2/dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEndpoint.kt.

Alternatively, you can open your Android module in Android Studio and connect with debugger to `DataOkHttpUploader#upload` method.

**Comment by joshuous** [comment]
Thanks @0xnm for the quick response! I believe you're right and found that it works when I test on a physical device instead of in the simulator.
