### ISSUE TITLE
Build error in Xcode 16 / iOS18

### ISSUE THREAD

**Issue by Ufo8MyCat** [DataDog/dd-sdk-reactnative#679]
### Describe the bug

Getting the following error when trying to build my app in Xcode 16 / iOS 18.

`Type 'UIApplication' does not conform to protocol 'UIKitAppBackgroundTaskCoordinator'`

`Candidate has non-matching type '((@MainActor () -> Void)?) -> UIBackgroundTaskIdentifier'`

### Reproduction steps

- Install Xcode 16
- Integrate Datadog SDK in an app
- Build the app and look at the errors

### Affected SDK versions

2.3.6

### Latest working SDK version

2.3.6

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

Yarn

### React Native Version

0.72.5

**Comment by akos-gg** [comment]
I see that this issue is fixed in the dd-sdk-ios [2.13.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.13.0) since 3 weeks, is there someone from the development team? When this will be updated in the React Native package? Its a build breaking change and seems a low hanging fruit to update the core sdk.

**Comment by marco-saia-datadog** [comment]
@Ufo8MyCat @pootyx Hello 👋 

The update is ready and it will soon be released, we apologise for the long wait 🙏

**Comment by marco-saia-datadog** [comment]
Hello @Ufo8MyCat @pootyx 👋 

We have released version [v2.4.0](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.4.0) of the Datadog React Native SDK, which includes the update of the native DataDog SDKs and fixes the reported issue.

Feel free to re-open this or another issue if the problem persists.

Thank you for your patience 🙏
