### ISSUE TITLE
Support Custom Grouping error tracking in RUM

### ISSUE THREAD

**Issue by michael-johnson-zip** [DataDog/dd-sdk-reactnative#692]
### Feature description

We utilize DD in a react native application with RUM and want to use Custom Grouping to further control how our errors are grouped in error tracking. From looking at the docs and digging through the code it looks like this currently isn't supported on the React Native SDK.

The [RUM Docs have examples](https://docs.datadoghq.com/logs/error_tracking/custom_grouping/?tab=browser#rum) for Browser, iOS, Android, and Flutter, but not React Native.

### Proposed solution

What I tried was using an [`errorEventMapper`](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative/#modify-or-drop-rum-events) to update error events before they're sent to DD, but this doesn't have the attributes exposed in a way they can be modified. Perhaps being able to set an `errorFingerprint` type of attribute here would be one approach.

**Comment by marco-saia-datadog** [comment]
Hello @michael-johnson-zip, thank you for reaching out! We are going to introduce `errorFingerprint` in our React Native SDK very soon. I will link the PR as soon as it's ready so that you can follow the progress from here.

**Comment by marco-saia-datadog** [comment]
Hello @michael-johnson-zip, `errorFingerprint` has been introduced with https://github.com/DataDog/dd-sdk-reactnative/pull/700 and it will soon be released!

**Comment by michael-johnson-zip** [comment]
Awesome. Thanks @marco-saia-datadog!

**Comment by marco-saia-datadog** [comment]
Hello @michael-johnson-zip! 👋 

We have released [v2.4.2](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.4.2), which introduces custom error fingerprinting for logs.

Let us know if it works for you, I will close this issue for now :)
