### ISSUE TITLE
Setting a custom `serviceName` does not work

### ISSUE THREAD

**Issue by jb-berthet** [DataDog/dd-sdk-reactnative#698]
### Describe the bug

When I set a `serviceName` in my `build.gradle` file (as stated in your [docs](https://docs.datadoghq.com/fr/real_user_monitoring/error_tracking/mobile/reactnative/#passing-options-for-your-uploads)), this service name is not the one that appears on the source map list. This option should apply and the source maps should be linked to the given service.

After further investigation, it looks like your gradle file does unexpected things in [`getServiceName` function](https://github.com/DataDog/dd-sdk-reactnative/blob/f527de2facb85c3e5bdfcc7e46e2931c1f9e8039/packages/core/datadog-sourcemaps.gradle#L270-L277).

Indeed, the docs tells us to declare a map object:
```groovy
project.ext.datadog = [
	serviceName: "my-awesome-application"
]
```

And then your gradle file checks this Map object `hasProperty` when it is a Groovy method to check whether a class comes with a property, but here we don’t have a class but a Map.

**Solution**: instead of checking if `project.datadog.hasProperty('serviceName')`, just try to access directly the property (as you're doing in the following check actually) is enough

### Reproduction steps

1. Use the wizard to install source maps upload files (cf. [this documentation](https://docs.datadoghq.com/fr/real_user_monitoring/error_tracking/mobile/reactnative/#get-deobfuscated-stack-traces))
2. In your `build.gradle` file, add the following lines (cf. [docs](https://docs.datadoghq.com/fr/real_user_monitoring/error_tracking/mobile/reactnative/#passing-options-for-your-uploads)):
```groovy
project.ext.datadog = [
	serviceName: "my-awesome-application"
]
```
3. Build the app

You should see logs related to source maps upload in your build logs and the service name will match your application ID and not the service name you specified in the `build.gradle`.

### Affected SDK versions

2.4.1

### Latest working SDK version

IDK

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

NPM

### React Native Version

0.71.10

**Comment by marco-saia-datadog** [comment]
Hi @jb-berthet, that seems to be an error on our side, thank you for your contribution!
