### ISSUE TITLE
2.4.2 build on android error

### ISSUE THREAD

**Issue by wcastand** [DataDog/dd-sdk-reactnative#707]
### Describe the bug

when i try to build my expo app with the latest release on android i get this:

```
> Task :datadog_mobile-react-native:compileDebugKotlin FAILED
e: file:///Volumes/dev/retails/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/FrameRateProvider.kt:43:24 Unresolved reference: postFrameCallback
e: file:///Volumes/dev/retails/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/FrameRateProvider.kt:48:49 Unresolved reference: getInstance
e: file:///Volumes/dev/retails/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/FrameRateProvider.kt:49:28 Unresolved reference: postFrameCallback
e: file:///Volumes/dev/retails/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/FrameRateProvider.kt:55:49 Unresolved reference: getInstance
e: file:///Volumes/dev/retails/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/FrameRateProvider.kt:56:28 Unresolved reference: removeFrameCallback

FAILURE: Build failed with an exception.
```

### Reproduction steps

install "@datadog/mobile-react-native": "^2.4.2",
and try to build android app

### Expected behavior

be able to build the android app

### Affected SDK versions

2.4.2

### Latest working SDK version

2.4.1

### Did you confirm if the latest SDK version fixes the bug?

No

### Integration Methods

Source

### React Native Version

0.73.3

### Other relevant information

seems to be related to FramerateProvider added in 2.4.2

**Comment by RamboWasReal** [comment]
same error

**Comment by AlbertHernandez** [comment]
Same here, using 2.4.1 works fine

**Comment by marco-saia-datadog** [comment]
@wcastand @RamboWasReal @AlbertHernandez 

Hello 👋 Thank you for reaching out!

Can you please share your `package.json`? I am particularly interested in your Expo and React Native packages versions.

**Comment by wcastand** [comment]
expo: ~51.0.22
react-native": 0.74.3

**Comment by short-dsb** [comment]
This is also happening outside of Expo with React Native v0.74.3.

**Comment by ghost** [comment]
Same here, no expo RN v0.74

**Comment by malavshah9** [comment]
Same here with 
```
    "expo": "^51.0.0",
    "react-native": "0.74.3",
```

**Comment by dhleeOfficial** [comment]
any update?

**Comment by MichaelPeterJoyce** [comment]
Same issue

**Comment by AlexLFundbox** [comment]
Same here, no expo, RN v0.74.3

**Comment by MathiasLimaCompass** [comment]
We had to move to version 2.1.0 to resolve @wcastand 

   "@datadog/mobile-react-native": "2.1.0",
   "@datadog/mobile-react-navigation": "2.1.0",
   
    "react-native": "0.74.3",

**Comment by wcastand** [comment]
was working fine for me until 2.4.2, even 2.4.1
why did you go so far back? 
we are on expo router so we don't use react-navigation packages directly at least.

**Comment by dconlisk** [comment]
Same issue. Downgrading to 2.4.1 worked for us, very grateful for this issue being raised!

**Comment by AlbertHernandez** [comment]
Hi @marco-saia-datadog, I am using react native 0.74.3, expo 51.0.22

**Comment by marco-saia-datadog** [comment]
Thank you for reaching out, we are addressing the issue in v2.4.3. We can confirm that downgrading to 2.4.1 will solve the issue as for now. We apologise for the inconvenience!

**Comment by marco-saia-datadog** [comment]
Hey 👋 😃 

Version [v2.4.3](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.4.3) has been released! Thank you for your patience :)

**Comment by hroland** [comment]
hi @marco-saia-datadog! experiencing the same kotlin build error under:

```
"expo": "51.0.32",
"react-native": "0.75.2"
```

whats the recommended expo/RN version for v2.4.3?
