### ISSUE TITLE
after installation of beta3. "None of these files exist: * node_modules/dd-sdk-reactnative/src/rum/instrumentation/DdRumReactNativeNavigationTracking(.native..)"  

### ISSUE THREAD

**Issue by nauman-matloob** [DataDog/dd-sdk-reactnative#77]
Thanks for taking the time for reporting an issue!
**Describe what happened**
First of all i installed beta2 which got me the react-navigation error.
i checked this issue to solve it :
https://github.com/DataDog/dd-sdk-reactnative/issues/76
but now i get the this error :
`Failed building JavaScript bundle.
Unable to resolve module ./rum/instrumentation/DdRumReactNativeNavigationTracking from /mnt/c/Users/nauman/Desktop/personal/kingchickenapp/node_modules/dd-sdk-reactnative/src/index.tsx:

None of these files exist:
  * node_modules/dd-sdk-reactnative/src/rum/instrumentation/DdRumReactNativeNavigationTracking(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * node_modules/dd-sdk-reactnative/src/rum/instrumentation/DdRumReactNativeNavigationTracking/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
> 1 | /*
  2 |  * Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
  3 |  * This product includes software developed at Datadog (https://www.datadoghq.com/).
  4 |  * Copyright 2016-Present Datadog, Inc.`
**Steps to reproduce the issue:**
i only installed the latest version of the package and when i start the project i got this.
**Describe what you expected:**
to work.
**Additional context**
i am using the latest version of expo (41)
`{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "@babel/core": "~7.9.0",
    "@babel/plugin-transform-react-jsx": "^7.3.0",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-async-storage/async-storage": "^1.13.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "6.0.0",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "dd-sdk-reactnative": "^1.0.0-beta3",
    "expo": "^41.0.1",
    "expo-app-loading": "^1.0.3",
    "expo-font": "~9.1.0",
    "expo-linear-gradient": "~9.1.0",
    "expo-notifications": "~0.11.6",
    "expo-permissions": "~12.0.1",
    "jsonwebtoken": "^8.5.1",
    "native-base": "^2.15.2",
    "react": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-easy-grid": "^0.2.2",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-modal": "^11.5.3",
    "react-native-qrcode": "^0.2.7",
    "react-native-qrcode-svg": "^5.3.2",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "12.1.0",
    "react-native-webview": "11.2.3",
    "react-redux": "^7.2.4",
    "react-timer-mixin": "^0.13.4",
    "redux": "^4.1.0",
    "restful.js": "^0.9.6",
    "socket.io-client": "^4.1.2",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "unimodules-permissions-interface": "^6.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "eslint": "^6.5.1",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.16.0",
    "redux-devtools": "^3.7.0"
  }
}
`
Thank you for your help.

**Comment by 0xnm** [comment]
Hello @nauman-matloob. Do you try to reference `DdRumReactNativeNavigationTracking` from your code? Otherwise I would suggest you to reset the cache of Metro bundler, this file is indeed is not part of `beta3` and you shouldn't reference it.

**Comment by nauman-matloob** [comment]
Sorry this error was from another package 'restful.js' which couldn't found some dependencies.

Thank you for your response.
