### ISSUE TITLE
[Feature Request] Add support for Expo Config Plugins

### ISSUE THREAD

**Issue by leggomuhgreggo** [DataDog/dd-sdk-reactnative#78]
I am on a team that's fixin to start work on a cross-platform Expo app, intended to replace our three legacy clients. Wanted to inquire whether y'all would consider adding support for [Config Plugins](https://docs.expo.io/guides/config-plugins/), so this library can be used with the Expo Managed Workflow (i.e. without ejecting)

Thanks for your consideration!

## Feature Context

Over the past several months Expo has introduced features which enable apps to use external native modules, without ejecting Expo's managed workflow. 

The customizations to the iOS and Android code that are required by a given native module are automated, using an AST-based API that Expo provides through  "Config Plugins" feature.

These automations (called "mods") are executed during a new "Prebuild" phase, in which boilerplate ios and android directories are created — and then their respective files are altered, based on the instructions in a given modules config plugin. The end result is essentially the same as if you ejected and manually changed the ios/android files. 

Here's the [Expo blog post](https://blog.expo.io/introducing-expo-run-commands-835ae8da4813) announcing Config Plugins and the associated feature-set.

## Overview of Proposed Implementation

The process for creating a Config Plugin is detailed here:
https://docs.expo.io/guides/config-plugins/#creating-a-plugin

There are a few different "recipes" for how to implement — but the gist of it is:

- Create the `app.plugin.js` file, at the project root — which serves as a standard entrypoint where expo can resolve the plugin code. [ex: [`expo-camera`](https://github.com/expo/expo/blob/master/packages/expo-camera/app.plugin.js)]
- Export a function prefixed using "with" (eg `withFeature`) which accepts a `config` object that can be used, along with `@expo/config-plugins` methods, to implement mods for each platform's native code. [ex: [`withCamera`](https://github.com/expo/expo/blob/master/packages/expo-camera/plugin/src/withCamera.ts)]
- Add mods corresponding to the setup steps in your README.md
- Celebrate!

**Comment by xgouchet** [comment]
Hi @leggomuhgreggo , 
indeed this is a direction we would like to go forward with, and hopefully we can provide a "Expo Managed Workflow" compatible SDK in the future.

**Comment by brookemitchell** [comment]
If you would like any support adding an expo config plugin, @evanbacon has offered to help support 😆 🙏 https://twitter.com/Baconbrix/status/1463611262055583750

**Comment by xgouchet** [comment]
@brookemitchell thanks for the tip!
@EvanBacon, you're welcome to give it a try if you want to.

**Comment by EvanBacon** [comment]
Based on the [setup](https://github.com/DataDog/dd-sdk-reactnative#setup) this package doesn't appear to need an Expo config plugin. Expo config plugins are used for adding extra values to the Info.plist, AndroidManifest.xml, etc. I can open a PR to update the docs accordingly.

**Comment by hindmanj** [comment]
I can confirm that as of 1.0.0-rc3 with Expo SDK 42 and EAS Build, this does work correctly, so no config plugin may be needed unless the implementation is changed in some fashion.

**Comment by brookemitchell** [comment]
Can also confirm, working great. We had to cross our fingers and ship to production to get rum session, debugging locally we couldn't get things working but may have been our end. 🚀

**Comment by louiszawadzki** [comment]
Hi all,
We now support Expo managed workflow, you can learn about how to enable our SDK with Expo here: https://github.com/DataDog/dd-sdk-reactnative/blob/develop/docs/expo_development.md
If you are using Expo Go, you'll find instructions on how to move to development builds or to prevent your app from crashing with the SDK while using Expo Go.

For now, there is no need to add plugins ;) 

I'm closing this issue, feel free to open a new one if the documentation is missing something :)
