### ISSUE TITLE
Issue with `react-native-navigation` not resolved when upgrading from beta1 to beta2

### ISSUE THREAD

**Issue by WNemencha** [DataDog/dd-sdk-reactnative#80]
**Describe what happened**

Hey DataDog ! Hope you're all doing well :)

We encountered an issue today when updating `dd-sdk-reactnative` so I wanted to make sure to share it, as well as a possible fix for it. 

We make use of `@react-navigation/native` in our project and I saw you recently added support for `wix/react-native-navigation` which is great! The issue here is that metro tries to resolve `react-native-navigation` even we don't have it in our dependencies. I feel its because module `index` exports the `DdRumReactNativeNavigationTracking` which leads Metro to resolve the imports in there.

I guess people using it the other way around would get a pretty similar issue just with `@react-navigation/native` not being resolvable ^^

Here's the error:

```
13:48:27
  If you are sure the module exists, try these steps:
13:48:27
   1. Clear watchman watches: watchman watch-del-all
13:48:27
   2. Delete node_modules and run yarn install
13:48:27
   3. Reset Metro's cache: yarn start --reset-cache
13:48:27
   4. Remove the cache: rm -rf /tmp/metro-*
13:48:27
     6 | 
13:48:27
     7 | import React from 'react'
13:48:27
  >  8 | import { ComponentDidAppearEvent, Navigation } from 'react-native-navigation'; // <---- THIS
13:48:27
     9 | import { DdRum } from '../../foundation';
13:48:27
    10 | /**.
13:48:27
      at ModuleResolver.resolveDependency (/Users/[snipped]/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
13:48:27
      at DependencyGraph.resolveDependency (/Users/[snipped]/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
13:48:27
      at Object.resolve (/Users/[snipped]/node_modules/metro/src/lib/transformHelpers.js:317:42)
13:48:27
      at resolve (/Users/[snipped]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
13:48:27
      at /Users/[snipped]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
13:48:27
      at Array.reduce (<anonymous>)
13:48:27
      at resolveDependencies (/Users/[snipped]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
13:48:27
      at /Users/[snipped]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
13:48:27
      at Generator.next (<anonymous>)
13:48:27
      at asyncGeneratorStep (/Users/[snipped]
/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
13:48:27
  info Run CLI with --verbose flag for more details.
13:49:46
  Process exited with code 1 (Step: Create React native bundle for Android (Command Line))
13:48:27
  Step Create React native bundle for Android (Command Line) failed
```

**Steps to reproduce the issue:**

1. Setup a project with dd-sdk-reactnative @ 1.0.0-beta1
2. Update to 1.0.0-beta2
3. Try to compile the iOS app, results in this

**Describe what you expected:**

I except the app to just compile as it was before ^^

**Temporary fix**

In local, removing the export for the module we don't use makes metro happy

**Additional context**
    - Version of the SDK: 1.0.0-beta2
    - A copy of your `package.json` file: Can't do that ^^

**Comment by 0xnm** [comment]
Hello @WNemencha. We will address this issue in https://github.com/DataDog/dd-sdk-reactnative/pull/79. In the meantime you can use version `1.0.0-beta3` which has no dependency on `react-native-navigation` as temporary fix.

**Comment by WNemencha** [comment]
Thanks for the fast reply and the great work, already made a PR in house for using beta3 👍
