### ISSUE TITLE
Is Error Tracking Feature working with this?

### ISSUE THREAD

**Issue by ZeroCho** [DataDog/dd-sdk-reactnative#81]
I can see my app's errors in RUM -> Sessions -> Errors, but not in UX Monitoring -> Error Tracking.

When I visit Error Tracking page, I see "Get started with Error Tracking" with two buttons "Set up RUM" and "Upload Source Maps". I already set up RUM, but I didn't upload the source code as I don't know how to upload React Native source code.

I'm curious whether I didn't set up properly or this feature is not yet ready.

I'm using "dd-sdk-reactnative": "^1.0.0-beta1", with following initialization
```
const config = new DdSdkReactNativeConfiguration(
  'REMOVED',
  __DEV__ ? 'development' : 'production',
  'REMOVED',
  true, // track User interactions (e.g.: Tap on buttons)
  true, // track XHR Resources
  true, // track Errors
);
// Optional: enable or disable native crash reports
config.nativeCrashReportEnabled = true;
DdSdkReactNative.initialize(config);
```

**Comment by xgouchet** [comment]
Hi, the Error Tracking feature for now only supports native Android Application. It will soon support native iOS application, and eventually it will support cross platform application such as React Native. I can't give any timeline or ETA yet, but this is scheduled in our roadmap.

**Comment by ZeroCho** [comment]
Thank you for letting me know!

**Comment by alejosod** [comment]
@xgouchet any news about IOS and react-native support?

**Comment by xgouchet** [comment]
Hi @alejosod , as mentioned earlier, this is a feature we're actively working on. But we can't give any ETA yet as we want to make sure this feature is reliable and fully working before releasing it, and not rush into things.

**Comment by sregg** [comment]
Is iOS native crash reporting now supported? If so, how does dsym upload work?
Also, how does JS source maps upload work?

**Comment by louiszawadzki** [comment]
Hi everyone,
We've released version 1.0.0-rc8 yesterday which includes native iOS crash reporting 🎉

Please note that If you are using distributed tracing, you now need to specify your hosts as first-party hosts in your SDK config after upgrading to this version:

```
config.firstPartyHosts = ['example.com'];
```

You can upload dsyms by using our fastlane plugin, our github action or our cli, you'll find more on that here: https://docs.datadoghq.com/fr/real_user_monitoring/ios/crash_reporting/?tab=cocoapods#symbolicate-crash-reports

I'll come back to you soon regarding js source maps upload :)

**Comment by louiszawadzki** [comment]
@sregg JS source maps are high on our priority list but they aren't supported yet.
I'll let you know as soon as it is possible to upload them.

**Comment by nisargrthakkar** [comment]
Is there any update on React Native Source map upload?

**Comment by xgouchet** [comment]
Hi @nisargrthakkar, this is still under active development, we will update this issue as soon as this feature is fully supported.

**Comment by louiszawadzki** [comment]
Hi, 

Source maps upload is now supported for React Native.

You will find documentation on how to set it up here: https://docs.datadoghq.com/real_user_monitoring/error_tracking/reactnative/.

I am closing the issue, feel free to open new ones dedicated to any specific issue you would face.
