### ISSUE TITLE
setAttributes is not adding any attributes to the logs

### ISSUE THREAD

**Issue by dusan-dragon** [DataDog/dd-sdk-reactnative#87]
**Describe what happened**
looks like calling `setAttributes` does not have any effect on logs and these attributes are not appended to the logs.

**Steps to reproduce the issue:**

**Describe what you expected:**
We are calling `setAttributes` with some global data which should appear in all logs logged after that point forward

**Additional context**
    - Version of the SDK: "dd-sdk-reactnative": "1.0.0-beta3",

**Comment by xgouchet** [comment]
Hi @dusan-dragon, 
thanks a lot for reaching out to us, indeed this is something we haven't solved yet, for now we are focusing a lot on RUM functionalities, and will improve Logs and Spans in future version, and we'll definitely fix this specific issue.
