### ISSUE TITLE
Are you able to support Android SDK version 21?

### ISSUE THREAD

**Issue by everestster** [DataDog/dd-sdk-reactnative#99]
I am getting the following error when I build.

**Additional context**
> Task :dd-sdk-reactnative:processDebugAndroidTestManifest FAILED
[androidx.vectordrawable:vectordrawable-animated:1.0.0] \.gradle\caches\transforms-3\f14803a315f67746b9fb71068be927be\transformed\vectordrawable-animated-1.0.0\AndroidManifest.xml Warning:
        Package name 'androidx.vectordrawable' used in: androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1.
\node_modules\dd-sdk-reactnative\android\build\intermediates\tmp\manifest\androidTest\debug\manifestMerger2972781339863275701.xml:5:5-74 Error:
        uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.64.2] \.gradle\caches\transforms-3\90a8cc388b0622ca7803b1b02bc7114f\transformed\jetified-react-native-0.64.2\AndroidManifest.xml as the library might be using APIs not available in 19
        Suggestion: use a compatible library with a minSdk of at most 19,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dd-sdk-reactnative:processDebugAndroidTestManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 18s
220 actionable tasks: 20 executed, 200 up-to-date

**Comment by 0xnm** [comment]
Hello @everestster. Please check the following solution https://github.com/DataDog/dd-sdk-reactnative/issues/62#issuecomment-858413322.

**Comment by Rehubbard** [comment]
Can this project not be updated to use minSdk: 21? The proposed solution above did not work for me, but updating minSdk using patch-package did. Thanks for the great project!

**Comment by mustafaskyer** [comment]
Still not working after trying all solutions

**Comment by ecexplorer** [comment]
Ran into this issue compiling for Detox. I'm not sure why minSdkVersion isn't set to 21.
